### ISSUE TITLE
Interface full of glitches on Mac High Sierra 10.13.2

### ISSUE THREAD

**Issue by ondraspa** [webcamoid/webcamoid#107]
### Summary

The interface does not show any icons and text is full glitches.

* Webcamoid information: (8.1.0) (Mac)
* Operating System information: (Mac High Sierra) (10.13.2) (unix)
* Any other useful information:  screenshots
![snimek obrazovky 2018-01-16 v 14 53 36](https://user-images.githubusercontent.com/25400706/34992904-f87ac9ce-face-11e7-833a-aef5ca836508.png)

**Comment by hipersayanX** [comment]
What graphics card are you using?

**Comment by ondraspa** [comment]
Intel integrated 4600

**Comment by hipersayanX** [comment]
Try running webcamoid as:

QT_QUICK_BACKEND=software /Applications/webcamoid.app/Contents/MacOS/webcamoid

**Comment by ondraspa** [comment]
It works.

**Comment by hipersayanX** [comment]
Great! it will be fixed in 8.5.0.

**Comment by ondraspa** [comment]
OK thanks a lot.

**Comment by hipersayanX** [comment]
Fixed in 8.5.0.
