### ISSUE TITLE
How to put the video stream in replay loop?

### ISSUE THREAD

**Issue by arpcpro** [webcamoid/webcamoid#109]
1) Is there any way to put the mp4 video file from the virtual cam replaying in an infinite loop?

2) What symptoms to collect in order to report a crash?
I was playing with the effects and after a while the app crashed. Even after rebooting Windows 8.1, the app would crash immediately after launching it. I had to reset settings in registry to make it work again.

Thanks

**Comment by hipersayanX** [comment]
>Is there any way to put the mp4 video file from the virtual cam replaying in an infinite loop?

Webcamoid already does that by default, when the video ends it will play from the start again. If it does not do that, it is maybe a bug.

>What symptoms to collect in order to report a crash?

Give me enough information to reproduce in my computer, for example what effects were you switching between when the crash occurred, if you were playing with recording settings, what formats and codecs were you using. .
Also try to reproduce the crash several times (random crash are quite hard to debug), to isolate the crash sequence.

>I had to reset settings in registry to make it work again.

The configs can actually have valuable information for debugging, next time Webcamoid crash upload the config tree as a gist.
