### ISSUE TITLE
Build and install in Windows: not clear with current QT version

### ISSUE THREAD

**Issue by inoculator** [webcamoid/webcamoid#122]
Plattform: Windows 10
current QT Build: Qt Creator 4.6.1
Document: https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Windows

For QT Install which compiler to install is missing. There is a hughe list during install. Not clear for user which to select.
Additional Arguments for Build not found. Might have moved to other location?

Please check, if documentation is really current and matching versions of QT.

**Comment by hipersayanX** [comment]
[wiki](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Windows) updated.
