### ISSUE TITLE
Does Webcamoid support 4K?

### ISSUE THREAD

**Issue by arpcpro** [webcamoid/webcamoid#123]
Does it support a virtual 4k webcam with resolutions like 3840 × 2160 or 4096 × 2160 ?

**Comment by hipersayanX** [comment]
I don't have the means to prove, but it may work. Webcams vendors normally compress higher resolutions frames in MP4 or MJPG to save bandwidth, and Webcamoid can decompress the stream with FFmpeg and GStreamer so it may work.

**Comment by arpcpro** [comment]
Thanks
