### ISSUE TITLE
Unable to record audio in win10

### ISSUE THREAD

**Issue by foppedisano** [webcamoid/webcamoid#125]
### Summary

I'm trying to record a video with audio but audio is always muted like the "record audio" option was disabled. But it is enabled.

### Current Behavior

I configured the mic input to use (I tried all my available mics) and then tried to record video with the "record audio" option enabled.

### Expected Behavior

How it should have work?

### Steps to Reproduce

The video output configuration is webm with libvorbis audio codec.
But i tried differnt configurations (e.g. mp4 with mp3 audio)  with the exact same results.

Video file with no audio.

### Suggestions and tips
My hypotesis is that it's not a codec issue... it semms the audio is not recorded from the source.

### Your Environment

windows 10
webcamoid 801 win64
Various webcam tried

**Comment by hipersayanX** [comment]
Fixed in 8.5.0.
