### ISSUE TITLE
Cancel button from the file manager window when record is clicked

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [webcamoid/webcamoid#130]
### Summary
Cancel button from the file manager window.

### Current Behavior
Does not work when record is clicked and cancel is needed.

### Expected Behavior
Must cancel the file recording to save, and go back to webcamoid

### Steps to Reproduce
1.  Click on Record
2.  File manager window opens to let you save the file
3.  Click on Cancel

### Your Environment
* Webcamoid information:  last, 32 and 64 bits
* Operating System information: Window 10 pro 64bits

**Comment by hipersayanX** [comment]
I was able to reproduce this only once, everything was disabled except for Cancel button, after pressing Cancel the dialog reappeared normally and was able to save/cancel, some extra info, the system was very busy updating. I was not able to reproduce it never again.
If this happen to someone else, just close the dialog and reopen it again.
IMO this is more likely a Qt bug, I don't think it's fixable from my side, [the code](https://github.com/webcamoid/webcamoid/blob/cb7daefa6b85f73fe58618f943a45d9616b53f1a/StandAlone/src/mediatools.cpp#L298) for that dialog does not have any special hackery that can cause that behavior.
