### ISSUE TITLE
My webcam has gone when i installed webcamoid i have turn off my pc, please fix and update for my cam driver

### ISSUE THREAD

**Issue by toozzb** [webcamoid/webcamoid#131]
Please help me i cannot enable my cam on this software it will always block my camera on manycam and ur software like this

i have to uninstall and turn off my pc to make it work again after uninstall

![frfrfrf](https://user-images.githubusercontent.com/38509697/42405736-0540e634-8193-11e8-919f-1bb4b4d97e46.png)

**Comment by hipersayanX** [comment]
You don't need to uninstall, is just a problem of camera control adjustments, try moving the sliders of contrast and brightness.

**Comment by toozzb** [comment]
can you give me an example, it is because when i close this software i try go on manycam its all blocked, i have to uninstall sir even still i cant do anyhting it blocks my manycam

**Comment by hipersayanX** [comment]
Install Webcamoid again and move the sliders in the right of you capture.

![42405736-0540e634-8193-11e8-919f-1bb4b4d97e46](https://user-images.githubusercontent.com/1249885/42406056-e86da806-8176-11e8-9419-599b3624c914.png)

If it's a external camera you can also disconnect and reconnect again, if it's integrated camera just turn off and turn on the notebook. And settings will be back to before.

Don't worry that your webcam is not damaged.

**Comment by toozzb** [comment]
connect to my teamviewer please its all damaged i have to do my method to stop this not work
connect to me
id 
719 602 402
pass
7760

**Comment by hipersayanX** [comment]
Sorry, no TeamViewer. Did you tried what I said?

**Comment by toozzb** [comment]
add me on discord please i will screenshare or skype

i tried what u said this is about ur software just block my cam

**Comment by hipersayanX** [comment]
Problems must be reported HERE.

**Comment by toozzb** [comment]
i swear to god this is just blocking my computer i cannot cam up on any website or even apps, this software will block on my case i have to unisntall and turn off my pc so it fix itself.

**Comment by toozzb** [comment]
yes, before i did that i have to uninstall first and this is about your software bro it wont let me use on my cam driver or computer its a usb vga u can see on op

**Comment by hipersayanX** [comment]
If it works in GNU/Linux, then is a problem of your driver, try reinstalling the UVC driver, follow [these instructions](https://help.huddlecamhd.com/support/solutions/articles/5000624209-how-do-i-remove-a-bad-copy-of-the-uvc-driver-from-my-windows-machine-).

**Comment by ROBERT-MCDOWELL** [comment]
if it's a USB cam so sometimes when the camera is forced to change a resolution it's simply freeze, the best being to unplug and plug the USB cam again

**Comment by toozzb** [comment]
sir this an laptop camera Robert its not an usb camera the camera is inside of my laptop
i will do it now lets see

**Comment by hipersayanX** [comment]
@ROBERT-MCDOWELL I think it just trolling, probably just tapped the webcam, if you look the frame you can see the garbage pixels and that means the webcam is working.

**Comment by hipersayanX** [comment]
I has been thinking and re-thinking this, definitely there was a communication language problem, @toozzb I don't understand your english well enough, sorry for that. 
And to clarify, what was absolutely wrong on your side (@toozzb), **don't ever ask for solving your issues outside the issue tracker** and **and don't ever ask a developer to fix your computer** we are not your personal service, doing things like that will get you kicked out everywhere.
