### ISSUE TITLE
Hebrew translation was overwritten by the English strings

### ISSUE THREAD

**Issue by yarons** [webcamoid/webcamoid#136]
I've finished translating Webcamoid several days ago, now I went back to look at the translation and about 240 strings were overwritten by the English strings on the latest update, this forces me to go through all the strings, one by one and revert to the Hebrew translation instead.

I'm not willing to do this all over again, how can we make sure my translation will be restored?

**Comment by hipersayanX** [comment]
Weblate de-synchronized again and there were a merge conflict. Do you remember some source string and file that was translated and is missing? maybe is still in the git history.

Also not sure but I'm thinking on using Weblate just as a mirror, and let user translate the source strings directly, to prevent things like this to happen.

**Comment by yarons** [comment]
We can contact @nijel, is there anything you can add to the bug report?
If we can make sure it won't happen again it can be a pretty awesome tool (I'm using it for several projects myself).

**Comment by hipersayanX** [comment]
This is the error message from Weblate.

```
Auto-merging StandAlone/share/ts/he.ts
CONFLICT (content): Merge conflict in StandAlone/share/ts/he.ts
Auto-merging StandAlone/share/ts/de.ts
CONFLICT (content): Merge conflict in StandAlone/share/ts/de.ts
Automatic merge failed; fix conflicts and then commit the result. (1)
```

Then followed the [How to fix merge conflicts in translations?](https://docs.weblate.org/en/latest/faq.html), and when merged from weblate/master it never marked a merge conflict in my repository, checked the files and everything was fine, git log also looks ok, then pushed the merged changes to the repository, the error message was still there.
Then, tried  everything from Weblate interface, pull, push, rebase, and finally I had no option but to reset Weblate, and that fixed the error.

>pretty awesome tool.

And it is, but I think it need a bit more rethink.

**Comment by nijel** [comment]
What happened is that there were still some pending changes when you've resolved the merge conflict. So after pushing it, Weblate flushed the pending changes and the conflict was still there. I've just updated the docs to recommend committing pending changes in Weblate first.

**Comment by hipersayanX** [comment]
@nijel Thanks!
