### ISSUE TITLE
Seems to only support Intel Processors ???

### ISSUE THREAD

**Issue by NigBrooks** [webcamoid/webcamoid#145]
Just installed to try, came up with:

OMP: Warning #72: KMP_AFFINITY: affinity only supported for Intel(R) processors.
OMP: Warning #71: KMP_AFFINITY: affinity not supported, using "disabled".

Then 'stopped working'

**Comment by hipersayanX** [comment]
That message does not come from Webcamoid, are you running in an special condition?

**Comment by hipersayanX** [comment]
Information missing, it may work on any processor in theory.
