### ISSUE TITLE
GIF Source displays incorrectly and in black and white.

### ISSUE THREAD

**Issue by tlbkwl1** [webcamoid/webcamoid#147]
When creating a new source with a GIF, the file will appear and loop but with graphical errors (appears as a kind of diagonal split) and in black and white.  This occurs no matter what GIF is used.
![image](https://user-images.githubusercontent.com/44442655/47445351-90782480-d76d-11e8-8154-159d42469bb8.png)
Webcamoid version is Win32 8.1.0
OS is Win10 1803.

**Comment by hipersayanX** [comment]
Can you upload the GIF file?

**Comment by tlbkwl1** [comment]
![fasthacks](https://user-images.githubusercontent.com/44442655/47512767-b666fd00-d831-11e8-91c0-bf6fbb01c2f0.gif)
Here is the GIF shown on the comment.
Below is another GIF I used which also showed the issue.
![looking](https://user-images.githubusercontent.com/44442655/47512850-e2827e00-d831-11e8-91fa-a6c884d94bd8.gif)

**Comment by hipersayanX** [comment]
Thanks! will check.

**Comment by hipersayanX** [comment]
Fixed in 8.6.0.
