### ISSUE TITLE
problem with the installation window.

### ISSUE THREAD

**Issue by steveroth64** [webcamoid/webcamoid#154]
Hi everyone. I installed Webcamoid on mint 18.xx. 
Started the program, it creates a problem. the initial configuration window is larger than the screen resolution. 
I can not modify and configure the program, let alone Mint. 
Can anyone tell me how to do? Thank you.

**Comment by hipersayanX** [comment]
Tried with LinuxMint 19.1 Cinnamon and can't reproduce the issue.
