### ISSUE TITLE
man page isn't installed by 8.5.0 any more

### ISSUE THREAD

**Issue by yurivict** [webcamoid/webcamoid#157]
Is this intended?

**Comment by hipersayanX** [comment]
Definitely not :confused:, the [install rule](https://github.com/webcamoid/webcamoid/blob/54e5038901c9c3c43b219cd9a3f3633d488e611d/StandAlone/StandAlone.pro#L130) may be ok.

**Comment by hipersayanX** [comment]
>What about the disappearance of these libraries:

Those submodules are not required anymore 082d1f8d1193b99fd9dcefee0c7825877f0f02b5.

>Could you fix it and make a release again?

No, unless critical, like  #156.

**Comment by hipersayanX** [comment]
Here is a [patch](https://gist.github.com/hipersayanX/a27bef15c3fc7b44c7d20d06913a80bf) for *nix like systems.

**Comment by hipersayanX** [comment]
Fixed in 8.6.0.
