### ISSUE TITLE
Virtual Camera Enabled on MacOS Eats Up Memory

### ISSUE THREAD

**Issue by graywolf336** [webcamoid/webcamoid#159]
### Summary

After manually launching webcamoid on MacOS 10.14.2 (see [here](https://github.com/webcamoid/webcamoid/issues/156#issuecomment-457572936)), I am able to input my rtsp camera and all is fine. Then I enable the Virtual Camera and all is good for a few minutes. However, after leaving webcamoid up and running for a while my system complains about running out of memory and webcamoid is taking up 32gb+ of RAM (no clue how it got this high when I only have 16gb).

### Current Behavior

Seems like the virutal camera has a memory leak because as soon as I enable it the memory usage jumps up 1gb every four seconds.

### Expected Behavior

Enabling virutal camera without consuming all of my RAM.

### Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue below:

1. Open webcamoid
2. Add a source
3. Create a new virtual camera
4. Enable the virtual camera
5. Watch the memory usage skyrocket

### Your Environment

* Webcamoid information: 8.5.0 64bits
* Operating System information: MacOS 10.14.2, 16gb ram, 3.4GHz Intel Core i5
* Any other useful information: Logs: https://pastebin.com/pzzZAZxh

**Comment by graywolf336** [comment]
Just changed the description as it happens with any source and not just an rtsp source. I can use it for about 30 seconds before everything crawls to a halt and it gets all distorted due to eating up the memory. I know it is the virtual camera because when I start webcamoid with activity monitor up (mac's task manager; I can see the memory usage) and enable the the virtual camera, the memory skyrockets. However, when I disable the virtual camera everything returns back to normal.

Happens with the daily build as of this comment (February 8th, 2019 at 2:48pm CST).

**Comment by hipersayanX** [comment]
Will check it's probably something related to the plugin. Also, which target program?

**Comment by graywolf336** [comment]
Not sure I know what you mean by "which target program?"... I have a webcam input that then goes to a new virtual camera and as soon as I enable the virtual camera the memory usage starts to sky rocket

**Comment by hipersayanX** [comment]
>Not sure I know what you mean by "which target program?"

The program that is receiving the frames, Chrome, Firefox for example, if there is not a target program then it could be more likely a problem in the IpcBridge, anyway will check.

**Comment by graywolf336** [comment]
Yeah, nothing was using it when it starts.

**Comment by hipersayanX** [comment]
This issue was fixed in the daily build.

**Comment by graywolf336** [comment]
I will test it tomorrow, thanks!

**Comment by graywolf336** [comment]
Verified it has been fixed in the daily builds. :) thanks!!!

**Comment by hipersayanX** [comment]
May be fixed in 8.6.0.
