### ISSUE TITLE
I'm a stingy and can't afford a better webcam

### ISSUE THREAD

**Issue by JamesTheHacker** [webcamoid/webcamoid#163]
![dumbhat](https://user-images.githubusercontent.com/1249885/53828478-8d334780-3f5c-11e9-84db-d9571274190a.png)
The UI is terrible and awful to use. My top line Logitec webcam is jerky too. Whatever default settings you use on boot are wrong because the camera is also very dark in a well lit room.

**Comment by hipersayanX** [comment]
JamesTheStingyHacker  :smile:
