### ISSUE TITLE
Is there a way to toggle visibility of the UI?

### ISSUE THREAD

**Issue by TSedlar** [webcamoid/webcamoid#168]
It'd be nice if there was a way to hide the UI bar if it is not already possible. Something as simple as Ctrl+H to toggle it.

It works surprisingly better than most of the other camera viewers I've used for directly viewing a capture card to play a game (no noticeable audio/input delay)

![image](https://user-images.githubusercontent.com/924309/54176058-71dba700-444a-11e9-94de-d19b171be931.png)

But would work much better if the UI was toggleable, simply for downscaling for a smaller window:

![image](https://user-images.githubusercontent.com/924309/54176079-9041a280-444a-11e9-8bb5-fc31a1cbd6bc.png)

**Comment by stefan-reich** [comment]
This would be extremely nice. I'm looking for a low-CPU-use webcam preview window for Linux and with this feature, Webcamoid would be perfect.

**Comment by crimzind** [comment]
It's something I'd also like.

**Comment by bryanmtdt** [comment]
That would be a great feature, this program catch video source better than others.

**Comment by stefan-reich** [comment]
Guys, I'm currently simply using mplayer for webcam preview:

`mplayer -title "WebCam" -tv device=/dev/video2:width=640:height=320 tv://`

Maybe that works for you too?

**Comment by hipersayanX** [comment]
Closing this and joining with #581.
