### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by hipersayanX** [webcamoid/webcamoid#169]
**Stage 1**: Make it work
Ready :heavy_check_mark:

![Webcamoid in Android](https://user-images.githubusercontent.com/1249885/54470132-9228a000-4781-11e9-9a3e-2fe784f9d648.png)

 :sunglasses:

**Comment by hipersayanX** [comment]
**Stage 2.0**: Camera working (both JNI and NDK) :heavy_check_mark: 

![android-camera](https://user-images.githubusercontent.com/1249885/56699657-ce2e1980-66cc-11e9-899f-c84ce1e11500.png)

**Comment by hipersayanX** [comment]
**Stage 2.1**: Screen capture working :heavy_check_mark:

![Screenshot_20190427_120914](https://user-images.githubusercontent.com/1249885/56851494-3f94e480-68e6-11e9-82d8-aeca292ecc18.png)

**Comment by hipersayanX** [comment]
**Stage 2.2**: Video and audio playback working :heavy_check_mark:

![Screenshot_20190718_172141](https://user-images.githubusercontent.com/1249885/61493701-9b718580-a98a-11e9-9c3f-66d081736e44.png)

**Comment by hipersayanX** [comment]
**Stage 2.3**: Video and audio recording working :heavy_check_mark:

![Screenshot_20190817_121437](https://user-images.githubusercontent.com/1249885/63214098-5f952180-c0ea-11e9-875c-3cf1bf62526f.png)

And now Webcamoid has all base features working in Android, obviously there would be some bugs out there that needs to be fixed, and Webcamoid is not usable at all yet, but over all the most important part of the port is done.
The next step is reworking the UI, and I'm planning a big full rewrite of it, I will keep you updated.

**Comment by hipersayanX** [comment]
[Android packages](https://bintray.com/webcamoid/webcamoid/webcamoid/daily#files/android) are ready for testing. The packages are signed with a debug sign so you will need to enable Android to install from unknown sources. You need Android 6.0 or higher.
This is **NOT** an official release, and as said before this is not ready for daily usage, expect a **LOT** of bugs.

**Comment by blackchineykh** [comment]
Hi, are these packages available for download? The link doesn't give us a way to download.

Also does this allow override of the actual physical camera on android? This is my use case and would love to see if I could use for this and also lend any support

**Comment by hipersayanX** [comment]
@blackchineykh yes in the **Files** section in the **android** folder. Bintray seems to be a bit bugged and it does not show it directly :confused:

**Comment by hipersayanX** [comment]
Ok, after 3 years of not updating, and having several problems with Android packages in CI environments, the Webcamoid port is up and running once again.

![Screenshot_20220114_192902](https://user-images.githubusercontent.com/1249885/149594854-dccab785-d243-41fc-ad6b-85d5c8bfb802.png)

The UI looks clunky, and there are some bugs to solve yet, but the most important part is that at least it's working and the port can keep going forward.

**Comment by hipersayanX** [comment]
I found that is crashing when making a screen capture, the port will need a bit more of work.

**Comment by hipersayanX** [comment]
Webcamoid 9.2.0 is fully working in Android, the next step is uploading to the PlayStore.
