### ISSUE TITLE
man page is installed into a wrong location in the version 8.6.0

### ISSUE THREAD

**Issue by yurivict** [webcamoid/webcamoid#170]
It is installed into ```man/webcamoid.1.gz```, while the correct location is ```man/man1/webcamoid.1.gz```.

**Comment by hipersayanX** [comment]
Fixed in [PR165](https://github.com/webcamoid/webcamoid/pull/165). Will make a new release probably the next week.

**Comment by hipersayanX** [comment]
Fixed in 8.6.1.
