### ISSUE TITLE
Libraries are installed into the Qt location

### ISSUE THREAD

**Issue by yurivict** [webcamoid/webcamoid#171]
For example, version ```8.5.0``` installed ```/usr/local/lib/avkys/libCartoon.so```, but in ```8.6.0``` this file is now installed into ```/usr/local/lib/qt5/avkys/libCartoon.so```.

Directory ```/usr/local/lib/qt5``` contains Qt5 libraries, and can't be used by the third party packages.

**Comment by hipersayanX** [comment]
It follow ```qmake -query```, [QT_INSTALL_LIBS:/usr/local/lib/qt5](https://cirrus-ci.com/task/4744313371099136) (at the very beginning of the log). You can change the library install directory with LIBDIR=/usr/local/lib.

**Comment by yurivict** [comment]
This works, thanks!
