### ISSUE TITLE
Virtual Webcam didn't uninstall - Can't open program after reinstalling

### ISSUE THREAD

**Issue by Nshabdue** [webcamoid/webcamoid#179]
I installed 2 virtual cameras with the same name accidentally. While I got an error doing this within webcamoid, it did however make 2 identical webcams visible when I go somewhere like camtests.com. I uninstalled the application, but the virtual cameras remain. They are not in device manager (this is a windows 32-bit install), so I have no clue how to manually remove them. 

I tried to reinstall the application, but it won't open at all. I've uninstalled an reinstalled 2x. I suspect my mistake of reusing the same name on a 2nd camera is causing an issue somehow. 

Is there a way to manually remove the virtual webcam?

**Comment by Nshabdue** [comment]
Disregard. I was able to fix this issue by using the portable version of daily build. I removed the devices there.

**Comment by hipersayanX** [comment]
As reported in #178, the uninstaller does not uninstall the driver yet, but it will do in future releases. Also there is no problem using the same name for the cameras since each camera is assigned with a different Device ID.

**Comment by Nshabdue** [comment]
Gotcha. I searched and couldn't find a similar situation. Thanks for a great product. I'm highly looking forward to v10 with picture in picture!

**Comment by GetzMikalsen** [comment]
Experienced the same issue on the latest build for Mac.
Using the portable version and disabling the devices worked fine.

**Comment by lucario** [comment]
How do you remove it manually, neither portable or installed version opens at all.

**Comment by h3llb3nt** [comment]
same problem as OP but portable app won't run at all. tried re-installing new regular app but it also will not run and crashes on start. have a "test" camera that i cannot get rid of in other video processing apps like OBS.

**Comment by smileymalaise** [comment]
I've deleted all files and folders relating to webcamoid and virtualcamera, i've deleted all registry keys related to those as well yet the virtual camera still shows up in discord and other apps. This app is malware.

**Comment by hipersayanX** [comment]
@h3llb3nt Try with [this](https://github.com/webcamoid/webcamoid/issues/178#issuecomment-614395023).

@smileymalaise :clown_face: 

https://en.wikipedia.org/wiki/Malware
https://www.avast.com/c-malware
https://www.csoonline.com/article/2615925/security-your-quick-guide-to-malware-types.html

**Comment by Leemusa** [comment]
This has nothing to do with Malware.

The issue / solution outlined by   j256   in https://github.com/webcamoid/webcamoid/issues/144 explains the entire situation. j256 offers a terminal solution, but the user can just visit the directories he identifies and delete the files he notes and all is good.

Who ever closed bug https://github.com/webcamoid/webcamoid/issues/144 screwed up big time. Why close a bug before it is no longer a bug?

**Comment by hipersayanX** [comment]
@Leemusa

>Who ever closed bug #144 screwed up big time. Why close a bug before it is no longer a bug?

Because the user was asking how to uninstall Webcamoid in GNU/Linux, the user did not give any more interaction, question answered, issue closed.

**Comment by hipersayanX** [comment]
This problem was solved in 9.0.0, the virtual camera comes with its own installer.
