### ISSUE TITLE
Virtual webcam

### ISSUE THREAD

**Issue by Joe23232** [webcamoid/webcamoid#186]
Using Virtual webcam, am I able to play some video and services such as skype will be fed the video  instead?

**Comment by Joe23232** [comment]
> Yes, you can play a video and the virtual camera will send the frames to Skype or any other program.

Hi, how do I get Opera (a browser) to use the virtual camera instead of using the built in?

![image](https://user-images.githubusercontent.com/34926497/63841570-65321780-c9c6-11e9-9d6c-0d44f3a44d0a.png)

I tried to change the setting but this is the only setting, any ideas?

**Comment by Joe23232** [comment]
On this PC, for some reason it just doesn't allow me to use any camera,
even the intergrated camera, something is a bit fucked I am not too sure
why nothing works :/

**Comment by hipersayanX** [comment]
If the problem is with your system I can't give you any help with that :confused:

**Comment by malikAr** [comment]
Hi,

I have compiled webcamoid code on mac successfully , but not able to find out how to use akvirtualcamera.plugin properly.

I have copied it /Library/CoreMediaIO/Plug-Ins/DAL

Now @hipersayanX  will you please help me to find out my camera plugin in skype or zoom.

Any help is thankful.

**Comment by hipersayanX** [comment]
@malikAr don't install the plugin manually, just copying the file isn't enough, some other files must be created and some services must be activated. When testing Webcamoid you can pass the **--vcam** option with the path to the plugin to the CLI (you can add that option in Qt Creator), and Webcamoid will do everything for you. For example:

    webcamoid --vcam /path/to/AkVirtualCamera.plugin
