### ISSUE TITLE
Add 'Virtual camera' in macOS 10.14.6 fail? 

### ISSUE THREAD

**Issue by kenfa01** [webcamoid/webcamoid#187]
Can we use 'Virtual camera' in macOS 10.14.6? When I 'Add' Virtual camera, the application shows the message: "Error creating camera"!

![螢幕快照 2019-09-09 上午10 40 28](https://user-images.githubusercontent.com/55073101/64502271-acd66e80-d2f7-11e9-8d43-1b4abc1fa820.png)

**Comment by hipersayanX** [comment]
I checked the virtual webcam just a few days ago and it worked fine, any way I will add a more specific error message.

**Comment by hipersayanX** [comment]
Can you test the [daily build](https://bintray.com/webcamoid/webcamoid/webcamoid/daily#files/mac)?

**Comment by kenfa01** [comment]
Sorry, I can not run apps.
![Screen Shot 2019-09-12 at 9 29 55 AM](https://user-images.githubusercontent.com/55073101/64747215-ebab3500-d540-11e9-989a-5ebf1422058f.png)

**Comment by kenfa01** [comment]
We can set "Virtual camera" now, thank you. :)
