### ISSUE TITLE
Add default picture file format option

### ISSUE THREAD

**Issue by IvanAP1791** [webcamoid/webcamoid#188]
Goodnight.

I turn to you, in order to ask if the software can be configured in any way so that the images are automatically saved in * .jpg

Greetings.

**Comment by hipersayanX** [comment]
No, but it can be done.

**Comment by IvanAP1791** [comment]
and how could we do?

**Comment by hipersayanX** [comment]
Writing the code to do so.

**Comment by somewhereinusa** [comment]
Has this been done yet? Would also like to save to a default file of my choosing

**Comment by yllekz** [comment]
Hello, this app should really be saving webcam captures as jpg and not png. Where is the option to change this?

**Comment by hipersayanX** [comment]
@yllekz _Preferences>Image Capture>File Format_ in the daily build, 8.8 has not such option. I will keep PNG as default for quality and compatibility reasons.

**Comment by hipersayanX** [comment]
Feature added in 9.0.0, closing.
