### ISSUE TITLE
Memory usage continues to grow

### ISSUE THREAD

**Issue by kenfa01** [webcamoid/webcamoid#196]
In macOS. When the applications connect to the Virtual Camera of the webcamoid, the memory usage of the webcamoid will continue to grow. In the end, it will cause the entire system to run very slowly!

Is there a way to limit the memory cap used by the webcamoid?
Thank you.

Before:
![Screen Shot 2019-10-08 at 1 32 06 PM](https://user-images.githubusercontent.com/55073101/66370516-2767dc00-e9d3-11e9-9147-e3b7829ebf79.png)

When an application connected:
![Screen Shot 2019-10-08 at 1 34 32 PM](https://user-images.githubusercontent.com/55073101/66370542-3ea6c980-e9d3-11e9-8890-0680e61ab017.png)

**Comment by hipersayanX** [comment]
This was fixed in the [daily build](https://bintray.com/webcamoid/webcamoid/webcamoid/daily#files/mac), install it or copy the portable version to the /Applications folder, remove all virtual cameras, restart Webcamoid and create the virtual camera again.

**Comment by kenfa01** [comment]
There is no USB camera now, just test the screenshot.

I have downloaded the latest version from github.
But connecting to "virtual camera" from other programs will have no image output! (The old version has image output)
Thank you.

**Comment by hipersayanX** [comment]
Try [resetting the configs](https://github.com/webcamoid/webcamoid/wiki/Reset-configs-and-starting-fresh#mac).

**Comment by hipersayanX** [comment]
Fixed in latest release. Remember to remove all virtual cameras and create a new one.
