### ISSUE TITLE
Mirror/flip capability needed

### ISSUE THREAD

**Issue by adamf663** [webcamoid/webcamoid#202]
When working with a usb microscope, it is a major hasle dealing with an image that is flipped and/or mirrored.  When trying to position an object into view, it is a pain when moving the object left causes the image to move right or when moving the object up causes the image to move down.
I couldn't find any plugin or settings page that offered such functionality.

The gnu guvcview application has such functionality.

**Comment by WolfgangFahl** [comment]
Good that it's not low priority any more ...

**Comment by hipersayanX** [comment]
@WolfgangFahl I had removed all Priority tags because they were subjective.

**Comment by davipatti** [comment]
Mirror / flip and rotation operations can be achieved by the Matrix Transform effect.

For instance, enter this matrix for a y-flip:

~~~
-1   0   0
 0  -1   0
~~~

**Comment by hipersayanX** [comment]
@davipatti maths magic :wink: 

https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:matrices-as-transformations/v/transforming-position-vector
https://en.wikipedia.org/wiki/Transformation_matrix

**Comment by hipersayanX** [comment]
Feature added in 9.0.0, closing.

**Comment by dchmelik** [comment]
> Mirror / flip and rotation operations can be achieved by the Matrix Transform effect.
> 
> For instance, enter this matrix for a y-flip:
> 
> ```
> -1   0   0
>  0  -1   0
> ```
```
-1, 0, 0
 0, 1, 0
```
