### ISSUE TITLE
Hide Webcamoid bottom menu bar?

### ISSUE THREAD

**Issue by zzzinha** [webcamoid/webcamoid#203]
Hello, I am a basic user (not programmer) of Webcamoid. I am wondering if anyone knows a trick to hide the bottom menu bar ... or a way to go full screen that hides the menu bar.

Many thanks,
Teresa

**Comment by hipersayanX** [comment]
Isn't possible right now, but no problem I can add that feature.

**Comment by zzzinha** [comment]
Thank you so much, HipersayanX! I look forward!

**Comment by wbraswell** [comment]
Any progress on this issue?  It is an important feature request.

**Comment by bryanmtdt** [comment]
I need this feature too

**Comment by chiyi4488** [comment]
me too.

**Comment by nolfr** [comment]
Thanks for the reference to #203, do you have a schedule of when to add the feature?

**Comment by hipersayanX** [comment]
@nolfr Nope, I've other priorities right now, but PRs are very welcome if someone want to work on this.

**Comment by sanette** [comment]
that would be great indeed, for instance when you broadcast your screen. Maybe a simple trick would be to set the transparency to zero?

**Comment by hipersayanX** [comment]
@sanette my idea is to add an option (maybe in the menu) that make a shrink effect and hide all the UI into a button in a corner, something similar to this:

![9d85046f8f4eb04](https://user-images.githubusercontent.com/1249885/114058805-2b93e480-986a-11eb-85f2-01732ade6530.gif)

then click the button and get the UI back with the opposite effect.
But right now I haven't time to implement it.

**Comment by sanette** [comment]
did you also consider completely hiding the controls and make them appear automatically as soon as the user hovers the window?
It seems to me that this is a common choice for video players, like youtube

**Comment by hipersayanX** [comment]
@sanette could be a mix of both approaches, shrinking the UI to a button, and making the button transparent when the mouse is outside the window.

**Comment by rajhlinux** [comment]
I would like this feature too.

**Comment by hipersayanX** [comment]
Closing this and joining with #581.
