### ISSUE TITLE
Rtsp camera showing 1sec delay

### ISSUE THREAD

**Issue by Bhavyashri** [webcamoid/webcamoid#209]
Hello
Im implementing the RTSP streaming by using SVDK board,the designing part is done,now i'm facing the delay in VLC player.whenever i'll play the video in vlc it will show the delay of 1sec. i do not know the reason why it is showing this one?can anyone help me to come of this problem?is that problem on camera side or vlc side?

Thank you..

**Comment by bitraid** [comment]
This is probably due to VLC caching. You can try adding the `--network-caching=0` parameter to VLC.

**Comment by hipersayanX** [comment]
I don't understand your question, how is this related to Webcamoid?
