### ISSUE TITLE
Opening infinite windows in Linux Mint Cinnamon 19.2

### ISSUE THREAD

**Issue by Martok7** [webcamoid/webcamoid#214]
I installed webcamoid-installer-8.7.1-x86_64.run on my PC which is running Linux Mint Cinnamon 19.2 64bit. When I execute the program, it opens an infinite amount of the application (image attached). I tried using the portable version also with the same results. 
I searched the support channel but did not see an issue related to mine.

**Comment by Martok7** [comment]
![Webcamoid](https://user-images.githubusercontent.com/10260295/72254512-41b4e580-35d2-11ea-874a-99b0274d31e0.png)

**Comment by hipersayanX** [comment]
Resize the window, move around, and you will soon understand what's going on :smile:

**Comment by hipersayanX** [comment]
The user is just making a desktop capture, not an issue, closing.
