### ISSUE TITLE
Error when creating a virtual camera

### ISSUE THREAD

**Issue by ryanhardt41** [webcamoid/webcamoid#217]
Hello guys,

I'm trying to run Webcamoid 8.7.1 on Zorin OS (a distro based on Ubuntu 18.04 LTS).
The application turns on and everything works fine, EXCEPT when I try to create a virtual camera.
The checkbox of "virtual camera" works **however** when I try to add a virtual camera it shows "Error creating camera:" even though I have entered the correct password.

This is an image of the issue I've been getting:
![Screenshot from 2020-02-05 09-24-52](https://user-images.githubusercontent.com/37240192/73802849-d7bae500-47f9-11ea-9168-3ad97ac9b2d5.png)
This is an image of my settings:
![Screenshot from 2020-02-05 09-28-50](https://user-images.githubusercontent.com/37240192/73802878-f1f4c300-47f9-11ea-841f-f12528e5dc3e.png)

**Comment by hipersayanX** [comment]
I think this could be related to [this](https://github.com/webcamoid/akvcam/issues/4).

**Comment by lcarva** [comment]
I'm having the same issue on Fedora 30. I see the same error as initially reported when running both the AppImage and portable linux binary.

**Comment by tuxflo** [comment]
I'm having the same issue on manjaro. Any ideas what to do? I also tried v2loopback but the resolution of the fake webcam is way too bad for screen sharing.

**Comment by JosefLitos** [comment]
I am using arch, I managed to start the v4l2loopback using insmod and the extra/v4l....ko.xz module, but I can't use that camera anyway and can't save the virtual camera in webcamoid neither.

**Comment by Kotarou0** [comment]
Same with Arch

**Comment by JosefLitos** [comment]
I have solved this some time ago, you have to have a graphical polkit interface agent running in background (such as polkit-gnome).

**Comment by hipersayanX** [comment]
Error messages have been improved in Webcamoid 9.0.0, closing.
