### ISSUE TITLE
Framerate selection only show default framerate on windows. 

### ISSUE THREAD

**Issue by circuitvalley** [webcamoid/webcamoid#221]
I have Tested with verion 8.5.0 and 8.7.1 with Logitech C920 and two other USB  UVC cameras. Only the default frame rate is available the FPS dropdown menu. 
Default windows camera app shows different frame rates but only 30 and 60 FPS.
FFMPEG with dshow shows complete list of supported frame rate. 

I believe on configure source page on right side FPS dropdown menu should show all supported frame rates. 
Issue seems to be with Windows 10 only. I have tested linux there frame rate selection is okey. 

Regards

# README

Some considerations before doing anything:

* Search the [issues list](https://github.com/webcamoid/webcamoid/issues) for similar topics before opening a new one.
* If you know how to fix the problem, consider doing a [pull request](https://github.com/webcamoid/webcamoid/pulls) instead of opening a new issue.
* Only report problems in [latest](https://github.com/webcamoid/webcamoid/releases) and [development](https://github.com/webcamoid/webcamoid/) version. Reporting issues related to older versions will be rejected.
* Use [gist](https://gist.github.com/) to post logs longer than 1024 characters.
* Webcamoid as project, is not affiliated or endorsed to any distribution, report packaging problems in their respective issue tracker.
* Respect the templates, we need as much information as possible.
* Don't open an issue and disappear, we need you at least the first week to clear up missing information.
* Missing information makes useless and unsolvable an issue report.
* You are our debbuger, eyes and hands, if an issue is not reproducible then you will be the only person able to solve it.
* Take a seat and wait for your turn, as many others that has their issues open, or much better try fixing it your self and collaborate with the solution :smile:

Choose one of the templates bellow that fit better your issue.

# Reporting a problem?

## Summary

Write here a brief description of the problem.

## Current Behavior

Describe the problem the best as you can, don't omit information.

## Expected Behavior

How it should have work?

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue bellow:

1.  Open this
2.  Click that
3.  Drag those
4.  ...

## Suggestions and tips

How would you solve the problem?

## Your Environment

* Webcamoid information: (version) (architecture)
* Operating System information: (name) (numeric version and codename if applied) (architecture)
* Any other useful information: (logs, gdb backtrace, valgrind logs, screenshots, hardware, etc.)

# Want a new feature?

Describe your idea the best as you can, include sketches, mockups and diagrams if required.  
Be patient, take in mind that there may be other priorities. Your idea will be accepted if fit in project goals.

# Questinons and other matters?

Go ahead!

**Comment by hipersayanX** [comment]
Same as explained [here](https://github.com/webcamoid/webcamoid/issues/219#issuecomment-585273426), Webcamoid only works with what is offered by DirectShow, if DirectShow say that only 30 FPS is available then Webcamoid will only show that frame rate, I can't do nothing about that.
