### ISSUE TITLE
MacOS binary version is not notarized, cannot run on MacOS without paying for Apple Developer Credentials

### ISSUE THREAD

**Issue by dg1sek** [webcamoid/webcamoid#223]
When running the binary release on MacOS Catalina 10.15.3 I get an error message saying the developer cannot be verified. 

![image](https://user-images.githubusercontent.com/2736464/75817994-6ccce180-5d98-11ea-875e-6a4a8fd4fae9.png)

Unfortunately on my system with recent Catalina, it's not possible to workaround this message in Preferences-Security as it was the case in previous MacOS versions.

I also cannot notarize it manually over command line, as I don't have a developer account.

Would it be possible for you to notarize the MacOS binary?

**Comment by hipersayanX** [comment]
Did you tried [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac)?

>Would it be possible for you to notarize the MacOS binary?

Impossible, I have no way to pay for signing.

**Comment by core-code** [comment]
the bug report is misleading, you can easily launch this and any other non-notarized app even on Catalina. no developer membership is needed, i am not sure where this myth is coming from.

**Comment by core-code** [comment]
just use right-click=>open as has always been necessary. or use the "open anyway" button in the system preferences

<img width="297" alt="Screenshot 2020-03-05 at 23 59 20" src="https://user-images.githubusercontent.com/1261954/76033807-76437e80-5f3d-11ea-9bba-6de50e0b5292.png">
<img width="780" alt="Screenshot 2020-03-05 at 23 58 51" src="https://user-images.githubusercontent.com/1261954/76033814-79d70580-5f3d-11ea-8273-c80725198552.png">

**Comment by ferdi2005** [comment]
Notarizing your software is **FREE**, please do it, you won't need to pay anything
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by hipersayanX** [comment]
@ferdi2005 will check, thanks!
