### ISSUE TITLE
'webcamoid-portable-8.7.1-x86_64.dmg' has no proper version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [webcamoid/webcamoid#224]
as can be seen on the two screenshots, 'webcamoid-portable-8.7.1-x86_64' is missing proper version numbers on macOS:

<img width="252" alt="Screenshot 2020-03-06 at 00 02 03" src="https://user-images.githubusercontent.com/1261954/76034005-f538b700-5f3d-11ea-93b7-841c705896ad.png">
<img width="602" alt="Screenshot 2020-03-06 at 00 02 21" src="https://user-images.githubusercontent.com/1261954/76034006-f669e400-5f3d-11ea-971f-fac6daf2b58b.png">

more specifically both the CFBundleShortVersionString and CFBundleVersion entries in your Info.plist file are missing. those should probably be set to "8.7.1". all macOS apps are expected to have proper version number information.

furthermore, the Info.plist file contains the CFBundleGetInfoString entry which has been deprecated for more than 10 years and should be removed and would prevent the display of proper version number information even if it was present.

**Comment by hipersayanX** [comment]
Will check, thanks!

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.

**Comment by core-code** [comment]
thanks! i can confirm its fixed
