### ISSUE TITLE
'webcamoid-8.7.1.dmg' is confusing

### ISSUE THREAD

**Issue by core-code** [webcamoid/webcamoid#225]
i was going to write a 3 page bug report about your ''webcamoid-8.7.1.dmg' download, before realising that this is actually an 'Installer'

if this is an installer it should probably have some indication that it is an installer, e.g. "Installer" in its name or at least an installer icon instead of your app-icon.

i think any normal user is just going to drag this to his app folder assuming it is the app and then have a bad surprise when launching it...

in any case, why an installer anyway? any person who has used macOS for more than 5 minutes absolutely hats installers anyway and will prefer the real app download

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.

**Comment by core-code** [comment]
thanks!
