### ISSUE TITLE
Unable to run webcamoid: Unknown option 'q'. 

### ISSUE THREAD

**Issue by gordonel** [webcamoid/webcamoid#226]
## Summary

When running webcamoid from QT Creator, I get the following in the console

## Current Behavior

```bash
18:19:49: Starting /Users/gordonel/webcamoid/StandAlone/release/Qt5.14.1/clangpp/x86_64/bin/webcamoid --vcam /Users/gordonel/webcamoid/libAvKys/Plugins/VirtualCamera/src/cmio/VirtualCamera -r -p /Users/gordonel/webcamoid/libAvKys/Plugins -q /Users/gordonel/webcamoid/libAvKys...
Webcamoid: Unknown option 'q'.
18:19:49: /Users/gordonel/webcamoid/StandAlone/release/Qt5.14.1/clangpp/x86_64/bin/webcamoid exited with code 1
```

## Expected Behavior

No "Webcamoid: Unknown option 'q'." error

## Steps to Reproduce

1. Clone the repo afresh
2. Install the deps afresh
3. In short, follow all the instructions in the wiki for macOS
4. Attempt running from qt-creator

## Your Environment

* Webcamoid information: master
* Operating System information: macOS Catalina 10.15.3

**Comment by hipersayanX** [comment]
I have not updated the wiki, the **q** option was removed in master, isn't necessary anymore.

**Comment by gordonel** [comment]
That fixes it, but still, the app is unusable. See my other issue. Here's what I have in the console:
```
18:57:19: Starting /Users/gordonel/webcamoid/StandAlone/release/Qt5.14.1/clangpp/x86_64/bin/webcamoid --vcam /Users/gordonel/webcamoid/libAvKys/Plugins/VirtualCamera/src/cmio/VirtualCamera -r -p /Users/gordonel/webcamoid/libAvKys/Plugins...
qrc:/Webcamoid/share/qml/main.qml:523:13: QML ToolBar: Binding loop detected for property "implicitHeight"
qrc:/Webcamoid/share/qml/main.qml:92: ReferenceError: togglePlay is not defined
qrc:/Webcamoid/share/qml/MediaBar.qml:63:5: QML Label: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
18:57:55: /Users/gordonel/webcamoid/StandAlone/release/Qt5.14.1/clangpp/x86_64/bin/webcamoid exited with code 0
```

**Comment by hipersayanX** [comment]
I'm in the middle of [UI redesign](https://github.com/webcamoid/webcamoid/issues/216) right now, those messages will be common until I finish with it.

**Comment by beppe9000** [comment]
webcamoid-portable-daily-win64 has this error

**Comment by hipersayanX** [comment]
@beppe9000 remove the _-q "%~dp0/path"_ part of the command. I will update the script later.
