### ISSUE TITLE
WINDOWS - face recognition does not render image overlays

### ISSUE THREAD

**Issue by beppe9000** [webcamoid/webcamoid#229]
I confirmed the default stickers bundled with webcamoid work, but after selecting an image file from filesystem it is not rendered.
If I switch again to a bundled one it renders correctly.

**Comment by phord** [comment]
I see the same problem on Linux.

**Comment by phord** [comment]
Nevermind.  The face detection plugin doesn't show an image unless you choose the image option on the dropdown.  Works fine on linux.   Sorry about the noise.

**Comment by beppe9000** [comment]
> Nevermind. The face detection plugin doesn't show an image unless you choose the image option on the dropdown. Works fine on linux. Sorry about the noise.

Do ou need to choose a default image from the dropdown and then select one from file system ?

**Comment by dikdust** [comment]
sorry but in ubuntu 18.04 doesn't work ... also if the picture is selected ...

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
