### ISSUE TITLE
Windows: Keeps crashing immediately after start

### ISSUE THREAD

**Issue by jekay001** [webcamoid/webcamoid#231]
First it worked for about an hour. Now it keeps crashing immediately after start. Already reinstalled several times, tried portable versions, 32 and 64bit. Nothing works anymore.
Win10.

**Comment by jekay001** [comment]
I used the new virtual cam.

**Comment by beppe9000** [comment]
I had limited success by deleting the app folder and extract again the portable release.
Is there a place where things are logged? The 'app crashed' dialogue of windows is pretty useless, although it does offer the option of debugging it... I shall test it but I think it needs to be an explicit debug build with pdb files for visual studio to work well with it.

**Comment by hipersayanX** [comment]
@beppe9000 error logging is one of the features I want to add.

**Comment by beppe9000** [comment]
no way to get you a stack trace from the crash ?

**Comment by beppe9000** [comment]
I found a bunch of crash dumps in windows app data. IDK if they are useful to diagnose the problems
[CrashDumps.zip](https://github.com/webcamoid/webcamoid/files/4365308/CrashDumps.zip)

**Comment by hipersayanX** [comment]
@beppe9000 will check, thanks!

**Comment by valbok** [comment]
Can somebody rebuild directshow plugin in QtMultimedia without 
hr = pVideoControl->GetFrameRateList(pPin, iIndex, size, &listSize, &frameRates);
and check if it works?
can it be an issue with negotiating the frame rates?

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
