### ISSUE TITLE
Memory leak back on 8.7.1?

### ISSUE THREAD

**Issue by perdja** [webcamoid/webcamoid#232]
Hello,

I saw that on a previous version there was a memory leak which was updated according to records (post #159 ). By behaviour it seems that this leak has returned in version 8.7.1 (mac) as I can confirm the described behaviour recorded for previous version. After some use I am forced to restart computer due to memory. Can this be confirmed?

**Comment by hipersayanX** [comment]
Do you remember which was the target program?

**Comment by perdja** [comment]
Hello, thanks for quick response! 
Well at the time I was channeling to Teams from OBS using the virtual cam capabilities, but please be aware that I experienced this also a few days ago without any particular destination, which also was indicated in post #159 . I operate with Mojave 10.4.6. I was really happy being able to use the webcamiod as virtual camera capability and really appreciate your work!

**Comment by esnho** [comment]
I'm experiencing something similar but related to hard drive space on MacOS Catalina, I've got a two screen setup, grabbing one of the desktop quickly fill my hard drive.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
