### ISSUE TITLE
Setting Screen 1 as source crashes application Windows

### ISSUE THREAD

**Issue by DavMol2k** [webcamoid/webcamoid#239]
## Summary

When running as virtual camera selecting screen 1 as cam source causes the application to crash

## Expected Behavior

To display screen 1 as the webcam output

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue bellow:

1.  Open webcamoid
2.  Select Virtual camera
3.  Click Configure source
4. select Screen 1 (Second monitor)
4.  click Play

## Your Environment

O/S Windows 10
Webcamoid 8.7.1 32 and 64 bit application tested

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
