### ISSUE TITLE
Hang while adding a virtual camera

### ISSUE THREAD

**Issue by rvanlaar** [webcamoid/webcamoid#241]
#Reporting a problem?

## Summary

Can't add a virtual camera output

## Current Behavior

Setting the checkmark on 'virtual camera', click add, pick a name and press 'ok'.
A password form popups. Afterwards it hangs, doesn't react to click. Have to resort
to force-quit.

Quitting and restarting webcamoid makes a virtualcamera with the given name pop up.

## Expected Behavior

I expect a virtual camera to be added.
How it should have work?

## Suggestions and tips

How would you solve the problem?

- Would update the documentation explaining how to add a virtual camera.
- explain what adding one means and the differences between 'dummy' and one you add yourself.
- Futhermore, VLC did find a virtual

## Your Environment

* Webcamoid information:  8.7.1 x64
* Operating System information: Linux 19.10 eoan
* Any other useful information: (logs, gdb backtrace, valgrind logs, screenshots, hardware, etc.)
strace shows:
```
openat(AT_FDCWD, "/dev/video7", O_RDWR|O_NONBLOCK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=500000000}, 0x7fffa94af7b0) = 0
openat(AT_FDCWD, "/dev/video7", O_RDWR|O_NONBLOCK) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=500000000}, 0x7fffa94af7b0) = 0
openat(AT_FDCWD, "/dev/video7", O_RDWR|O_NONBLOCK) = -1 ENOENT (No such file or directory)
```

dmesg:
```
[24003.164918] uvcvideo: Failed to query (SET_CUR) UVC control 10 on unit 3: -32 (exp. 2).
[24003.167515] uvcvideo: Failed to query (SET_CUR) UVC control 4 on unit 1: -32 (exp. 4).
[24003.167933] uvcvideo: Failed to query (SET_CUR) UVC control 6 on unit 1: -32 (exp. 2).
```

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
