### ISSUE TITLE
webcamoid-portable-8.7.1-win64 version starts 'not responding' and never recovers

### ISSUE THREAD

**Issue by paulvirtuel** [webcamoid/webcamoid#242]
# README

# Reporting a problem?
yes

## Summary
webcamoid-portable-8.7.1-win64 version starts 'not responding' and never recovers

## Current Behavior
I have waited 30 minutes and it still shows 'not responding'

## Expected Behavior
When using VLC media player, I can select the same web cam and it works.

## Steps to Reproduce
Nothing special, after installing it, start it

## Your Environment
webcamoid-portable-8.7.1-win64 version
Windows 8.1

# Want a new feature?

# Questions and other matters?

**Comment by gijbelsy** [comment]
Same issue here, only I haven't configured the webcam yet, so no virtual cam's are available

**Comment by Aquind** [comment]
I just installed Webcamoid and I also get the (Not Responding) issue upon launch.  I have tried rebooting, reinstalling, uninstalling rebooting then installing again.  I have also left it running for hours with still no response.  There are no driver issues and multiple other programs use the webcam fine.

Is there any other info I can provide to help troubleshoot this?  Any ideas?

![2020-04-15_09-09-23](https://user-images.githubusercontent.com/1574081/79340804-de03c680-7ef8-11ea-9c2e-070227e418ea.png)

**Comment by hipersayanX** [comment]
@Aquind Can you give me the video information from **TANDBERG Video**, for example from VLC or similar? is that a streamed video or a local file?

![current-media-information](https://user-images.githubusercontent.com/1249885/79408300-63c35880-7f71-11ea-936e-34e5fe6289b1.png)

Also try [Reset configs and starting fresh](https://github.com/webcamoid/webcamoid/wiki/Reset-configs-and-starting-fresh)

**Comment by paulvirtuel** [comment]
1- The application does this even without any webcam connected.

2- I connected a web cam and got this from VLC:
Stream 0
   Type: Video
   Codec: Packed YUV 4:2:2, Y:U:Y:V (YUY2)
   Resolution: 1280x720
   Display resolution: 1280x720
   Frame rate: 10
Stream 1
   Type: Audio
   Codec: PCM S16 LE (araw)
   Channels: Stereo
   Sample rate: 44100 Hz
   Bits per sample: 16

**Comment by paulvirtuel** [comment]
I am trying to understand why this issue is closed pointing to #345 since #345 is also pointing to this issue and closed as duplicate.

**Comment by hipersayanX** [comment]
@paulvirtuel This issue is actually open, check bellow the title, #345 is pointing to this issue as reference ([check](https://guides.github.com/features/issues/) this and [this](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls)) and closed because the similarities with this issue. Please, take some time to learn how github works.

>I should create a new issue with the same information since the issue is still present?

Don't try to do that, that's basically spamming and I will ban you and anyone doing that, if there was a problem with current version that you believe that was not actually solved just reopen it.

**Comment by hipersayanX** [comment]
And I forgot to mention, I've updated the daily build for Windows these days, check if you still have this problem.

**Comment by paulvirtuel** [comment]
Thanks for your response.

I just tried the daily build and the 'not responding' is not present at startup but appears as soon as I select the web cam source 'USB 2.0 Camera'.

From VLC it works.  Here is the codec info shown by VLC:
Stream 0
Type: Video
Codec: Packed YUV 4:2:2, Y:U:Y:V (YUY2)
Resolution: 1280x960
Display resolution: 1280x960
Frame rate: 30.000030

Stream 1
Type: Audio
Codec: PCM S16 LE (araw)
Channels: Stereo
Sample rate: 44100 Hz
Bits per sample: 16

**Comment by hipersayanX** [comment]
@paulvirtuel I can't reach to any conclusion with that information, Webcamoid handles fine that format in other webcams, so I think the problem comes from somewhere else. Could it be that you have installed the virtual camera? Did you tried [resetting the configurations](https://github.com/webcamoid/webcamoid/wiki/Reset-configs-and-starting-fresh#windows)?

**Comment by Aquind** [comment]
sorry for the delay.  Actually I am getting this from the codec information in VLC (The video works fine in VLC) 
![image](https://user-images.githubusercontent.com/1574081/94353317-de72c280-003d-11eb-888c-ca5e4f606d79.png)

**Comment by Aquind** [comment]
BTW, the daily build also freezes but instead of freezing on a white window it freezes with the following:
![image](https://user-images.githubusercontent.com/1574081/94353610-116a8580-0041-11eb-9c71-8b28b815d408.png)

**Comment by hipersayanX** [comment]
@Aquind again, I can't reach to any conclusion with this information https://github.com/webcamoid/webcamoid/issues/242#issuecomment-699569116, Webcamoid works fine with those formats. It should be something else.

>BTW, the daily build also freezes but instead of freezing on a white window it freezes with the following:

If you you go to _Video/Sources_, what formats does it show? Do you have the virtual camera enabled in _Video/Outputs_?

**Comment by cjbarth** [comment]
I am getting this problem to with the latest daily builds of Win32 and Win64 both the portable and installed versions. Webcamoid starts, sometimes turns on the camera and shows a single frame, and then reports (Not Responding) in the title bar and never does anything. I eventually close it and it reports the problem to Microsoft. What debugging or logging steps can I take to help get to the bottom of this?

**Comment by hipersayanX** [comment]
@cjbarth beside using gdb//lldb, there are not much options for debugging right now. Improving error logging is one of my pending tasks.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
