### ISSUE TITLE
I can't uninstall/erase folder AkVirtualCamera.plugin

### ISSUE THREAD

**Issue by Jotxemari** [webcamoid/webcamoid#246]
I can't uninstall/erase folder AkVirtualCamera.plugin. Windows 10.
Thanks.

**Comment by hipersayanX** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_10-files/need-permission-to-delete-folder-after-windows-10/bc9c59ce-d9c1-4ebf-9662-e0c8d4fb0007
