### ISSUE TITLE
downloaded webcamoid install file for win 10 does not work

### ISSUE THREAD

**Issue by thamcore** [webcamoid/webcamoid#248]
webcamoid-8.7.1-win64.exe
webcamoid-8.7.1-win32.exe
the X to close that pop up screen does not work either. It's dead.
![image](https://user-images.githubusercontent.com/62708494/77660452-9e8d2e80-6f79-11ea-9f6f-c8cc7bee9b64.png)

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
