### ISSUE TITLE
Audio distorted when making a movie

### ISSUE THREAD

**Issue by littlefico** [webcamoid/webcamoid#251]
## Summary

No matter which mic i use no matter which codec i use as output for audio and video, the result is always the same. audio is so distorted, you cannot understand anything

## Current Behavior

When watching videos, made with the program they have distorted audio, not understandable

## Expected Behavior

i should have hear my voice

## Steps to Reproduce

1.) Configure Audio Settings to your mic
2.) Make a Video
3.) Watch it with VLC player

## Your Environment

* Webcamoid information: 8.7.1 x64
* Operating System information: win10 pro x64, intel hades canyon barebone
* Any other useful information: 2x mics tested (bluetooth headset sennheiser mx 150, and integrated mic of a webcam, dericam) --> i could test both mics positive and working properly

# Questinons and other matters?
programm crashes everytime when changing output audio to FLAC
Go ahead!

**Comment by littlefico** [comment]
could you reproduce that?

**Comment by littlefico** [comment]
i have an update.
i installed a jack microphone and it works with the same cam, when the audio output source is another microphone than the inbuild one in the webcam.

**Comment by littlefico** [comment]
anything new?

**Comment by hipersayanX** [comment]
@littlefico Nope, I'll will check this later, but if you have new information or patch to solve this bug, just drop it.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
