### ISSUE TITLE
Fails to play video to Virtual Camera if video size is too small

### ISSUE THREAD

**Issue by Dianolve** [webcamoid/webcamoid#252]
## Summary

When the video is too small, the application crashes. It then also crashes on launch if autoplay video is enabled.

## Current Behavior

The size that i have found it work is at least 640 pixels wide, however it is possible that something lower may work. Dimensions that did NOT work for me were 320x320px and 400x224px. However i found that resizing these videos to at least 640 pixels wide fixed the issue.

## Expected Behavior

The video should play.

## Steps to Reproduce

1.  Install Webcamoid
2.  Find a video that is 320x320 pixels wide
3.  Make sure an application is using your webcam
4.  Try playing it

## Suggestions and tips

Maybe enlarge the videos before they are played?

## Your Environment

* Webcamoid information: 8.7.1 32bit/64bit
* Operating System information: Windows 10 / Ubuntu(tried both virtual camera drivers)
* Any other useful information:

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
