### ISSUE TITLE
creating a virtual camera does not work on macOS

### ISSUE THREAD

**Issue by benz0989** [webcamoid/webcamoid#260]
hi everyone

i just installed the latest version of webcamoid on my macbook,and i am trying to create a virtual camera but it is not working.After i create one it does not show up in photo booth or any other program.
It also does not show up as a camera source in webcamoid itself.
i have not used webcamoid in a few months but it used to work fine.,and i was hoping someone could assist me with this.
sorry if this is a known issue but i could not find anything about it.

**Comment by hipersayanX** [comment]
https://github.com/webcamoid/webcamoid/issues/220#issuecomment-599091191
