### ISSUE TITLE
Deploy.py does not include Qt libraries on macOS

### ISSUE THREAD

**Issue by demiantres** [webcamoid/webcamoid#268]
Running `./ports/deploy/deploy.py` creates an app container containing all libraries (avksys plugins, ffmpeg, virtual camera driver) but it is lacking the Qt frameworks and libraries (the Qt Qml files are copied).

- macOS 10.4
- Qt 5.14
- webcamoid master branch and also 8.7.1 release source package

The commands are as follows:

1. ~/Qt/Qt.5.14.0/clang/bin/qmake
2. make -j8
3. python3 ./ports/deploy/deploy.py

Including the deploy step in Qt Creator creates the same package structure lacking the Qt libraries.

**Comment by demiantres** [comment]
I tried to fix this but for me it is not clear how the Qt framework and plugin copying to the app package works.

**Comment by hipersayanX** [comment]
Don't use the official Qt, use [homebrew](https://brew.sh) instead.

**Comment by demiantres** [comment]
Thanks! With homebrew it works.

**Comment by hipersayanX** [comment]
Package managers makes everything easier :smile:
