### ISSUE TITLE
Config gets lost when switching webcams

### ISSUE THREAD

**Issue by Dangerfreak** [webcamoid/webcamoid#272]
I'm using V8.7.1 (windows 64 bit) for live-streams (via virtual cam). As long I only have one webcam attached to my computer, the configuration  (fps, resolution, format) is saved. However, if you have two webcams attached, the config of webcam #1 gets lost when switching to webcam #2 (and vice versa).
What can I do to save all configs permanently?

**Comment by hipersayanX** [comment]
Feature added in 9.0.0, closing.
