### ISSUE TITLE
effect chaining / layering ?

### ISSUE THREAD

**Issue by beppe9000** [webcamoid/webcamoid#277]
is there any plan to allow that ?

**Comment by hipersayanX** [comment]
It's actually possible but very unintuitive, as it's implemented now, you must enable the advanced effect mode and then you can add as many effects as you want, but again is unusable as it's implemented.
The redesign is already planned, check [this](https://github.com/webcamoid/webcamoid/issues/216#issuecomment-589687742) (Video effect selection), the feature that you want wiil be implemented as the **Overlap** option (or some similar name).
I'll start working on that probably this week.

**Comment by beppe9000** [comment]
looks promising. indeed I was picturing it like the level panel of photoshop

**Comment by hipersayanX** [comment]
Do you mean something like this?

<img width="106" alt="layer-group" src="https://user-images.githubusercontent.com/1249885/79078224-29da2400-7cdd-11ea-99d7-92a84f4a40a2.png">

My idea is to start with something simple and then start adding the rest of the features later, based on what users needs.
Also, I'm very careful not adding features that consumes a lot of resources, for example, I wanted to use a Cheese like effect selection like this:

![cheese_efectos](https://user-images.githubusercontent.com/1249885/79078357-2f843980-7cde-11ea-837d-75f9403aa4e8.jpg)

but it does not looks like a good idea doing that in a phone.

**Comment by beppe9000** [comment]
yes, actually i meant much simpler than that. basically a listbox control with buttons or drag&drop for setting order

**Comment by hamoid** [comment]
Would it be possible to add user GLSL effects? It would be cool if that was possible without recompiling.

**Comment by hipersayanX** [comment]
@hamoid possible yes, but you must write a plugin that make use of them.

**Comment by hamoid** [comment]
Do you mean 1 plugin, maybe called "user effects" that provides a way to load effects? (either a textarea or a dropdown showing effects from a folder), and maybe with a way to build a GUI for those shaders? Using ISF might be a way to get a few thousand effects at once: https://editor.isf.video/shaders?q=&category=&sort=&page=0

**Comment by hipersayanX** [comment]
[This feature](https://github.com/webcamoid/webcamoid/issues/216#issuecomment-618757525) can be tested in the daily build. I was not able to allow the user to rearrange the effects by dragging them, the ScrollView seems to be eating the drag & drop events, must figure out how to fix that.

@hamoid Open a new issue so I can remember to do that later.

**Comment by hamoid** [comment]
@hipersayanX The new issue: https://github.com/webcamoid/webcamoid/issues/288

**Comment by hipersayanX** [comment]
Feature added in 9.0.0, closing.
