### ISSUE TITLE
Ubuntu 18.04 LTS black screen virtual camera

### ISSUE THREAD

**Issue by eigo228** [webcamoid/webcamoid#278]
hello, now im trying to setup virtual camera, i installed both akvcam and v412loopback drivers, but no one of this isnt translating my mp4 file to Zoom, i choosed a virtual camera in zoom, but it shows black screen. what to do?
im using kubuntu 18.04.04 LTS and latest webcamoid

**Comment by nanohard** [comment]
It's not a problem w/ virtual cam to Zoom, it's a problem w/ webcam to virtual cam; virtual cam is black even inside Webcmoid.

Arch Linux 5.6.15
Webcamoid 8.7.1
avkcam-dkms-git 1.0.4.r0.g5f94c37

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
