### ISSUE TITLE
frozen image

### ISSUE THREAD

**Issue by ghost** [webcamoid/webcamoid#279]
Effective as an application. I used it with webex in search of the customization of the background which is not at the top, in addition I found that the image freezes very frequently

**Comment by hipersayanX** [comment]
Can you give any context? Which operating system? What is exactly "frozen" means? what is frozen? the webcam? the virtual camera? a video? the desktop?

**Comment by samliddicott** [comment]
I find on Windows 10 with an Intel RealSense Camera SR300 Virtual Driver  that I get about 20 seconds of freezing and 30 seconds for working, continually. But with the Intel RealSense Camera SR300 RGB, it works find continuously.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
