### ISSUE TITLE
webcamoid 8.5.0 stops  (Raspbian Buster)

### ISSUE THREAD

**Issue by Max11223344** [webcamoid/webcamoid#282]
I have a simple webcam (Sunplus) connected via usb to my Raspbian buster.
The camera is recognized (/dev/video0). When i press start the video from the camera is displayed - but only for a few minutes. Then it stops. Pressing 'Stop' and then 'Start' again i can see the video again. 

Settings for Webcamoid are the defaults

The same camera works on Webcamoid under Windows without problems.
Is there something i can try to overcome this?

Thanks in advance
Max

**Comment by Max11223344** [comment]
i forgot: It is Raspberry 4b with 4 GB

**Comment by hipersayanX** [comment]
Only latest version is supported https://github.com/webcamoid/webcamoid/releases.
