### ISSUE TITLE
Editing the wiki is disabled?

### ISSUE THREAD

**Issue by beppe9000** [webcamoid/webcamoid#285]
I wanted to add proper windows commands to do a complete reset but there is no "edit" button...

**Comment by hipersayanX** [comment]
Yes it's restricted to members only, I sent you an invite.

**Comment by beppe9000** [comment]
Could you tell me where I can see it?

**Comment by beppe9000** [comment]
OK I got it, it was only shown in the organization page ¯\_(ツ)_/¯

**Comment by beppe9000** [comment]
checked it still does not allow wiki edit ¯\_(ツ)_/¯

**Comment by hipersayanX** [comment]
Now?

**Comment by beppe9000** [comment]
ok now i see it
