### ISSUE TITLE
Streaming a video from C# to AkvCam on windows

### ISSUE THREAD

**Issue by beppe9000** [webcamoid/webcamoid#286]
If Webcamoid is cpp, what headers and lib files should I use with [this tool](https://github.com/mono/CppSharp) to get dotnet binding? Thanks

**Comment by hipersayanX** [comment]
[API header](https://github.com/webcamoid/webcamoid/blob/master/libAvKys/Plugins/VirtualCamera/src/ipcbridge.h)
[API lib](https://github.com/webcamoid/webcamoid/tree/master/libAvKys/Plugins/VirtualCamera/src/dshow/VCamIPC)
[API example](https://github.com/webcamoid/webcamoid/blob/master/libAvKys/Plugins/VirtualCamera/src/virtualcameraelement.cpp#L64)

**Comment by beppe9000** [comment]
Thanks! I will post when I get it working or hit some roadblock.

**Comment by hipersayanX** [comment]
There are many users asking the same, a solution would be designing a communication protocol with the plugin so developers don't need to link against any library to talk to it, maybe using something similar to Linux device drivers in which you communicate with device files. Probably using [File Mapping](https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications#using-a-file-mapping-for-ipc) or something similar.

**Comment by correa** [comment]
Would webcamoid accept pull requests and setup a new repository to separate the virtual camera in it's own repository/library to accommodate those users?

**Comment by hipersayanX** [comment]
@correa I'm already into that.

https://github.com/webcamoid/akvirtualcamera

**Comment by hipersayanX** [comment]
Check latest updates for [akvirtualcamera](https://github.com/webcamoid/akvirtualcamera/issues/3), its almost working fine and no linking is required, so it can be used easily in any programming language.
