### ISSUE TITLE
Resize window Webcamoid

### ISSUE THREAD

**Issue by KovalevArtem** [webcamoid/webcamoid#293]
# Reporting a problem?

## Summary

Resizing the window is too jerky.

## Current Behavior

[Demonstration ](https://imgur.com/a/G8qxSuJ)of this problem.

## Your Environment

* Webcamoid information: (Development version - Daily Build )
* Operating System information: (Windows) (1909)

**Comment by hipersayanX** [comment]
This maybe fixed in the master.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
