### ISSUE TITLE
Camera and microphone destroyed

### ISSUE THREAD

**Issue by manos92** [webcamoid/webcamoid#294]
I unistalled Webcamoid as I did not need it anymore. Now, the camera and the microphone do not work when I am trying to make a video call...

**Comment by hipersayanX** [comment]
What do you mean with "destroyed"? What operating system?

**Comment by manos92** [comment]
Windows 10. Trying to make a video call from messenger this appears
[cid:843566be-72dd-48c7-a08c-dc69c30186ab]
Trying to give access then this appears


[cid:2e92996a-2ee2-4cbe-8c2a-b5bc509d6d75]


The default of my camera is not this name. This name should not even exist anymore.

Furthermore, no video call even if it is in Viber, or Skype cannot use my microphone so nobody listens to me.


________________________________
Από: hipersayanX <notifications@github.com>
Στάλθηκε: Παρασκευή, 1 Μαΐου 2020 1:52 πμ
Προς: webcamoid/webcamoid <webcamoid@noreply.github.com>
Κοιν.: manos92 <em.louloudis@hotmail.com>; Author <author@noreply.github.com>
Θέμα: Re: [webcamoid/webcamoid] Camera and microphone destroyed (#294)


What do you mean with "destroyed"? What operating system?

**Comment by hipersayanX** [comment]
The screenshots were not uploaded properly, can you upload again? use the ```Attach files by dragging & dropping, selecting or pasting them.``` option bellow in the comment.

>Furthermore, no video call even if it is in Viber, or Skype cannot use my microphone so nobody listens to me.

Check your microphone volume is up, beside that Webcamoid is just a capture program, it does not modify nothing related to the audio.

**Comment by manos92** [comment]
![image](https://user-images.githubusercontent.com/64617366/80833709-ce25fb00-8bf7-11ea-81b0-dbb5266fa222.png)

![image](https://user-images.githubusercontent.com/64617366/80833730-daaa5380-8bf7-11ea-9aea-5b3d47d1d24f.png)

This camera that appears named manolis in the Google Chrome is something that I had created using webcamoid. It does not exist anymore but cannot be changed. My microphone operates well, when it is not related with a live chat. The settings of my microphone and camera are ok in general as you can see.

![image](https://user-images.githubusercontent.com/64617366/80833864-2bba4780-8bf8-11ea-8574-46a3d0205a02.png)

![image](https://user-images.githubusercontent.com/64617366/80833964-64f2b780-8bf8-11ea-94e8-9b9f4866d663.png)

![image](https://user-images.githubusercontent.com/64617366/80834037-953a5600-8bf8-11ea-9570-b2c66a85ec9e.png)

**Comment by hipersayanX** [comment]
@manos92 get it, you created a virtual and when removing it did not get erased properly right? it has been discussed how to fix that [here](https://github.com/webcamoid/webcamoid/issues/178#issuecomment-606301900) and [here](https://github.com/webcamoid/webcamoid/issues/178#issuecomment-614857556). Also en the **Camera and microphone allowed** you can actually select either the virtual camera or your webcam.
With the audio part sorry but don't understand greek? russian? it seems to be disabled in Chrome, it could be that is disabled because your are not using it.

**Comment by manos92** [comment]
@hipersayanX  I ran the .bat file. I also have deleted everything that appears to the search of the disk C: that is related with the words akvcam, akvirtualcamera and webcamoid. I have tried to reinstall my camera. I have tried everything. Nothing works. I have tried to open a video call in Messenger from every browser and every browser shows that there is a camera named manolis and uses it as my default camera and cannot be changed.

**Comment by manos92** [comment]
![image](https://user-images.githubusercontent.com/64617366/80862530-8b5b3600-8c7e-11ea-81da-e583af8bf6c0.png)
@hipersayanX  Maybe everything here that is related with the number 20856 has to do with the akvirtual camera? and should be deleted?

**Comment by manos92** [comment]
@hipersayanX  What is your opinion?

**Comment by hipersayanX** [comment]
Open **regedit** and give me screenshots of this paths:

```
Computer\HKEY_CLASSES_ROOT\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance
Computer\HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance
```

**Don't do anything else.**

**Comment by manos92** [comment]
![image](https://user-images.githubusercontent.com/64617366/81112595-8e2c8400-8f27-11ea-8b52-5d31ffe84a95.png)

![image](https://user-images.githubusercontent.com/64617366/81112796-e19ed200-8f27-11ea-8e94-e5bee55a749e.png)

**Comment by manos92** [comment]
Thank you in advance @hipersayanX  for your time !

**Comment by hipersayanX** [comment]
The **{D550C587-...}** is the virtual camera and you can delete that key, **don't delete any other key**.
That will remove the virtual camera.
For the missing webcam, the webcam is detected by the but does not appears in the **Instances**, try reinstalling the driver.

https://www.youtube.com/watch?v=RhaveEmhsbA

Is more or less the same for any webcam.

**Comment by manos92** [comment]
It is ok now. Thank you very much for the detailed instructions!
________________________________

**Comment by hipersayanX** [comment]
Glad it worked :smile: 
Will try to fix it before the next release.
