### ISSUE TITLE
Distorted Video Feed

### ISSUE THREAD

**Issue by FunkFreaksAmsterdam** [webcamoid/webcamoid#298]
Hi, 

So I make it to connect my Go Pro 7 black as a virtual camera to webcamoid, on the webcamoid preview feed looks good, but on the Zoom/Whereby/etc it comes out like this.

![GoPro image](https://user-images.githubusercontent.com/64772846/80945812-f88cd980-8dec-11ea-8f96-810fffe681af.png)

Any ideas?

I'm on Mac OSX Mojave btw.

Thank you!

**Comment by hipersayanX** [comment]
What is the format and resolution of the stream?

**Comment by FunkFreaksAmsterdam** [comment]
I’m streaming via wifi and fffmpg, is it maybe a PAL/NTSC thing? How do I see the resolution of the stream?

**Comment by hipersayanX** [comment]
>I’m streaming via wifi and fffmpg, is it maybe a PAL/NTSC thing?

I don't understand, you tested with both a Go Pro and FFmpeg?

>How do I see the resolution of the stream?

When you use FFmpeg it shows the stream information in the terminal.
For the Go Pro, try opening the stream with ffplay, it will show the same information as FFmpeg.

**Comment by FunkFreaksAmsterdam** [comment]
In order to have the GoPro streaming in webcamoid, I need to run fffmpeg otherwise it won’t load.

Streaming video: h264 848x700 25fps 25tbr

is that enough informations?

**Comment by hipersayanX** [comment]
@FunkFreaksAmsterdam Yes, that's enough.

>848x700

The problem is that the width of the video (848) is not multiple of 32, and Webcamoid is not handling the align properly.

**Comment by FunkFreaksAmsterdam** [comment]
Yes, it was indeed that, once changed the resolution in the Camera Suite settings, now it works! Thanks for sharing the infos!!
