### ISSUE TITLE
Is Virtual Camera mode supposed to be a virtual camera?

### ISSUE THREAD

**Issue by PatientZerobeat** [webcamoid/webcamoid#299]
**Mac OS 10.14.6 and Webcamoid 8.7.1**

I don't have a USB camera (nor can I seem to buy one nowadays; every store is sold out that I have tried). What I'm trying to do is use software that can only derive its video source from a camera (like Zoom), but instead use the output of my video card. In other words, I'd like the "camera" source for software like Zoom to simply be whatever I'm seeing on my display. 

But even if I had a camera, there are times when I simply want the video that the software (like Zoom) is seeing to be whatever I am seeing on my display. There is a feature in Zoom called "Share Screen" but this doesn't work for my purposes (because only 1 user can share a screen, plus it becomes the exclusive image that everybody is seeing). 

Is "Virtual Camera" mode in Webcamoid supposed to provide this feature? If so, I can't get it to work.

**Comment by hipersayanX** [comment]
It has [some limitations](https://github.com/webcamoid/webcamoid/issues/220#issuecomment-599091191) but yes, it can be detected as a virtual camera.
