### ISSUE TITLE
Face detection, blur outter

### ISSUE THREAD

**Issue by gianluca-mascolo** [webcamoid/webcamoid#300]
Hello, that's not really an issue but a feature request.
Is it possible to add a check button to invert the filter in face detection? That is, I would like to pixelize or blur what is outside my face, not inside the rectangle.

**Comment by timrichardson** [comment]
You can do this now, at least in nightly. Edit the Face Detection plugin and choose Marker Type Blur Outer

**Comment by hipersayanX** [comment]
This was added in 8.8.0.
