### ISSUE TITLE
8.1.0 package on Xubuntu 18.04LTS segfaults

### ISSUE THREAD

**Issue by galenthurber** [webcamoid/webcamoid#302]
the package will install on Xubuntu 18.04LTS

program segfaults
8.1.0+dfsg-7
[Mon May 11 09:47:35 2020] webcamoid[26978]: segfault at 10 ip 00007fd56e701ff3 sp 00007fff8f5ac9f0 
[Mon May 11 09:58:17 2020] webcamoid[27955]: segfault at 10 ip 00007f5ca6531ff3 sp 00007ffd4df25ac0

local user install of 8.7 does not cause segfaults

suggest ubuntu package maintainers update .deb

**Comment by hipersayanX** [comment]
Only report bugs for latest version. Distro developers are responsible for what they package.
