### ISSUE TITLE
not detecting. Bus 004 Device 003: ID 046d:08da Logitech, Inc. QuickCam Messanger

### ISSUE THREAD

**Issue by galenthurber** [webcamoid/webcamoid#303]
while I can capture the quickcam output via cvlc vlc
webcamoid will not detect it
the camera is on
/dev/video via v4l2

is there a way to force detection or addition via the config file?

**Comment by hipersayanX** [comment]
Did you tried with the [daily build](https://bintray.com/webcamoid/webcamoid/webcamoid/daily)?

**Comment by hipersayanX** [comment]
No answer, not reproducible, closing.
