### ISSUE TITLE
Unable to create a second webcam successfully

### ISSUE THREAD

**Issue by Kulkinz** [webcamoid/webcamoid#305]
** Summary

When attempting to add a second virtual camera, it is unable to successfully create one

## Current Behavior

Says that it was unable to create. Yet it does create a virtual webcam instance, but it is unable to display.

## Expected Behavior

Should be able to create a second virtual webcam that is able to take the same feed as the first.

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue bellow:

1.  Go to settings
2.  Create first virtual webcam
3.  Create second virtual webcam
4.  Unable to create. Next reload it will appear in the list, but unable to have data displayed to it.

## Your Environment

* Webcamoid information: 8.7.1 x32
* Operating System information: Windows 10. x64

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
