### ISSUE TITLE
Mount camera in /dev/video0 on macOS

### ISSUE THREAD

**Issue by Glagnar** [webcamoid/webcamoid#308]
# Questinons and other matters?
I am able to run the program fine on macOS and I have made a virtual camera with a test video file, that plays well in PhotoBooth.

What I want to achieve is to be able to mount a camera/virtual camera in my terminal, like I would on Linux.

/dev/videoX or
/akvcam/videoX

But that doesn't seem to be possible, as there are no devices there.

Is this possible ?

**Comment by hipersayanX** [comment]
>Is this possible ?

Yes and no.

First at all those devices are fake paths that doesn't exist in the file system but are required for the plugin [to be properly working](https://github.com/webcamoid/webcamoid/blob/03538e89139373efeb778b79ffabfe06ea276ad4/libAvKys/Plugins/VirtualCamera/src/cmio/VirtualCamera/src/plugininterface.cpp#L441), it can be any string, it does not matters.

The second problem is about emulating a character device and implement V4L2 on top of it like is done in Linux. Character devices requires ioctl calls to be implemented which is only possible in kernel space, requiring code signing and bypassing a lot of security walls in Mac, it does not worth the try.

A third option would be creating two pipe file, one for writing and the other for reading and manged by a service, the files would take the default video format as reference, for example YUY2 640x480, and every chunk of data you send or read from those files would be interpreted as a video frame with that format, additionally creating some other pipes for requesting information and configuring those devices. I'm not interested on it, but if someone what to implement it and there are people interested in that feature, go ahead.

The option I'm contemplating right now is moving all video output code to a CMIO plugin, so other programs and libraries can interface with it without relying on Webcamoid's libraries. That way other people will be able to implement whatever they want with it, and I'm still will have the freedom to modify the internals as I want.

**Comment by Glagnar** [comment]
My end goal was to try to mount the webcam in a docker container with a syntax like this:
```bash
docker run --rm -it -v /dev/video0:/dev/video0 myImage bash
```
This works on Linux, but not macOS. Yesterday I managed to do a workaround with a custom hypervisor using VirtualBox and mounting my USB camera in there - and then accessing it via docker. But the above solution would be much nicer, if it works.

**Comment by hipersayanX** [comment]
As explained before, isn't possible to create a character device that emulates V4L2 in Mac since it's not possible to get access to the kernel space. If you want to do that just use GNU/Linux.
