### ISSUE TITLE
AkVCamAssistant.exe still running even though Webcamoid was uninstalled.

### ISSUE THREAD

**Issue by SkillzGamingYT** [webcamoid/webcamoid#315]
# README

Choose one of the templates bellow that fit better your issue.

# Reporting a problem?

AkVCamAssistant.exe still running even though Webcamoid was installed.

Write here a brief description of the problem.

C:\Program Files\AkVirtualCamera.plugin\x64\AkVCamAssistant.exe still running in background process even though the mother program was uninstalled. (Webcamoid) 
There is also no way to remove the program without going into program files.

Describe the problem the best as you can, don't omit information.

If Webcamoid was uninstalled, AkVirtualCamera should too.

How it should have work?

Uninstall Webcamoid. (all components)
Restart your PC.
Open Task Manager and look for AkVirtualCamera.

=

## Suggestions and tips

Make the uninstaller also remove the AkVirtualCamera?
HKLM\System\CurrentControlSet\Services << also check this registry.

## Your Environment

* Webcamoid information: lastest
* Operating System information: Windows 10 PRO (64bit)
* Any other useful information:

**Comment by hipersayanX** [comment]
Same as  #178.
