### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by katsar0v** [webcamoid/webcamoid#317]
Just installed this application + akvcam (built from source), but nothing really works:

![image](https://user-images.githubusercontent.com/7236157/83963750-87878880-a8a8-11ea-84b8-94f1305608f0.png)

Really bad. 

The "take a photo" button works, but does not nothing:

![image](https://user-images.githubusercontent.com/7236157/83963759-9706d180-a8a8-11ea-80ea-ce08a1c0c667.png)

OS: Ubuntu 18.04

**Comment by hipersayanX** [comment]
Show me a screenshot of _Preferences > General Options_.

**Comment by katsar0v** [comment]
Nothing happens if I click on Preferences

**Comment by hipersayanX** [comment]
Does it show some error massage in the terminal?
Also, try master branch instead.

**Comment by hipersayanX** [comment]
No answer, closing.
