### ISSUE TITLE
Crashing when press "ok" in virtual cam form

### ISSUE THREAD

**Issue by tonn** [webcamoid/webcamoid#318]
## Summary

I'm trying to add virtual camera. 
1. Check "Virtual camera" checkbox
2. Press "Add" button
3. Enter "123" to "Camera name" input. Or not.
4. Press "Ok" button.

## Current Behavior

App is crashed.

## Your Environment

Windows 10 64bit latest.
Webcamoid 8.7.1 64 and 32

# Questinons and other matters?

Where can I get app logs?

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
