### ISSUE TITLE
Virtual webcam not working

### ISSUE THREAD

**Issue by epiixgd76** [webcamoid/webcamoid#321]
simpliest when i want to put a video on the virtual webcam in apps like google meet or zoom the virtual webcam not works 
(i use v4l2loopback)

**Comment by hipersayanX** [comment]
Try akvcam instead.

**Comment by RealFoxes** [comment]
This is due to the directory where the program is located, try changing the path so that it contains only Latin characters

**Comment by antoineMoPa** [comment]
I had this problem on Debian and it was fixed by:

    apt-get install v4l2loopback-dkms

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
