### ISSUE TITLE
Virtual Camera working, but not showing output in Windows 10

### ISSUE THREAD

**Issue by tonyridal** [webcamoid/webcamoid#326]
<img width="1128" alt="webcamoid problem" src="https://user-images.githubusercontent.com/67265638/85273818-061e2180-b476-11ea-9059-09dacab40bd3.png">

This is Windows 10 - I've seen a similar problem reported on Macs, but no applicable solution.

I'm 95% of the way to getting this to do what I need - the attached screenshot should explain all.

I've setup the matrix transform to flip the image as desired - this is working fine in the Webcamoid app. I've setup a virtual camera, called "flipped webcam 2", which Microsoft Teams can see fine and use.

What's not working is Webcamoid is not outputting to the virtual camera - I'm getting the "Enable virtual camera" message, even though it already is enabled, even when I look at it in the Webcamoid app (second screenshot)… 

Any help gratefully received!
<img width="1128" alt="webcamoid problem 2" src="https://user-images.githubusercontent.com/67265638/85274711-37e3b800-b477-11ea-8e23-dcd47f1dfcac.png">

**Comment by An-land** [comment]
I've got the exact same issue, both on kde neon and on windows 10. I've tried with both of the available drivers, but couldn't figure out how to get it to work. I tried to find a guide on how to make the virtual camera use the webcam as its input, but I was unable to find one.

**Comment by anchithAcharya** [comment]
@tonyridal Try pressing the stop button at the bottom left, and then 'play' it again. That worked for me.

**Comment by sijanec** [comment]
Yup, can confirm @anchithAcharya 's solution on Windows 10.0.18363 Pro. The problem happened after the latest Windows upgrade.

**Comment by Shamrockie** [comment]
I'm having the same issue as well, however stopping the camera and turning it back on did not work for me.

**Comment by rajesh-smartwebtech** [comment]
yes not working in win 10 same issue here

**Comment by Fusseldieb** [comment]
This software is beyond broken on W10 Pro 19043

![image](https://user-images.githubusercontent.com/4715129/135853401-3557870c-f54c-43e3-905e-339090546c38.png)
Virtual Webcam remains empty

When selecting any mp4 file as a source, when pressing play simply crashes the program and hinders it from running ever again until I change the filename of that file

No Webcam appears in VLC

And it takes ages to start up

A bummer...

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
