### ISSUE TITLE
links in Wiki maybe wrong (Updated Build and install in GNU Linux and FreeBSD)

### ISSUE THREAD

**Issue by shingo-ohki** [webcamoid/webcamoid#334]
[This](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-GNU-Linux-and-FreeBSD#installing-dependencies) in the Wiki maybe wrong.

I hope this helps.
https://github.com/shingo-ohki/webcamoid_wiki/commit/b74ab3a52ddb78feffc2097ae3c163b529ba368c

**Comment by hipersayanX** [comment]
I've updated the wiki and used permalinks instead so I won't need to update the wiki constantly. Thank!
