### ISSUE TITLE
Can Webcamoid rotate a video feed?

### ISSUE THREAD

**Issue by zylstra** [webcamoid/webcamoid#343]
Can Webcamoid rotate a video feed, by 90 degrees?

**Comment by hipersayanX** [comment]
There's no specific plugin for that, but you can use **Matrix Transform** to rotate the source, for example the following matrix rotate the video 45°:

```
0.7071 -0.7071
0.7071  0.7071
```

https://en.wikipedia.org/wiki/Rotation_matrix

**Comment by dchmelik** [comment]
> There's no specific plugin for that, but you can use **Matrix Transform** to rotate the source, for example the following matrix rotate the video 45°:

I need this to mirror-flip photo on Webcamoid 8.8 (9 won't even save photo) but there's no 'save/apply' button(s) for rotation matrix effect?

**Comment by hipersayanX** [comment]
Now there is a Rotate plugin in the [video-converter branch](https://github.com/webcamoid/webcamoid/tree/video-converter), I'll release it with 9.1.0.
@dchmelik there is no need for an apply button, the changes are applied intermediately.

**Comment by hipersayanX** [comment]
Feature added in Webcamoid 9.1.0.

**Comment by stav-ros** [comment]
> Feature added in Webcamoid 9.1.0.

Hi, there is a rotate function, but is there a mirror-flip function in the works?
