### ISSUE TITLE
Concatenation of effects/plugins

### ISSUE THREAD

**Issue by BonScottCH** [webcamoid/webcamoid#344]
Hi would it be possible to create a Plugin that allows to combine effects (stacking). This would be very useful in some circumstances where image enhancements should be combined.

If there is such a functionality already how can I use it? I didn't find any documentation.

**Comment by hipersayanX** [comment]
That feature is already available in the daily build as **Chain effect** https://github.com/webcamoid/webcamoid/issues/216#issuecomment-618757525:
