### ISSUE TITLE
on macos, there is always a crash when I call CMIOObjectAddPropertyListener to listen device change

### ISSUE THREAD

**Issue by ZhikaiZuo** [webcamoid/webcamoid#347]
when I call CMIOObjectAddPropertyListener(kCMIOObjectSystemObject, inAddress, inListener, inClientData) to listen device change event, a carsh alway happens.

const CMIOObjectPropertyAddress propertyAddress = {
kCMIOHardwarePropertyDevices,
kCMIOObjectPropertyScopeGlobal,
kCMIOObjectPropertyElementMaster
};

**the dump in my app:**
perating system: Mac OS X
                  10.15.6 19G73

CPU: amd64
     family 6 model 142 stepping 9
     4 CPUs

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x0
Crash time:    1599207333

Thread 0 (crashed)
  0  libsystem_platform.dylib + 0xe52
      r10 = 0x00007f9296679c00      r11 = 0x00007fff6460a3de
      r12 = 0x0000000000000000      r13 = 0x00007f929667df00
      r14 = 0x00007ffeeb5d5860      r15 = 0x00007f929661a3d0
       r8 = 0x0000000000000004       r9 = 0x0000000000000004
      rax = 0x0000000000000000      rbp = 0x00007ffeeb5d57a0
      rbx = 0x0000000000000000      rcx = 0x0000000000000000
      rdi = 0x0000000000000000      rdx = 0x0000000000000000
      rip = 0x00007fff674fde52      rsi = 0x0000000000000000
      rsp = 0x00007ffeeb5d57a0
     Found by: given as instruction pointer in context
  1  libc++.1.dylib + 0x383f2
      rbp = 0x00007ffeeb5d57c0      rip = 0x00007fff6460a3f3
      rsp = 0x00007ffeeb5d57b0
     Found by: previous frame's frame pointer
  2  AkVirtualCamera + 0x4540
      rbp = 0x00007ffeeb5d5a00      rip = 0x0000000109ceb541
      rsp = 0x00007ffeeb5d57d0
     Found by: previous frame's frame pointer
  3  AkVirtualCamera + 0x633b
      rbp = 0x00007ffeeb5d5a20      rip = 0x0000000109ced33c
      rsp = 0x00007ffeeb5d5a10
     Found by: previous frame's frame pointer
  4  AkVirtualCamera + 0x4324
      rbp = 0x00007ffeeb5d5a40      rip = 0x0000000109ceb325
      rsp = 0x00007ffeeb5d5a30
     Found by: previous frame's frame pointer
  5  CoreFoundation + 0xfd75c
      rbp = 0x00007ffeeb5d5a50      rip = 0x00007fff2d31675d
      rsp = 0x00007ffeeb5d5a50
     Found by: previous frame's frame pointer
  6  CoreFoundation + 0xfd5c6
      rbp = 0x00007ffeeb5d5a90      rip = 0x00007fff2d3165c7
      rsp = 0x00007ffeeb5d5a60
     Found by: previous frame's frame pointer
  7  CoreMediaIO + 0x111f8
      rbp = 0x00007ffeeb5d5b90      rip = 0x00007fff2e5261f9
      rsp = 0x00007ffeeb5d5aa0
     Found by: previous frame's frame pointer
  8  CoreMediaIO + 0x458f
      rbp = 0x00007ffeeb5d5c50      rip = 0x00007fff2e519590
      rsp = 0x00007ffeeb5d5ba0
     Found by: previous frame's frame pointer
  9  CoreMediaIO + 0x4113
      rbp = 0x00007ffeeb5d5c80      rip = 0x00007fff2e519114
      rsp = 0x00007ffeeb5d5c60
     Found by: previous frame's frame pointer
 10  CoreMediaIO + 0x3f7e
      rbp = 0x00007ffeeb5d5c90      rip = 0x00007fff2e518f7f
      rsp = 0x00007ffeeb5d5c90
     Found by: previous frame's frame pointer
 11  CoreMediaIO + 0x2298
      rbp = 0x00007ffeeb5d5ce0      rip = 0x00007fff2e517299
      rsp = 0x00007ffeeb5d5ca0
     Found by: previous frame's frame pointer
 12  CoreMediaIO + 0xadb9
      rbp = 0x00007ffeeb5d5d80      rip = 0x00007fff2e51fdba
      rsp = 0x00007ffeeb5d5cf0
     Found by: previous frame's frame pointer

**the dump in AkVCamAssistant:**
Process:               AkVCamAssistant [14648]
Path:                  /Library/CoreMediaIO/*/AkVirtualCamera.plugin/Contents/Resources/AkVCamAssistant
Identifier:            AkVCamAssistant
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           AkVCamAssistant [14648]
User ID:               501

Date/Time:             2020-09-06 16:37:02.370 +0800
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Bridge OS Version:     4.6 (17P6065)

Time Awake Since Boot: 5400 seconds

System Integrity Protection: enabled

Crashed Thread:        1  Dispatch queue: com.apple.root.default-qos.overcommit

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [14648]

VM Regions Near 0:
--> 
    __TEXT                 00000001046bc000-00000001046d4000 [   96K] r-x/rwx SM=COW  /Library/CoreMediaIO/*/AkVirtualCamera.plugin/Contents/Resources/AkVCamAssistant

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff67695dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff67696170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2d4e9ef5 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff2d4e89c2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff2d4e7e3e CFRunLoopRunSpecific + 462
5   com.apple.CoreFoundation      	0x00007fff2d570489 CFRunLoopRun + 40
6   AkVCamAssistant               	0x00000001046bd5c5 0x1046bc000 + 5573
7   libdyld.dylib                 	0x00007fff67554cc9 start + 1

Thread 1 Crashed:: Dispatch queue: com.apple.root.default-qos.overcommit
0   AkVCamAssistant               	0x00000001046bdb24 0x1046bc000 + 6948
1   libxpc.dylib                  	0x00007fff6779922c _xpc_connection_call_event_handler + 56
2   libxpc.dylib                  	0x00007fff6779806b _xpc_connection_mach_event + 726
3   libdispatch.dylib             	0x00007fff674fb6f8 _dispatch_client_callout4 + 9
4   libdispatch.dylib             	0x00007fff67513fc7 _dispatch_mach_cancel_invoke + 65
5   libdispatch.dylib             	0x00007fff6751195c _dispatch_mach_invoke + 1057
6   libdispatch.dylib             	0x00007fff6750ac09 _dispatch_workloop_worker_thread + 596
7   libsystem_pthread.dylib       	0x00007fff67755a3d _pthread_wqthread + 290
8   libsystem_pthread.dylib       	0x00007fff67754b77 start_wqthread + 15

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff67754b68 start_wqthread + 0

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fff8dcb89a0  rcx: 0x0000000000000000  rdx: 0x00000000000f7cb0
  rdi: 0x0000000000000004  rsi: 0x00007ff4b5400000  rbp: 0x000070000a4598a0  rsp: 0x000070000a459870
   r8: 0x00000000000001da   r9: 0x0000000000000003  r10: 0x00007ff4b5400000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x00007ff4b5605a30  r14: 0x00007ff4b5406160  r15: 0x00007ff4b5605a50
  rip: 0x00000001046bdb24  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Binary Images:
       0x1046bc000 -        0x1046d3ffb +AkVCamAssistant (0) <C59AA490-D371-3DD4-AD0B-09A814BD91BA> /Library/CoreMediaIO/*/AkVirtualCamera.plugin/Contents/Resources/AkVCamAssistant
       0x10b6f9000 -        0x10b78af47  dyld (750.6) <34A11073-9E4C-38C3-9293-7D566ABAE8B6> /usr/lib/dyld
    0x7fff2d466000 -     0x7fff2d8e5feb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff64063000 -     0x7fff64065ff7  libDiagnosticMessagesClient.dylib (112) <C94F3B7B-1854-38EB-9778-834501C53B3F> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff64539000 -     0x7fff6453afff  libSystem.B.dylib (1281.100.1) <001B3B7F-D02C-31D3-B961-1ED445D5A266> /usr/lib/libSystem.B.dylib
    0x7fff6481f000 -     0x7fff64871fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff64872000 -     0x7fff64887ffb  libc++abi.dylib (902) <E692F14F-C65E-303B-9921-BB7E97D77855> /usr/lib/libc++abi.dylib
    0x7fff652f1000 -     0x7fff652f3fff  libfakelink.dylib (149.1) <36146CB2-E6A5-37BB-9EE8-1B4034D8F3AD> /usr/lib/libfakelink.dylib
    0x7fff65403000 -     0x7fff6565afff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff66399000 -     0x7fff663ccfde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff66a75000 -     0x7fff66a87ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff67336000 -     0x7fff6733bff3  libcache.dylib (83) <5940876E-AC8A-3BE0-80B3-DE3FB14E257A> /usr/lib/system/libcache.dylib
    0x7fff6733c000 -     0x7fff67347fff  libcommonCrypto.dylib (60165.120.1) <C095BD55-1D27-337F-9B02-885E1C7FF87A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff67348000 -     0x7fff6734ffff  libcompiler_rt.dylib (101.2) <6E80AC11-A277-31FA-AEEF-E5A528274C77> /usr/lib/system/libcompiler_rt.dylib
    0x7fff67350000 -     0x7fff67359ff7  libcopyfile.dylib (166.40.1) <EB5E0BC8-873D-3546-A40E-C36DC46FA8F6> /usr/lib/system/libcopyfile.dylib
    0x7fff6735a000 -     0x7fff673ecfdb  libcorecrypto.dylib (866.140.1) <0B6C52DB-5A50-3FCD-8B5E-C0C2F35857E3> /usr/lib/system/libcorecrypto.dylib
    0x7fff674f9000 -     0x7fff67539ff0  libdispatch.dylib (1173.100.2) <EAD535EE-1270-39A9-A254-95CF117FF3B0> /usr/lib/system/libdispatch.dylib
    0x7fff6753a000 -     0x7fff67570fff  libdyld.dylib (750.6) <24C41E8B-6B33-30C7-94C9-02D2BD051D66> /usr/lib/system/libdyld.dylib
    0x7fff67571000 -     0x7fff67571ffb  libkeymgr.dylib (30) <6F582FDB-EB1A-3ED2-A989-B750643E2647> /usr/lib/system/libkeymgr.dylib
    0x7fff6757f000 -     0x7fff6757fff7  liblaunch.dylib (1738.140.1) <AFBCBDD3-0B55-3ECD-8E04-A73A3A57356B> /usr/lib/system/liblaunch.dylib
    0x7fff67580000 -     0x7fff67585ff7  libmacho.dylib (959.0.1) <1B0296B5-3FD0-342C-BCC2-9886351A4391> /usr/lib/system/libmacho.dylib
    0x7fff67586000 -     0x7fff67588ff3  libquarantine.dylib (110.40.3) <67FE2676-F9E8-3797-AEE5-F5F9D191CFA3> /usr/lib/system/libquarantine.dylib
    0x7fff67589000 -     0x7fff6758aff7  libremovefile.dylib (48) <5CEBDAB2-988A-3B66-87BC-3C45D1C08730> /usr/lib/system/libremovefile.dylib
    0x7fff6758b000 -     0x7fff675a2ff3  libsystem_asl.dylib (377.60.2) <7A07FF86-658E-35D7-8136-829737E98B7B> /usr/lib/system/libsystem_asl.dylib
    0x7fff675a3000 -     0x7fff675a3ff7  libsystem_blocks.dylib (74) <0D53847E-AF5F-3ACF-B51F-A15DEA4DEC58> /usr/lib/system/libsystem_blocks.dylib
    0x7fff675a4000 -     0x7fff6762bfff  libsystem_c.dylib (1353.100.2) <AF7873B0-AC4A-3C67-89BB-B8DA87718DAE> /usr/lib/system/libsystem_c.dylib
    0x7fff6762c000 -     0x7fff6762fffb  libsystem_configuration.dylib (1061.141.1) <0EE84C33-64FD-372B-974A-AF7A136F2068> /usr/lib/system/libsystem_configuration.dylib
    0x7fff67630000 -     0x7fff67633fff  libsystem_coreservices.dylib (114) <08B89E9B-C5B2-3E73-8964-03E58692B21F> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff67634000 -     0x7fff6763cfff  libsystem_darwin.dylib (1353.100.2) <BD5BAD5B-AC3F-371A-B4FC-ADF86D6DCE51> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6763d000 -     0x7fff67644fff  libsystem_dnssd.dylib (1096.100.3) <01E0965B-83E5-356C-AC1F-C723F5AAB483> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff67645000 -     0x7fff67646ffb  libsystem_featureflags.dylib (17) <6317641E-B43F-36A3-974E-6073786B94B9> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff67647000 -     0x7fff67694ff7  libsystem_info.dylib (538) <4DD813CB-D7B0-3AB5-9054-D2E4FF7A64B9> /usr/lib/system/libsystem_info.dylib
    0x7fff67695000 -     0x7fff676c1ff7  libsystem_kernel.dylib (6153.141.1) <2B6311E6-6240-3EF7-8C87-475B66F7452C> /usr/lib/system/libsystem_kernel.dylib
    0x7fff676c2000 -     0x7fff67709fff  libsystem_m.dylib (3178) <77A9D888-36E9-3968-8103-C82FFFC60B9E> /usr/lib/system/libsystem_m.dylib
    0x7fff6770a000 -     0x7fff67731fff  libsystem_malloc.dylib (283.100.6) <059F4DBD-856A-3A59-8B20-FD4B6918C5F2> /usr/lib/system/libsystem_malloc.dylib
    0x7fff67732000 -     0x7fff6773fffb  libsystem_networkextension.dylib (1095.140.2) <4CCE78C9-1DC4-3375-9828-D5BD739D23F3> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff67740000 -     0x7fff67749ff7  libsystem_notify.dylib (241.100.2) <DEAD75F2-DD34-3E8F-82DE-344625A2C25E> /usr/lib/system/libsystem_notify.dylib
    0x7fff6774a000 -     0x7fff67752fef  libsystem_platform.dylib (220.100.1) <97E825F6-D823-366C-9FF3-B1C8EA891044> /usr/lib/system/libsystem_platform.dylib
    0x7fff67753000 -     0x7fff6775dfff  libsystem_pthread.dylib (416.100.3) <80B053AA-B6F7-3B59-BC44-78A5A4F7368F> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6775e000 -     0x7fff67762ff3  libsystem_sandbox.dylib (1217.140.4) <20BF94E2-DAB8-3EBE-AACE-99DF84C1C391> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff67763000 -     0x7fff67765fff  libsystem_secinit.dylib (62.100.2) <28EDEB6F-899B-373D-B761-4C20D39285D9> /usr/lib/system/libsystem_secinit.dylib
    0x7fff67766000 -     0x7fff6776dffb  libsystem_symptoms.dylib (1238.120.1) <22800D8C-5C2A-3171-8C29-311BBE67F198> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6776e000 -     0x7fff67784ff2  libsystem_trace.dylib (1147.120) <DC00C77E-4709-31F0-B913-CF09559B7A6F> /usr/lib/system/libsystem_trace.dylib
    0x7fff67786000 -     0x7fff6778bff7  libunwind.dylib (35.4) <42B7B509-BAFE-365B-893A-72414C92F5BF> /usr/lib/system/libunwind.dylib
    0x7fff6778c000 -     0x7fff677c1ffe  libxpc.dylib (1738.140.1) <58E276A9-EE11-3F02-9D3E-5371E604E677> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 43
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 475568
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=400.5M resident=0K(0%) swapped_out_or_unallocated=400.5M(100%)
Writable regions: Total=81.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=81.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            24.0M        1 
Kernel Alloc Once                    8K        1 
MALLOC                            48.1M       18 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        3 
Stack                             9232K        3 
__DATA                            2049K       46 
__DATA_CONST                        20K        1 
__LINKEDIT                       388.8M        3 
__OBJC_RO                         32.3M        1 
__OBJC_RW                         1908K        2 
__TEXT                            11.7M       45 
__UNICODE                          564K        1 
mapped file                         32K        1 
shared memory                       44K        5 
===========                     =======  ======= 
TOTAL                            574.6M      136

**Comment by zzk167** [comment]
is there some updates?

**Comment by hipersayanX** [comment]
@zzk167 I've splitted the virtual camera into it's [own project](https://github.com/webcamoid/akvirtualcamera), beside that I haven't checked this issue yet.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
