### ISSUE TITLE
Daily Builds for Windows Are Out of Date

### ISSUE THREAD

**Issue by lukasubo** [webcamoid/webcamoid#350]
## Summary

Daily builds for windows are 4 months out of date.

## Current Behavior

All platforms have daily builds from 3 days ago except for windows.

## Expected Behavior

Windows builds from the same time as other platforms.

## Steps to Reproduce

Visit the following link:

https://bintray.com/webcamoid/webcamoid/webcamoid/daily#files/windows

**Comment by hipersayanX** [comment]
It may be working now.
