### ISSUE TITLE
Webcamoid not working after Droidcam

### ISSUE THREAD

**Issue by vlig** [webcamoid/webcamoid#355]
Hello! After playing with Droidcam, on the next start, Webcamoid doesn't do anything. Buttons are able to be pressed, but no response at all. Deleting ~/.config/Webcamoid isn't helpful. OBS shows my webcam well, BUT image freezes after a while.
And after close, there is a process in memory with ~12% of CPU using.
![изображение](https://user-images.githubusercontent.com/19915584/94317427-f5a6a700-ff8e-11ea-922c-12c8910957f2.png)
![изображение](https://user-images.githubusercontent.com/19915584/94317535-40c0ba00-ff8f-11ea-80e4-0f56d2f08794.png)
Arch Linux + KDE Plasma 5, up to date.
UPD. Only removing droidcam helps(((

**Comment by hipersayanX** [comment]
This issue is probably related to #259 and was solved in the daily build.

**Comment by ppcutter** [comment]
Same issue here with Ubuntu 20.04.2 LTS linux x86_64 Webcamoid 8.8.0 and Droidcam. With Webcamoid 8.7.1 everything works fine.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
