### ISSUE TITLE
Webcamoid should not notify user about new version if installed from the deb/APT repository

### ISSUE THREAD

**Issue by N0rbert** [webcamoid/webcamoid#358]
## Summary

On Debian based systems Webcamoid may be installed from repository. On Ubuntu is came from the universe pocket.

## Current Behavior

On first launch of Webcamoid on the freshest Ubuntu 20.10, it reports that new version is 8.7.1 is available.

## Expected Behavior

Webcamoid should not inform about the new version if it is installed as deb-package.

## Steps to Reproduce

1. Install Ubuntu 20.10
2. Launch Webcamoid

## Suggestions and tips

Forcing user to use non-deb package on the system will confuse the user.

The downstream bug-report is available on https://pad.lv/1898419 .

## Your Environment

Ubuntu 20.10, webcamoid 8.6.1+dfsg-2.1

**Comment by hipersayanX** [comment]
Totally disagree, I won't waste my time providing solutions for old versions of Webcamoid, users reporting bugs that was already solved in newer versions will just pollute the issues list.
If Debian maintainers want to maintain and old deprecated and buggy version of Webcamoid  their are on their own and their are the only responsible for patching it. But users **must** be warmed that a new version is available, and anyway users can disable the notification if they don't want it.
