### ISSUE TITLE
Unable to play streams on latest code

### ISSUE THREAD

**Issue by nejatafshar** [webcamoid/webcamoid#363]
I can not play video streams (e.g. live h264 camera streams) on the latest code, although there is no problem on 8.7.1. I made some tests and figured out the problem. By commenting these codes:
https://github.com/webcamoid/webcamoid/blob/94c9aad31b9d039379b689334735ac5fd40a16dc/libAvKys/Plugins/MultiSrc/src/ffmpeg/src/mediasourceffmpeg.cpp#L749-L751

I can successfully play camera streams after compiling. Any hint how this could be fixed properly?

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
