### ISSUE TITLE
Webcam settings cut off on main window

### ISSUE THREAD

**Issue by SammyTheBEAST** [webcamoid/webcamoid#367]
## Summary

Settings for the webcams are cut off on the main window, I don't see any other way to set resolution which is what I needed it for.

## Current Behavior

[Screenshot](https://imgur.com/a/xz2WwMT)
On the right side I opened the settings menu for my webcam, all of the options are cut off and can't be clicked on. I tried this in the XFCE and Qtile window manager, both don't work.

## Expected Behavior

The buttons and menu should be shifted an inch to the left.

## Your Environment

* Webcamoid information: webcamoid-git 8.7.1.r363.g74a9a95b AUR
* Operating System information: 5.8.16-2-MANJARO Qtile

**Comment by hipersayanX** [comment]
Drag the panel handler (the vertical line) to the left.
