### ISSUE TITLE
Trouble uninstalling

### ISSUE THREAD

**Issue by lipton1998** [webcamoid/webcamoid#368]
Hello, I've tried Webcamoid but uninstalled it since I preferred the UI of a different Virtual Camera I installed. Then I used the other application but the "breathing" 'TRIAL' message from Webcamoid keeps overlaying my Virtual Camera output...
Very frustrating because Webcamoid keeps crashing after I reinstalled.  Anybody got an idea on how to fix this?

**Comment by hipersayanX** [comment]
>Hello, 

Hi

>I've tried Webcamoid but uninstalled it since I preferred the UI of a different Virtual Camera I installed. Then I used the other application but the "breathing" 'TRIAL' message from Webcamoid keeps overlaying my Virtual Camera output...

Webcamoid is [Free Open Source Software](https://github.com/webcamoid/webcamoid/blob/master/COPYING), there is not [such](https://github.com/webcamoid/webcamoid/search?q=breathing&type=code) [messages](https://github.com/webcamoid/webcamoid/search?q=TRIAL&type=code) in Webcamoid, those messages are coming from the other app you have installed.

>Very frustrating because Webcamoid keeps crashing after I reinstalled. Anybody got an idea on how to fix this?

Try [resetting the settings](https://github.com/webcamoid/webcamoid/wiki/Reset-configs-and-starting-fresh).

**Comment by sleepindawg** [comment]
I can't get webcamoid to uninstall from win10

**Comment by hipersayanX** [comment]
@sleepindawg how did you installed? what was the error message.

**Comment by sleepindawg** [comment]
No error message, It just doesn't uninstall. I ended up deleting the folder and running CCleaner to take out the registry entries.

**Comment by hipersayanX** [comment]
@sleepindawg If there is not error message or any way to reproduce it, then that bug can't be solved.

**Comment by hipersayanX** [comment]
@sleepindawg could it be that you have installed the daily build and when uninstalling you get a black cmd window for few seconds?

**Comment by sleepindawg** [comment]
I suppose I could try reinstalling it and see if it will do the same thing again. I personally am only going to do this in the interest of assisting with development as people at gethub.com provide a great service to everyone with little compensation.

**Comment by sleepindawg** [comment]
I doubt it was the daily build, but it could have been.

**Comment by hipersayanX** [comment]
@sleepindawg will check it, I had a similar problem when testing the virtual camera, it could be a bug in QtIFW maybe.
