### ISSUE TITLE
Controlling PTZ camera 

### ISSUE THREAD

**Issue by tskarthikeyann** [webcamoid/webcamoid#370]
I tried to control two cameras connected with a machine. http://www.imaginart.es/produccion_av/lumens/pdf/VC-B30U_DataSheet_English(LUI)-2017-1129.pdf is the one I use. 
The camera uses the standard UVC driver and as per the dataset.
It seems the ptz controls work, but the camera doesn't move sometimes. It gets stuck. Sometimes, Going to another camera and coming back activates the camera movement again, but not all the time. I think all other camera properties are getting controlled without any issues. 

It would be great if you are able to help with this.

**Comment by hipersayanX** [comment]
>It would be great if you are able to help with this.

I can't give you any help with that because I've not any camera like that, but in theory it should work.

**Comment by tskarthikeyann** [comment]
Thanks for your response. After some serious debugging, found that the issue was because of USB 2.0. Everything starts working well as expected with USB 3.0. I can contribute to making the movement a little more smoother.. I will keep you posted on that. Thank you.
