### ISSUE TITLE
Unable to make the virtual camera work in Zoom (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by ytx21cn** [webcamoid/webcamoid#371]
# Bug description

## Summary

I installed webcamoid and want to make a working virtual camera. I also installed the **v4l2loopback** virtual camera driver. Then I tried with a short video randomly pulled off from Instagram: [test video.zip](https://github.com/webcamoid/webcamoid/files/5504407/test.video.zip). However, when I opened Zoom to test it, it does not work at all.

## Current Behavior

The Zoom app does not recognize any virtual webcam at all.

## Expected Behavior

Zoom should show up the virtual web camera with the name and video feed set by myself.

## Steps to Reproduce

1. Install webcamoid from http://webcamoid.github.io/ (choose the **Installable, 64 bits** version, since I am using Ubuntu 20.04 LTS).
1. Install the v4l2loopback-dkms package: `$ sudo apt install v4l2loopback-dkms`.
1. Load the `v4l2loopback` module: `$ sudo modprobe v4l2loopback`.
1. Add a virtual webcam: open webcamoid, click on **Preferences** → **Virtual camera** → **Devices** → **Add**, and name it with a simple name "test-cam".
![Screenshot from 2020-11-07 16-05-26](https://user-images.githubusercontent.com/5900105/98453898-1d069d00-2113-11eb-85cb-6f0b48afc965.png)
1. Switch to **Configure sources**, and add the short video I prepared previously. Then hit the **Play** button to start playing the video.
![Screenshot from 2020-11-06 22-56-15](https://user-images.githubusercontent.com/5900105/98434329-7c1cd100-2083-11eb-833f-5f77f7776142.png)
1. Open Zoom, and select **New meeting**. Then check the camera list. Here, only my built-in camera "HP Truevision HD" is showing up, but no virtual camera is listed here.
![Screenshot from 2020-11-06 22-58-43](https://user-images.githubusercontent.com/5900105/98434417-239a0380-2084-11eb-9d26-7a15d75900c2.png)
1. I also installed `v4l2loopback-utils` package. Here is the command line output of `v4l2-ctl --list-devices`:
	```
	test-cam (platform:v4l2loopback-000):
		/dev/video2
	
	HP Truevision HD: HP Truevision (usb-0000:00:1a.0-1.1):
		/dev/video0
		/dev/video1
	```
1. Here is my output of `$ lsmod | grep v4l2`:
	```
	v4l2loopback           40960  0
	videobuf2_v4l2         24576  1 uvcvideo
	videobuf2_common       49152  2 videobuf2_v4l2,uvcvideo
	videodev              225280  5 videobuf2_v4l2,v4l2loopback,uvcvideo,videobuf2_common
	mc                     53248  4 videodev,videobuf2_v4l2,uvcvideo,videobuf2_common
	```

It seems like that the virtual webcam driver "v4l2loopback" has correctly loaded the virtual camera. But the software using webcam are not detecting the virtual webcam and receiving the inputs from it. (I also tried Firefox and Chromium, and the virtual webcam is not working either.) Did I miss any important steps? Thank you.

## Your Environment

* Webcamoid information: 8.7.1, 64-bit
* Operating System information: Ubuntu 20.04 LTS, 64-bit
* Zoom version: 5.4.1 (53350.1027)
* Firefox version: 82.0.2 (64-bit)
* Chromium version: Version 86.0.4240.183 (Official Build) snap (64-bit)

**Comment by Leonpmlinux** [comment]
I have the same problem with v4l2loopback, it was updated on November 6 and everything works fine in OBS Studio, but when entering platforms like Zoom and Google Meet, it does not recognize the virtual camera.

**Comment by hipersayanX** [comment]
v4l2loopback is very limited, many programs rejects the camera, you should try with [akvcam](https://github.com/webcamoid/akvcam) instead.

**Comment by ytx21cn** [comment]
The v4l2loopback got a new update in the recent days.
```
$ apt list v4l2loopback-dkms -a
Listing... Done
v4l2loopback-dkms/focal-updates,focal-updates,now 0.12.3-1ubuntu0.2 all [installed]
v4l2loopback-dkms/focal,focal 0.12.3-1 all
```

My virtual webcam is working again!
![1](https://user-images.githubusercontent.com/5900105/99914296-4ac21900-2cb1-11eb-9cbb-e19ea1ba9c9b.png)

**Comment by hipersayanX** [comment]
@ytx21cn nice! :smiley:
