### ISSUE TITLE
Enable virtual webcam output not working, or not obvious.

### ISSUE THREAD

**Issue by gh-markt** [webcamoid/webcamoid#373]
## Summary

I am finding that other applications cannot get any video feed from a virtual camera crreated with webcamoid.

I believe this issue may be a related one to #273.   I had commented there, but as that issue was for the Mac, and my issue was with Linux, I was directed to create a new issue.  

## Current Behavior
I appear to be able to create a virtual camera in webcamoid (when run as root), and the virtual webcam is selectable by other apps as a video source, but only produces the following image in any application that tries to access the virtual camera:

![image](https://user-images.githubusercontent.com/31718967/98565020-f3a85700-2261-11eb-8468-5b9c9ef9b858.png)

I have not been able to find any way enable the webcam output in the webcamoid app to direct the source to the virtual webcam output, however.  

I am not entirely sure if I am not looking in the correct place for how to enable webcam output, or if this is actually a bug

I experience the same effects with zoom as well as in-browser apps which access the webcam whenI set the webcam device to use in that application to the virtual one, and do not experience any issues using the regular webcam while webcamoid is not running.

## Your Environment

 I am using linux 5.4.73, on a modern AMD processor, with akvcam as a virtual camera driver.

**Comment by alexbossers** [comment]
I experience the same. Tried both akvcam as well as the loopback device.

Running current version of ubuntu 20.10 and kernel 5.4.0-58-generic on intel xeon.. 

- Using webcamoid repository version 8.6.1. Works by itself as a charm including live effects.
- Manually compiled akvcam 1.1.1 and installed using dkms. It is present next to the v4l2loopback device in lib/modules/5.4.0-58-generic/updates/misc/akvcam.ko

I configured webcamoid to output to a new virtual cam (see image).
![image](https://user-images.githubusercontent.com/9135624/103172949-bae73000-4857-11eb-9121-eebba83391dc.png)

My configuration is default and changing fake driver makes no difference.
![image](https://user-images.githubusercontent.com/9135624/103172992-0b5e8d80-4858-11eb-829a-84569305b7ae.png)

Any logs I can provide to help troubleshoot this?

**Comment by hipersayanX** [comment]
@alexbossers I need to solve some stability problems in akvcam, newer kernels added more fields to API structures, and v4l2-compliance did not give any clue of that, I will return with Webcamoid and this issue once I finish with akvcam.

**Comment by leonardobsjr** [comment]
Any way to solve this? Ubuntu 24.04 Webcamoid 8.6.1 - Have this same screen on Teams :|

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
