### ISSUE TITLE
Listing Applications Currently Using Virtual Camera

### ISSUE THREAD

**Issue by dot-net-pow-lead** [webcamoid/webcamoid#380]
Is it possible to list the applications using the virtual camera driver?

**Comment by hipersayanX** [comment]
Webcamoid 9.0.0 will have that feature. Also if you are using GNU/Linux you can use ```fuser /dev/videoX``` to get the program using the virtual camera.

**Comment by hipersayanX** [comment]
Feature added in 9.0.0, closing.
