### ISSUE TITLE
Unable to change the 'Check New Versions' setting under the 'Updates' tab in Preferences Menu

### ISSUE THREAD

**Issue by castarr** [webcamoid/webcamoid#385]
## Summary

I'm unable to make any changes to the 'Check new versions' setting under the 'Updates' tab in Preferences Menu

## Current Behavior

When I select an option from the dropdown menu it updates the field, but there is no button to save this setting and if I navigate away from that screen in anyway and then return to the screen the setting has reverted to 'Daily'

## Expected Behavior

If there is no 'Save' button, one would presume that the setting would save automatically when the setting has been changed. This is not what is happening. 

## Steps to Reproduce

1.  Click 'Preferences'
2.  Click 'Updates'
3.  Change 'Check new versions' drop down to any setting besides 'Daily'
4.  Click 'Plugins Configs'
5. Click 'Updates' again
6. Notice that your change has not been saved

## Suggestions and tips

Add a 'Save' button? 

## Your Environment

* Webcamoid information: (version: 8.7.1) 
* Operating System information: (Windows 10) (10.0.18362 Build 18362)

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
