### ISSUE TITLE
Can webcamoid be made to recognize pre-UVC (20yo) Intel webcam?

### ISSUE THREAD

**Issue by bdutta** [webcamoid/webcamoid#390]
Wondering if there is a way to make Webcamoid work with pre-UVC (20 year old) Intel Pro-Share webcam.This webcam works fine in 'guvcview' on Ubuntu 18.04.4 LTS also works fine (at 320x240, I get 4 fps and this is good enough for my needs). This is on a intel i3-3240 on a H61 motherboard with 4GB DDR3 RAM.

**lsusb shows this:**
Bus 002 Device 006: ID 0733:0430 ViewQuest Technologies, Inc. Intel Pro Share Webcam

**/dev/video0 device exists:**
~$ ls -l /dev/video0 
crw-rw----+ 1 root video 81, 0 Jan  4 17:13 /dev/video0

**detailed output of lsusb -v for this device:**
Bus 002 Device 006: ID 0733:0430 ViewQuest Technologies, Inc. Intel Pro Share Webcam
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x0733 ViewQuest Technologies, Inc.
  idProduct          0x0430 Intel Pro Share Webcam
  bcdDevice            0.90
  iManufacturer           0
  iProduct                0
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength          137
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0000  1x 0 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0080  1x 128 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       2
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0180  1x 384 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       3
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       4
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0280  1x 640 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       5
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0300  1x 768 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       6
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0380  1x 896 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       7
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x03ff  1x 1023 bytes
        bInterval               1

**dmesg output for this cam:**
[ 4192.389618] usb 2-1.4: new full-speed USB device number 6 using ehci-pci
[ 4192.467598] usb 2-1.4: New USB device found, idVendor=0733, idProduct=0430, bcdDevice= 0.90
[ 4192.467601] usb 2-1.4: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 4192.488826] mc: Linux media interface: v0.10
[ 4192.497574] videodev: Linux video capture interface: v2.00
[ 4192.502898] gspca_main: v2.14.0 registered
[ 4192.503520] gspca_main: spca505-2.14.0 probing 0733:0430
[ 4192.506486] usbcore: registered new interface driver spca505
[ 4731.129708] spca505 2-1.4:1.0: alt 6 - bandwidth not wide enough, trying again
[ 4731.170831] spca505 2-1.4:1.0: alt 5 - bandwidth not wide enough, trying again
[ 4731.210720] spca505 2-1.4:1.0: alt 4 - bandwidth not wide enough, trying again
[ 4731.462829] spca505 2-1.4:1.0: alt 6 - bandwidth not wide enough, trying again
[ 4731.503203] spca505 2-1.4:1.0: alt 5 - bandwidth not wide enough, trying again
[ 4731.543953] spca505 2-1.4:1.0: alt 4 - bandwidth not wide enough, trying again
[ 4742.900894] spca505 2-1.4:1.0: alt 7 - bandwidth not wide enough, trying again
...

**Comment by hipersayanX** [comment]
Install **libv4l-0** and try running Webcamoid with:

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l1compat.so webcamoid
```

or 

```
LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l1compat.so webcamoid
```
