### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by csverma610** [webcamoid/webcamoid#401]
Hello,

After creating a virtual camera, I tried calling the OpenCV's, VideoCapture of the Virtual Camera.
I get the following error:

error: (-215:Assertion failed) api != 0 in function 'getBackendName'

However, the camera runs smoothly on VLC player.

Any suggestion will be helpful.

**Comment by hipersayanX** [comment]
I need context. which operating system? which version? which driver?

**Comment by hipersayanX** [comment]
No answer closing.
