### ISSUE TITLE
Modify Purple Placeholder Image on Linux / Windows

### ISSUE THREAD

**Issue by bwyyoung** [webcamoid/webcamoid#403]
How do you modify the Webcamoid placeholder image for virtual cameras on linux / windows?

**Comment by hipersayanX** [comment]
In Windows, if I remember well, the placeholder was saved in the install path at _C:\Program Files\AkVirtualCamera.plugin\share_.
It must be a 24 or 32 bit BMP file, and the width must be divisible by 32.
In Linux you must set the [default_frame](https://github.com/webcamoid/akvcam/wiki/Configure-the-cameras#no-signal-picture) option in _/etc/akvcam/config.ini_. Same rules apply for the BMP file.

**Comment by bwyyoung** [comment]
Thank you. default_frame.bmp was what I was looking for.
