### ISSUE TITLE
Wrong comment for german desktop file

### ISSUE THREAD

**Issue by freddii** [webcamoid/webcamoid#404]
the file https://github.com/webcamoid/webcamoid/blob/master/webcamoid.desktop
has a comment for german with:

Comment[de]=Maak foto's en video's opnemen met uw webcam

but that is dutch and not german.

it should be:
Comment[de]=Nehme Fotos und Videos mit deiner Webcam auf

**Comment by hipersayanX** [comment]
Fixed, thanks!
