### ISSUE TITLE
Virtual cam not appearing in Skype or Zoom

### ISSUE THREAD

**Issue by ifuchs** [webcamoid/webcamoid#412]
Running v8.8.0 and created a Virt Cam. Started/ Stopped and followed what I thought were the directions to be able to see a feed in Zoom and Skype but it does not show up.

**Comment by hipersayanX** [comment]
Which operating system?

**Comment by ifuchs** [comment]
OSX

**Comment by hipersayanX** [comment]
Tested with Zoom in a test call (with the new driver), and [it's working fine](https://github.com/webcamoid/akvirtualcamera/wiki/Support-status#mac). Can't test Skype, I won't create an account in any of this two apps.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
