### ISSUE TITLE
Compilation error:

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/webcamoid#413]
Hello,

On a latest Mac, I get the following error:

$ qmake libAvKys.pro
Project ERROR: Qt 5.9.0 or higher required, current installed version is 6.0.2

What change I have to make?

Thanks

**Comment by hipersayanX** [comment]
I've not ported Webcamoid to Qt6 yet, you must install Qt5:

```
brew install qt@5
```

If I remember well the qmake for Qt5 executable was located at _/usr/local/Cellar/qt@5/bin_.
