### ISSUE TITLE
Simple Usage

### ISSUE THREAD

**Issue by shersoni610** [webcamoid/webcamoid#414]
Hello,

I am looking for a simple example that emulates python fakecamera:

import pyfakewebcam
import numpy as np

blue = np.zeros((480,640,3), dtype=np.uint8)
blue[:,:,2] = 255

camera = pyfakewebcam.FakeWebcam('/dev/video1', 640, 480)
while True:
    camera.schedule_frame(red)

How can I do this in WebCamoid using C++?

Thanks

**Comment by hipersayanX** [comment]
Closing since you opened an issue [here](https://github.com/webcamoid/akvirtualcamera/issues/13). I'll answer there.
