### ISSUE TITLE
Can't change anything

### ISSUE THREAD

**Issue by KonradLinkowski** [webcamoid/webcamoid#427]
I just want a fake camera to check if my html video conference app works fine.
Can't change anything. The app is lacking a tutorial. I don't know how to add a video. I don't what Media UID is, but it isn't editable. There is no other input to change the video. Any clues?
![image](https://user-images.githubusercontent.com/26126510/113156766-975ac980-923a-11eb-9bb7-59839f2fe70d.png)

**Comment by hipersayanX** [comment]
Click, in the big green **+** button, in the bottom left corner, Media file, Search, and select the video file.

**Comment by KonradLinkowski** [comment]
This interface suggests that this green button should add new elements to the list on the left-hand side.
The button with the tooltip "add video source" seems to be adding video sources.

**Comment by hipersayanX** [comment]
Yes, because the virtual camera will play whatever video source you are playing.
