### ISSUE TITLE
(win) Program opens partially out of the screen

### ISSUE THREAD

**Issue by samozrejme** [webcamoid/webcamoid#429]
After reinstalling webcamoid (8.8.0) in order to uninstall it properly (story for another thread) the app opened on my 3rd monitor and partially out of it. 

Triple monitor setup - no1&no2: 2560x1440, **no3: 1280x1024**
Windows 10

![image](https://user-images.githubusercontent.com/82269815/114379851-a0785e80-9b89-11eb-8fce-9ff856d221a8.png)

**Comment by hipersayanX** [comment]
This is the same as #117, closing.
