### ISSUE TITLE
Error creating camera (Mac OS)

### ISSUE THREAD

**Issue by TheSeamau5** [webcamoid/webcamoid#435]
Hi, 

I'm on Mac OS 10.15.7 and I'm unable to create a Virtual camera. I opened the webcamoid app, clicked on preferences, and then in the Output tab, I checked Virtual camera and tried to "Add" a virtual camera. 

I get a prompt to enter my credentials
<img width="440" alt="Screen Shot 2021-05-29 at 4 44 32 PM" src="https://user-images.githubusercontent.com/3227869/120085381-8a1c5880-c08c-11eb-9b14-a9c000e5100c.png">

After successfully entering them, I simply see "Error creating camera" written. The camera was not created and there are no further error messages. 
<img width="394" alt="Screen Shot 2021-05-29 at 4 41 22 PM" src="https://user-images.githubusercontent.com/3227869/120085401-a7512700-c08c-11eb-9935-fa1ee918e3f2.png">

Would love some more guidance on what is happening and how to resolve and/or assist.

Thanks

**Comment by hipersayanX** [comment]
This is the first time for your using the virtual camera? maybe you have used an older version of Webcamoid? or it's a fresh install?

**Comment by Leemusa** [comment]
I am also experiencing this error on Mac OS 10.14.6. I start the program but there is no way to create a virtual camera.

**Comment by TheSeamau5** [comment]
@hipersayanX I had just installed it and then tried to create the virtual camera. It was my first time using it/fresh install. I haven't tried it since.

**Comment by hipersayanX** [comment]
Try installing the daily build, I've improved the error messages and the virtual camera installation.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
