### ISSUE TITLE
Still image as an input (JPG, PNG, etc.)

### ISSUE THREAD

**Issue by gkostov** [webcamoid/webcamoid#438]
Hi,

I was wondering if it is possible to read a still image (JPG, PNG, etc.) as an input instead of a GIF or some video format? I could not find a way to do it so I created a GIF from the JPG and it worked in a way, but being able to skip the conversion to GIF would be great.

Cheers

**Comment by hipersayanX** [comment]
Not possible for now, but it's a must feature.

**Comment by hipersayanX** [comment]
Feature added in Webcamoid 9.1.0.
