### ISSUE TITLE
Support JACK audio

### ISSUE THREAD

**Issue by wolftune** [webcamoid/webcamoid#44]
Anyone doing real audio stuff on Linux uses JACK as it's much more flexible. Webcamoid appears to only support Pulse Audio. It should add direct ALSA support and full JACK support as options.

**Comment by hipersayanX** [comment]
Thanks a lot for the idea!, my idea is to add audio and camera system detection at compile and runtime for 8.x series. Oss, Alsa and Jack will be supported for sure :smiley:

**Comment by mikhailnov** [comment]
Is it really worth spending time on the dead OSS?

**Comment by mikhailnov** [comment]
But Jack support will be a really great feature, especially when using Webcamoid as a virtual webcam.

**Comment by mikhailnov** [comment]
Because currently the sound from the video played as a virtual webcam must be manually redirected using pavucontrol, for example.

**Comment by wolftune** [comment]
Yeah, zero time should be given to OSS, nobody needs that. All they need are Pulse, ALSA, and JACK.

**Comment by hipersayanX** [comment]
Supporting OSS is because I want Webcamoid to work in platforms like FreeBSD and similar, and I'm not sure if ALSA, JACK and PulseAudio are supported there.

**Comment by hipersayanX** [comment]
Support for optional audio systems has been added in latest release.

**Comment by mikhailnov** [comment]
Thank you!

**Comment by hipersayanX** [comment]
@mikhailnov 👍
