### ISSUE TITLE
No Live preview or Camera Feed in WINPE 10

### ISSUE THREAD

**Issue by shadowwalkersteam** [webcamoid/webcamoid#442]
I'm trying to use Webcamoid in WINPE but its not working there. I've installed all the camera drivers etc and everything is fine in WinPE. 
I tested my webcam on webcamtests.com in WINPE environment and there the Webcam was working perfectly but not in webcamoid. What could be the issue? Can anyone helo me in this issue?

**Comment by hipersayanX** [comment]
Is the webcam detected or not at all? Vendor and model of the camera?

**Comment by shadowwalkersteam** [comment]
Yes Webcam detected. It is USB HD WEBCAM.

**Comment by hipersayanX** [comment]
>Yes Webcam detected.

Can you show me an screenshot of this part?

![Screenshot_20210716_115856](https://user-images.githubusercontent.com/1249885/125968312-9365e33e-a3d3-499b-94e2-14f036bf9cfd.png)

>It is USB HD WEBCAM (that is what is showing in device manager under Cameras)

Is a generic or integrated webcam? because I need to know which native formats are supported by that camera, otherwise i can't do anything with the information you are giving me.

**Comment by shadowwalkersteam** [comment]
@hipersayanX  
![IMG_4714-min](https://user-images.githubusercontent.com/26341269/126312589-8b63903c-97cd-4323-85b1-6d385a394ed3.png)
![IMG_4715-min](https://user-images.githubusercontent.com/26341269/126312697-b1b175bc-1a96-4ea3-8d26-c81b3c8ad1fb.png)

It is integrated webcam.

**Comment by hipersayanX** [comment]
Everything seems to be ok in the capture, the webcam and all it's parameters are detected, it an obvious question but, it could be that you forgot to click the Start/Stop button maybe?

**Comment by shadowwalkersteam** [comment]
@hipersayanX I tried that as well but no success. I clicked Start/Stop buttons multiple times.

**Comment by shadowwalkersteam** [comment]
@hipersayanX I've tried this application https://www.sordum.org/8585/webcam-on-off-v1-4/
and it is also working fine.

**Comment by hipersayanX** [comment]
Did you tried the [daily build](https://github.com/webcamoid/webcamoid/releases/tag/daily-build), does it have the same problem?

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
