### ISSUE TITLE
Lack of software function settings

### ISSUE THREAD

**Issue by Alvazz** [webcamoid/webcamoid#453]
MacOS 10.15.7
Webcamoid 8.8.0
USB Webcam

I see the picture in the Readme, there are parameter settings for the camera. But why I downloaded and installed Webcamoid 8.8.0, and then there are no parameters.

【This is an official picture】
![webcamoid_org](https://user-images.githubusercontent.com/50744096/131944691-ecb39bb7-71f1-4f63-be05-ebe31f202241.png)

【This is the picture of the software after I actually installed it】
<img width="1016" alt="webcamoid_now" src="https://user-images.githubusercontent.com/50744096/131944762-76d25e03-50fd-489c-af65-264a5f575360.png">

**Comment by hipersayanX** [comment]
This is being discussed here #333. In resume, Mac camera APIs doesn't provide native support for webcams UVC controls, and any solution is just a mere hack that could work or not.
