### ISSUE TITLE
reduce the delay when recording in 1280x800

### ISSUE THREAD

**Issue by evanescente-ondine** [webcamoid/webcamoid#454]
Hi,

I have the 8.6.1 version.
I wish to record at a 1280x800 resolution, the problem is there is an awful lagging of the display, several seconds, and the guy who is recorded needs to see himself talking, like in a miror. I have 4 processors, only 2 are used fully by wemcamoid. I have debian testing.
What can I do to reduce the display resolution but record the same ?
Or to reduce the delay in any way ?

Thanks.

**Comment by hipersayanX** [comment]
Please, use latest version. Old versions has not support.
