### ISSUE TITLE
Present in Applications after Uninstalling Ubuntu 20.04

### ISSUE THREAD

**Issue by andrewshrout** [webcamoid/webcamoid#456]
I have uninstalled via the command line, and I can't find the program in my list of installed applications anymore. However, the webcamoid icon is still present.

**Comment by hipersayanX** [comment]
How did you exactly uninstalled it from the command line, did not you uninstalled it from the uninstaller (WebcamoidUninstall or WebcamoidMaintenanceTool, whatever it was called)?

**Comment by hipersayanX** [comment]
No answer, closing.
