### ISSUE TITLE
half way to same effect chaining, help needed, it's not crashing!

### ISSUE THREAD

**Issue by j2l** [webcamoid/webcamoid#457]
On ubuntu 20.04, by duplicating the same effect file, 
![image](https://user-images.githubusercontent.com/65325/133463473-2ba5c3ff-c437-4007-9031-1bbc27e5e9ce.png)

I can apply it twice with different values. For example, replace light green with red and dark green with blue:
![image](https://user-images.githubusercontent.com/65325/133460671-3a431f8a-6f08-4267-9b75-8966e41dbdea.png)

Both are visible in the effects list.

# Reporting a problem?
2 problems:
- We can't change effect settings individually. Switching from one effect to the other, settings shown are only the ones of the FIRST effect (green to red in my case).
- When you quit and relaunch webcamoid, only the LAST effect is applied (the blue one), all effects become useless.

## Summary
It's a low hanging fruit because it's almost working as is, so it's kind of a bug (it uses existing build) and a FR.
Only settings and maybe plugin name should be individually distinguished among these copies.

## How would you solve the problem?
Being able to to tweak settings name in source (already here, just need a 2 lines tutorial)
A way to build a single effect from source?
OR
Dynamically generate setting names to be unique and don't remove the effect from the effects list once it's applied.

## Your Environment
* Webcamoid information: (8.8.0) ubuntu 20.04 x64

## Steps to Reproduce
In my case, copy `libColorReplace.so` and paste it in the same folder
Webcamoid > Settings > plugins configs > path > Refresh
Tweak and add the same effect
Enjoy the rainbow of your effects (yes, it works with more than 2 times the same effect):
![image](https://user-images.githubusercontent.com/65325/133462362-2a93fe59-4724-4d3d-a9fe-1d3350dfa94f.png)

**Comment by hipersayanX** [comment]
Interesting :laughing:, even though I was not aware of this bug specifically, I knew that assigning a plugin ID based on it's file name was a wrong idea, so I've changed the [plugin detection method](https://github.com/webcamoid/webcamoid/commit/3f8ba805140b820f1a69338c00632434ee8e694f) like 10 days ago, now Webcamoid should not be able to detect the same plugin more than once, like you did before. Also, I've added [effects chaining](https://github.com/webcamoid/webcamoid/issues/216#issuecomment-618757525) like one and half year ago. All this features will be available for Webcamoid 9, or you can test it already in the daily build.

**Comment by j2l** [comment]
Oh! Great, thank you @hipersayanX !
Can't wait to see it.
I hope we can chain the same effect again and again :)
Feel free to close this one.
Have a great day!

**Comment by hipersayanX** [comment]
Is the scaling problem still happening? can you give me the DPI and resolution from this page?

**Comment by j2l** [comment]
It seems to be fixed!
BTW, my screen is 89dpi (3840x2160)

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.

**Comment by j2l** [comment]
Great! Thanks
