### ISSUE TITLE
The application is not running Windows 11

### ISSUE THREAD

**Issue by markezz3** [webcamoid/webcamoid#460]
The app has problem with launch. In windows 11 the app is open and close.

**Comment by glenviewjeff** [comment]
Same thing happening in Windows 10.

**Comment by glenviewjeff** [comment]
Faulting application name: webcamoid.exe, version: 8.8.0.0, time stamp: 0x00000000
Faulting module name: obs-virtualcam-module64.dll, version: 26.1.0.0, time stamp: 0x5fd7c3c7
Exception code: 0xc0000005
Fault offset: 0x000000000003db4e
Faulting process id: 0xc8c
Faulting application start time: 0x01d7c6eeeb58f9ab
Faulting application path: C:\Program Files\webcamoid\bin\webcamoid.exe
Faulting module path: C:\Program Files\obs-studio\data\obs-plugins\win-dshow\obs-virtualcam-module64.dll
Report Id: 3d19722b-a801-45b0-b523-0b0cee206912
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mnns** [comment]
I don't have and never had OBS installed, it is crashing upon startup (window opens and closes right after), on Windows 11. Can't get it to work, portable does the same.

**Comment by tuxStarElan** [comment]
same here,
os: windows 11 home
never installed OBS 
webcamoid shortly shows application windows and instantly closes

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.

**Comment by MHketbi** [comment]
i have the same issue, the executable is running in the task manager but no ui on windows 11.
