### ISSUE TITLE
want both x86 and x64 app can see the same virtual camera, behaves the same.

### ISSUE THREAD

**Issue by yinkaisheng** [webcamoid/webcamoid#462]
My PC is Windows 10 x64 edition.
I downloaded webcamoid-portable-8.8.0-win64.zip and webcamoid-portable-8.8.0-win32.zip
and extracted them to different folders,
and installed akvirtualcamera-windows-9.0.0.exe

I ran webcamoid 8.8.0 **x64** edition and added a virtual camera named '**VirtualCamera1**'.
I ran webcamoid 8.8.0 **x86** edition and my app 86 edition,
but my app x86 editon and webcamoid 8.8.0 **x86** edition can't see the VirtualCamera1.

Then I closed all apps.
I ran webcamoid 8.8.0 **x86** edition and added a virtual camera named '**VirtualCamera2**'.

Then I closed all apps.
I ran webcamoid 8.8.0 **x64** edition again, the x64 editon only can see VirtualCamera1.
I ran webcamoid 8.8.0 **x86** edition again, the x86 editon can see both VirtualCamera1 and VirtualCamera2.

This is the picture shows that both x86 and x64 are running.
![image](https://user-images.githubusercontent.com/5846696/138321162-aa8317a8-3dba-476c-8bdc-cf4262789097.png)

Webcamoid 8.8.0 **x86** edition can't see VirtualCamera1 first,
but after adding a vitual camera by itself, it can see VirtualCamera1.

**Comment by hipersayanX** [comment]
Could it be because because in x64 you have the virtual camera enabled and you are sending to VirtualCamera2, and in x86 you have the virtual camera disabled? anyway you are testing an edge case which I did never tested.
