### ISSUE TITLE
Application fails on startup if OBS Studio virtual camera is installed

### ISSUE THREAD

**Issue by glenviewjeff** [webcamoid/webcamoid#464]
## Current Behavior

Application does not start successfully if OBS Studio (64-bit) virtual camera is installed. Updating OBS had no effect. Latest build of Windows webcamoid installed. Window's Event Log error below.

## Environment
Windows 10 64-bit

## Logs:
Faulting application name: webcamoid.exe, version: 8.8.0.0, time stamp: 0x00000000
Faulting module name: obs-virtualcam-module64.dll, version: 26.1.0.0, time stamp: 0x5fd7c3c7
Exception code: 0xc0000005
Fault offset: 0x000000000003db4e
Faulting process id: 0xc8c
Faulting application start time: 0x01d7c6eeeb58f9ab
Faulting application path: C:\Program Files\webcamoid\bin\webcamoid.exe
Faulting module path: C:\Program Files\obs-studio\data\obs-plugins\win-dshow\obs-virtualcam-module64.dll
Report Id: 3d19722b-a801-45b0-b523-0b0cee206912
Faulting package full name:
Faulting package-relative application ID:

**Comment by hipersayanX** [comment]
>I don't understand; you told me you only tried to reproduce on the portable version, not on the installer version. 

Again:

>Also there is no difference between using the portable or the installable, both have the same exact binaries compiled from the same exact source code.

I'll try but there will be not any difference.

**Comment by hipersayanX** [comment]
Can reproduce with latest builds, closing.
