### ISSUE TITLE
Virtual camera not functioning in Win64 standalone build

### ISSUE THREAD

**Issue by glenviewjeff** [webcamoid/webcamoid#466]
## Summary

Virtual camera not functioning in Win64 standalone build. 

## Current Behavior

Ran Win64 portable build; virtual camera documented to work "out of the box." Opened chrome, tried meet.google.com and https://zoom.us/test. Neither found a virtual camera and showed my physical camera was in use (by Webcamoid.) Repeated test on Firefox, same results.

Incidentally it is mentioned in other issues that there is a preference to enable the webcam. No such option appears to exist in this build. I assume the documentation is either obsolete or it does not apply to the Windows build.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
