### ISSUE TITLE
Win32 portable daily build not functioning

### ISSUE THREAD

**Issue by glenviewjeff** [webcamoid/webcamoid#467]
## Summary

Running Win32 portable build gives me a gray screen as if the camera is not recognized. Win64 portable works fine.

![image](https://user-images.githubusercontent.com/334914/139477065-cb69a918-c159-4a03-ab30-275ef352164b.png)

**Comment by hipersayanX** [comment]
It could be a problem with the deployment, but anyway I'm not sure if I should keep providing the 32 bits version.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
