### ISSUE TITLE
dependencies missing for Xubuntu18LTS

### ISSUE THREAD

**Issue by galenthurber** [webcamoid/webcamoid#472]
# Reporting a problem?

## Summary

won;t start due to missing dependencies

## Current Behavior

webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Quick.so.5)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Gui.so.5)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Qml.so.5)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Core.so.5)
webcamoid: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libQt5Core.so.5)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libpng16.so.16)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libicui18n.so.66)
webcamoid: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/west/webcamoid/lib/x86_64-linux-gnu/libicuuc.so.66)

## Expected Behavior

loaded

## Suggestions and tips

list dependencies

## Your Environment

8.8.0  64
Xubuntu 18LTS

**Comment by hipersayanX** [comment]
Webcamoid's binaries are compiled in Ubuntu 20.04 LTS Focal Fossa, it won't never work in older versions of Ubuntu, and in general, it won't work in distros with glibc older than 2.29.
