### ISSUE TITLE
The Arch Linux package does not compile

### ISSUE THREAD

**Issue by danielshub** [webcamoid/webcamoid#473]
The Arch Linux package (https://aur.archlinux.org/packages/webcamoid/) does not build/compile.

`src/image/videoformat.cpp: In member function ‘AkVCam::VideoFormat AkVCam::VideoFormat::nearest(const std::vector<AkVCam::VideoFormat>&) const’:
src/image/videoformat.cpp:289:19: error: ‘numeric_limits’ is not a member of ‘std’
  289 |     auto q = std::numeric_limits<uint64_t>::max();
      |                   ^~~~~~~~~~~~~~
src/image/videoformat.cpp:289:42: error: expected primary-expression before ‘>’ token
  289 |     auto q = std::numeric_limits<uint64_t>::max();
      |                                          ^
src/image/videoformat.cpp:289:45: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  289 |     auto q = std::numeric_limits<uint64_t>::max();
      |                                             ^~~
      |                                             std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from src/image/videoformat.cpp:21:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make[4]: *** [Makefile:374: release/Qt5.15.2/gpp/x86_64/obj/videoformat.o] Error 1
make[4]: Leaving directory '/build/webcamoid/src/webcamoid-8.8.0/libAvKys/Plugins/VirtualCamera/src/VCamUtils'
make[3]: *** [Makefile:49: sub-src-VCamUtils-make_first-ordered] Error 2
make[3]: Leaving directory '/build/webcamoid/src/webcamoid-8.8.0/libAvKys/Plugins/VirtualCamera'
make[2]: *** [Makefile:304: sub-VirtualCamera-make_first] Error 2
make[2]: Leaving directory '/build/webcamoid/src/webcamoid-8.8.0/libAvKys/Plugins'
make[1]: *** [Makefile:135: sub-Plugins-make_first-ordered] Error 2
make[1]: Leaving directory '/build/webcamoid/src/webcamoid-8.8.0/libAvKys'
make: *** [Makefile:48: sub-libAvKys-make_first-ordered] Error 2`

**Comment by hipersayanX** [comment]
Fixed, thanks!
