### ISSUE TITLE
No camera preview shown

### ISSUE THREAD

**Issue by slhck** [webcamoid/webcamoid#477]
# Reporting a problem?

## Summary

I see no camera preview when opening the app.

## Current Behavior

When opened, Webcamoid does not show any camera preview:

![image](https://user-images.githubusercontent.com/582444/147694321-8a083b24-473b-4144-8c8f-9acd5346f4a2.png)

The same goes for a third-party camera connected via USB-C:

![image](https://user-images.githubusercontent.com/582444/147694134-0dbb179e-4c97-4a42-b4f3-9f4ea67be98c.png)

The cameras themselves work (as tested with FaceTime, OBS, …) and their lights are on.

## Expected Behavior

I am expecting to see a camera preview.

## Steps to Reproduce

1.  Open Webcamoid
2.  Select any camera

## Your Environment

* Webcamoid information: Daily build from 29.12.2021
* Operating System information: macOS 12.1 (21C52), ARM64
* MacBook Pro M1 with built-in FaceTime camera

**Comment by hipersayanX** [comment]
Let say you select the YUY2, and you switch **Play sources** on and off, it still does not works?

**Comment by slhck** [comment]
I switched to the Logitech cam and selected YUV2. Switching that toggle does nothing; it also doesn't really look like it's on or off:

![image](https://user-images.githubusercontent.com/582444/147698833-0770b2e8-0063-43eb-8da0-6cb7e4db7751.png)

**Comment by hipersayanX** [comment]
Can you test this and #478 in the daily build? hopefully it should be working now.

**Comment by slhck** [comment]
I can now see the preview but it's all blue:

![image](https://user-images.githubusercontent.com/582444/148436164-84456da5-da90-4c1d-b1e4-1cfdeb5ddc51.png)

I'm putting up grayscale cards so you get the idea.

This is happening with all cameras, both for the FaceTime camera with the v024 color format as well as the Logitech StreamCam with YUV2.

**Comment by hipersayanX** [comment]
Now I've switched the data capture format to 24RGB, maybe it should work now, maybe. In my case its already working fine, so not sure at all what's causing it on your side.

**Comment by slhck** [comment]
Yes, it works now, thank you!

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
