### ISSUE TITLE
Virtual camera error : can't create a vcam

### ISSUE THREAD

**Issue by Hydr0Btz** [webcamoid/webcamoid#479]
Hello guys,
I'm here because i have a problem since i installed webcamoid : i want to create a vcam to have effects on websites such as omegle or for obs studio. I'm using kubuntu lts 20.04 and my webcamoid version is 8.8.0. i already installed v4l2loopback. the problem i have might be related to #273 

The problem is that when i want to create a virtual cam it doesn't show me anything in the first chosing space like that (even when i click)
![Screenshot_20220102_003228](https://user-images.githubusercontent.com/78450732/147862352-ce9bd587-cc52-4e0e-b448-8942050e96f8.png)
And then i try to click on add and then i chose a name and enter my password and it tells me an error with no description :
![Screenshot_20220102_003339](https://user-images.githubusercontent.com/78450732/147862367-cda3d1b9-b0ba-4bed-82f4-0187656c733f.png)
 I really want those issue to be resolved asap so if you know how to setup a vcam that would help me a lot !

**Comment by hipersayanX** [comment]
You can try with the daily build, I've improved the error messages, it can probably give a better clue of what is happening.

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.
