### ISSUE TITLE
Question on non integer zoom factors

### ISSUE THREAD

**Issue by Hirnfiedler** [webcamoid/webcamoid#484]
It seems there are two options to zoom in.
  1. The option in the virtual output device
  2. The matrix transformation.
  
But both methods seem to support only integers as factors. Did I missed an option or could anyone suggest a matrix (zoom 150%)

**Comment by hipersayanX** [comment]
I don't remember if the Matrix transform plugin handles float values in the 8.8 version, but in the daily build it does.  For a zoom of 150% just use the matrix:

```
1.5   0
 0   1.5
```

**Comment by Hirnfiedler** [comment]
Upps, that easy. :)
Thanx a lot
