### ISSUE TITLE
Webcamoid crashes when I change from the laptop's webcam to the USB one

### ISSUE THREAD

**Issue by Gerardo1G** [webcamoid/webcamoid#485]
## Summary

Webcamoid crashes when I change from the laptop's webcam to the USB one.

## Current Behavior

When I open the program, it shows the default webcam, which is the laptop's. If I choose the USB one, it lags and a little after, then an alert window pops up stating that Webcamoid stopped working, and offers a single button that says "close program". After I close the program, if I keep the USB webcam plugged in and try to open the program again, it crashes even before showing its interface. It will only let it load if I unplug the USB webcam before opening Webcamoid. This has happened from the moment I installed the program; I haven't changed anything in its configuration.

## Expected Behavior

The program should allow me to select the USB webcam, show its image, and let me work on the USB webcam with the program's its different options.

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue below:

1.  Open Webcamoid
2.  Click on "Configure source"
3. Click on "FHD Camera"

"FHD Camera" is the name given to my USB webcam in my computer. I don't have any other USB webcams to try it with different ones.

## Suggestions and tips

I have no idea. For some reason, this USB webcam seems to be incompatible with Webcamoid. It should be made compatible somehow. It does work with every other program I use with it.

## Your Environment

* Webcamoid version 8.8 using Qt 5.15.2
* Windows 8.1 Single Language 
* Intel Core i5-3317U
* 8 GB RAM
* Acer V5-171-6699
* YOHOOLYO Full HD 1080p webcam: https://www.yohoolyo.net/product/webcam-1080p-full-hd-webcam-with-microphone-and-privacy-cover-living-streaming-web-camera-for-laptop-desktop-autofocus-usb-plug-and-play-video-calls-conference-online-class-zoom-meeting.html

**Comment by hipersayanX** [comment]
Problem solved in 9.0.0, closing.

**Comment by Gerardo1G** [comment]
Thank you.
