### ISSUE TITLE
After installing webcamoid on Ubuntu 21.10 it has renamed my cameras.

### ISSUE THREAD

**Issue by jcwinters** [webcamoid/webcamoid#486]
I installed webcamoid, I have 2  cameras, and both my cameras were renamed to `Video Capture 5`- this appears to cause problems in Zoom with random freezing of the stream after some time.  So i removed webcamoid and both the webcams are still called `Video Capture 5`

I ran udevadm test on them and I can see that `ID_V4L_PRODUCT` has been renamed, as shown.

```SUBSYSTEM=video4linux
TAGS=:uaccess:snap_chromium_chromedriver:snap_chromium_chromium:seat:
ID_V4L_VERSION=2
ID_V4L_PRODUCT=Video Capture 5
ID_V4L_CAPABILITIES=:capture:
```

I've searched everywhere on how to name these back, but have found no guidance.  Any tips on how I fix this?

**Comment by hipersayanX** [comment]
It happened to me too in Arch, but this is not related to Webcamoid, Webcamoid can't do something like that, it seems to be a bug related to the kernel or V4L2, probably you can try downgrading your kernel until you find where it was introduced, but this is not related to this project.
