### ISSUE TITLE
Session/Root problems Ubuntu 16.10 (Duplicate of issue #43)

### ISSUE THREAD

**Issue by danielbarbier** [webcamoid/webcamoid#49]
Hi! I'm trying to create a virtual camera with some effects and I'm not able to do it.
I've been trying to create a new device as a normal user and as a root admin.
As a Normal user, it returns "Wrong Password", and as root, it "creates" it but there's no print of it in /dev/.
Tryed compiling it myself and this was the answer

```
~/webcamoid-7.2.0$ dpkg-buildpackage -us -uc
tail: no se puede abrir 'debian/changelog' para lectura: No existe el archivo o el directorio
dpkg-buildpackage: fallo: final de «debian/changelog» devolvió un estado de salida de error 1
```
as some kind of non existing file debian/changelog

I don't know much about compiling my own software, but I read there is a way to set Root Method on .conf file. How do I do that? On Webcamoid.conf file there is no ROOT_METHOD entry.
Any guide?

**Comment by hipersayanX** [comment]
**ROOT_METHOD** was a last hour fix, it was added in version [7.2.1](https://github.com/webcamoid/webcamoid/issues/43#issuecomment-243582504). Just download latest version and follow the [Debian build guide](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-the-Debian-package).
