### ISSUE TITLE
Missing files in 9.0.0

### ISSUE THREAD

**Issue by lgbaldoni** [webcamoid/webcamoid#493]
# Reporting a problem?

## Summary

Some files no longer being installed in 9.0.0

## Current Behavior

Until 8.8.0 these files and folders were also being installed:
```
/usr/include/avkys
/usr/include/avkys/ak.h
/usr/include/avkys/akaudiocaps.h
/usr/include/avkys/akaudiopacket.h
/usr/include/avkys/akcaps.h
/usr/include/avkys/akcommons.h
/usr/include/avkys/akelement.h
/usr/include/avkys/akfrac.h
/usr/include/avkys/akmultimediasourceelement.h
/usr/include/avkys/akpacket.h
/usr/include/avkys/akplugin.h
/usr/include/avkys/akvideocaps.h
/usr/include/avkys/akvideopacket.h
/usr/lib64/qt5/qml/AkQml
/usr/lib64/qt5/qml/AkQml/libAkQml.so
/usr/lib64/qt5/qml/AkQml/qmldir
```

## Expected Behavior

Unsure, just asking.

## Steps to Reproduce

`/usr/bin/cmake /home/abuild/rpmbuild/BUILD/webcamoid-9.0.0/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH
=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHAR
E_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUI
LD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasync
hronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wal
l -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -
Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-stro
ng -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '
-DCMAKE_EXE_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS=-flto=
auto -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS=-flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUF
FIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFIL
E:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/webcamoid`

## Your Environment

* Webcamoid information: 9.0.0 x86_64
* Operating System information: openSUSE Tumbleweed x86_64

# Want a new feature?

# Questions and other matters?

I'm the packager for openSUSE. I would like to know if libavksys is to be shipped with devel files, if not then libavksys.so should not be created either.

**Comment by hipersayanX** [comment]
I did removed the files from install for the moment, since the internal API is very unstable, it make no much sense to make it available for the general public, and anyway there are no any documentation on how to use it yet.

>I would like to know if libavksys is to be shipped with devel files, if not then libavksys.so should not be created either.

Since there are no header files, does not makes much sense to distribute a devel package.
