### ISSUE TITLE
[Advice] Which backend is preferred?

### ISSUE THREAD

**Issue by lgbaldoni** [webcamoid/webcamoid#495]
Packaging 9.0.0 for openSUSE Tumbleweed x86_64 and seeing both gstreamer and libav support: which should be used, ideally? Or should it be linked to both? In that case, which one will be preferred at runtime?

P.S: is the IRC channel still active somewhere?

**Comment by hipersayanX** [comment]
>which should be used, ideally?

FFmpeg/libav for recording, VLC for playback.

>Or should it be linked to both?

Ideally it must be linked to both, and let user choose which one they want at run time.

>In that case, which one will be preferred at runtime?

FFmpeg/libav for recording, VLC for playback.

**Comment by lgbaldoni** [comment]
Ok, but what about gstreamer?

**Comment by hipersayanX** [comment]
You deleted your message, but I will answer anyway. Just compile with support for both, GStreamer and FFmpeg, they are not mutually exclusive.

**Comment by lgbaldoni** [comment]
@hipersayanX ok, for now I'm leaving gstreamer out or there will be too many dependencies to install for a single package.

**Comment by hipersayanX** [comment]
If RPM allow optional dependencies (with for sure, it allows) just put GStreamer as an optional dependency, no need to remove GStreamer at all.

**Comment by lgbaldoni** [comment]
> If RPM allow optional dependencies (with for sure, it allows) just put GStreamer as an optional dependency, no need to remove GStreamer at all.

@hipersayanX libgstreamer will be pulled in if linked. Unsure about what else might be required.
