### ISSUE TITLE
can't make virtual camera(output)-webcamoid 9.0.0

### ISSUE THREAD

**Issue by xyzyi** [webcamoid/webcamoid#496]
after clicking add output nothing happens, when I try to set output picture - can't set virtual camera picture pops up

**Comment by hipersayanX** [comment]
Which operating system?

**Comment by xyzyi** [comment]
ubuntu 20.04, yeah i installed akvcam through installer and installed dkms through terminal

**Comment by hipersayanX** [comment]
I've tested the AppImage and its working fine for me. Give me a capture of _Preferences > General options_.

**Comment by hipersayanX** [comment]
It should be working fine in Webcamoid 9.1.0.
