### ISSUE TITLE
Incorrect video aspect ratio in VirtualCamera

### ISSUE THREAD

**Issue by mixalbl4-127** [webcamoid/webcamoid#512]
I have 1 source device, this is my HD cam with 1280x720 stream and **1.78 aspect ration**
When I create Virtual Camera with akvcam by webcamiod it creates virtual device with a lot of different formats, **including 800x600 with 1.33 aspect ration**.

When I shart stream from my HD cam with 1280x720 (1.78) => Virtual Cam and use it with any web sites, for example Google Meet, this service gets all available formats Virtual Cam and choose 800x600.

As a result original source video 1280x720 (1.78) SCALE DOWN to 800x600 (1.33), as a result:
![image](https://user-images.githubusercontent.com/3511307/163972589-1b0e7969-1ee6-473a-9d3c-5006b887fd39.png)
the most strage situation when I choose as source my mp4 video 1280x720 but google meet requested 800x600 in Virtual Cam and my video scales to it!

Ideas:
1. You have to add more options in Create Virtual Camera menu with format options!
![image](https://user-images.githubusercontent.com/3511307/163972929-6e8f229f-fd72-4ef3-b773-2931be3c2748.png)
2. Virtual Camera must repeat source formats when you streaming from read HD cam to Virtual Cam, you have to exclude unsupported video formats betwean this bridge.
3. When website like Google Meet try to change video output (from HD to SD or other) you have to try change this in original source too (HD cam is real webcam). Ex: Google Meet requested 800x600 video, Virtual Cam got it, changed to 800x600 (like now) and **request to HD Cam (source) to do same and change to 800x600**!
4. When source is mp4 wideo or stream with fixed resolution, for ex 1280x720, Virtual Cam must exclude other formats and give ONLY 1280x720 as source istead of scaling it!

**Temporary kludge solution for linux (set only 1280x720)**:
1. Edit akvcam config manually:
`sudo nano /etc/akvcam/config.ini`
for example my config with ONLY 1280x720 input/output formats:
```
[Cameras]
cameras\1\description=tst (out)
cameras\1\formats=5
cameras\1\mode=mmap, userptr
cameras\1\type=output
cameras\2\description=Zorro
cameras\2\formats=11, 17, 23, 29
cameras\2\mode=mmap, userptr
cameras\2\type=capture
cameras\size=2
```
2. Reload module:
```
sudo rmmod akvcam 
sudo modprobe akvcam
```

as a result, when I have input mp4 or physical HD WebCam with 1280x720 - it works fine, without any scaling!

p.s. I use webcamid 8.6.1 because of https://github.com/webcamoid/webcamoid/issues/510 bug, but I think in 9.0.0 same problem.

**Comment by hipersayanX** [comment]
Click in **Add output** or **Edit** the virtual camera.

![Screenshot_20220419_113949](https://user-images.githubusercontent.com/1249885/164031640-9980106c-2be3-474b-b51b-f1e5a7bf143f.png)

**Clear formats**, **Add format**.

![Screenshot_20220419_114031](https://user-images.githubusercontent.com/1249885/164031645-f2f03413-b131-4356-8589-9eb83c5fa65b.png)

Add whatever format you want.

![Screenshot_20220419_114233](https://user-images.githubusercontent.com/1249885/164033416-ecfde992-778c-48df-9f24-8e090252e803.png)

>p.s. I use webcamid 8.6.1 because of https://github.com/webcamoid/webcamoid/issues/510 bug, but I think in 9.0.0 same problem.

Sorry but old versions has not support, and the feature you want is is already implemented in 9.0.0.
