### ISSUE TITLE
Does not see USB microphone

### ISSUE THREAD

**Issue by holmesrichards** [webcamoid/webcamoid#554]
## Summary

Webcamoid does not recognize USB microphone as a sound source

## Current Behavior

Under Audio > Sources, only settings are Silence, Monitor of Built-in Analog Stereo, Built-in Analog Stereo, and HD Pro Webcam C920 Analog Stereo

## Expected Behavior

I would expect it to also include my TONOR TC30 USB microphone.

## Your Environment

* Webcamoid information: Version 9.0.0
* Operating System information: Linux Mint 20.3 Cinnamon 
* Any other useful information: System sound settings showing USB microphone, Webcamoid audio settings not showing it
![image](https://user-images.githubusercontent.com/56895621/177359970-156f1a61-b3c9-4891-8be8-31a5457a4325.png)

**Comment by hipersayanX** [comment]
What is the output of these commands?

```
pacmd list-cards
pacmd list-sources
```

**Comment by holmesrichards** [comment]
The mic is now showing in webcamoid. I don't know what's changed.
