### ISSUE TITLE
Feature request - Rotate by 90 degrees or 270 degrees

### ISSUE THREAD

**Issue by hdijkema** [webcamoid/webcamoid#555]
# Scanning Dia's with WebCamoid

On the market one can buy dia / negative scanners for old photo's. These devices act like a webcam in Linux. 
Feeding dia's to the device is simple, but one cannot predict (or one needs to inspect all dia frames before feeding them to the device) if the dia's are rotated or inverted. 

It would be great to have two buttons for that on webcamoid, e.g. visible when a checkbox is set  'X scanning dia's'.

Two buttons:

* Rotate 90 degrees (and again, and again, until 360 = 0 degrees). 
* Flip the image, i.e. invert it, i.e. mirror-image (so that text is displayed right). 

![IMG_0585](https://user-images.githubusercontent.com/745693/178770836-7953f85d-930a-4ce2-aaa2-a6edd59f8d2f.jpg)

**Comment by hipersayanX** [comment]
Feature added in Webcamoid 9.1.0.
