### ISSUE TITLE
Mac compatibility in 9.0.0 release

### ISSUE THREAD

**Issue by Digizard** [webcamoid/webcamoid#562]
# Reporting a problem

## Summary

Webcamoid's download page states that "OS X 10.14 or higher required", but both the installable and portable versions state that at least 11.6 is required.

## Current Behavior

Installer works, but the installed Webcamoid won't run. Portable version won't run either.

A popup states:

> **You can’t use this version of the application “Webcamoid” with this version of macOS.**
> You have macOS 10.15.7. The application requires macOS 11.6 or later.

## Expected Behavior

The program would work because the listed requirements are met by my machine.

## Steps to Reproduce

1. Download installer
2. Install
3. Attempt to open Webcamoid

Or

1. Download portable version
2. Open up DMG
3. Run/double click the app

## Suggestions and tips

If you're no longer supporting pre-Big Sur, please update your listed requirements. If you do intend to support the versions listed, please fix the release version.

## Your Environment

* Webcamoid information: 9.0.0
* Operating System information: macOS 10.15.7

**Comment by hipersayanX** [comment]
[Binary packages removed for Mac](https://github.com/webcamoid/webcamoid/issues/584), [compile from source code](https://github.com/webcamoid/webcamoid/wiki/Build-and-install-in-Mac) or [homebrew](https://brew.sh).
