### ISSUE TITLE
 Setting Output Directory Path on Windows using Search/Select Folder adds extra slash

### ISSUE THREAD

**Issue by Anutrix** [webcamoid/webcamoid#577]
# Reporting a problem?
Yes.

## Summary
Setting Output Path on Windows using Search/Select Folder adds extra slash.

## Current Behavior
Setting Output Path on Windows using Search/Select Folder adds extra slash.
E.g, Selecting `D:/Webcamoid` *using the search button* stores path as `/D:/Webcamoid`.
Thus, Capture button doesn't do anything when path starts with `/`.
Happens for both video and picture output directories.

## Expected Behavior
Store correct path. And capture buttons should work.

## Steps to Reproduce
1.  Open Preferences.
2.  Click Search button for Video Directory path.
3.  Select any folder using the Windows Explorer selection UI.
4.  Notice path starts with `/`.

## Suggestions and tips

In the code logic, just remove(or don't add) extra slash at the beginning of path when saving path on Windows.
Additionally, Search button should renamed something like "Locate".

## Your Environment

* Webcamoid information: (version) (architecture) 9.0.0 64 bit - Qt 5.15.2
* Operating System information: (name) (numeric version and codename if applied) (architecture) Windows 11 Pro 22H2 64 bit
* Any other useful information: (logs, gdb backtrace, valgrind logs, screenshots, hardware, etc.) Lenovo FHD 300 Web Cam

**Comment by dchmelik** [comment]
There seems to be no such 'search' button so I can't save; why not have easier classic/standard menus?

**Comment by hipersayanX** [comment]
@dchmelik 

I don´t understand your complaining, the **Search** button is there and always was.

![Screenshot_20230512_182036](https://github.com/webcamoid/webcamoid/assets/1249885/42b2cdb0-6e12-4a6e-a146-c49ffe68e7ed)

Also, a saving button is not necessary, all options are automatically saved unless explicitly required, it's the same exact design as Gnome apps.

![gnome-tweak-tool](https://github.com/webcamoid/webcamoid/assets/1249885/746891ec-603a-4432-b84b-3d53ddddc710)

**Comment by hipersayanX** [comment]
Bug fixed in Webcamoid 9.1.0.
