### ISSUE TITLE
Please, update Fedora installation instructions

### ISSUE THREAD

**Issue by q2dg** [webcamoid/webcamoid#59]
Recent versions use dnf instead of yum. Specifically, here is current necessary steps: https://docs.fedoraproject.org/en-US/Fedora/23/html/System_Administrators_Guide/sec-Managing_DNF_Repositories.html
Thanks!

**Comment by hipersayanX** [comment]
This goes in sync with what I said [here](https://github.com/webcamoid/webcamoid/issues/56#issuecomment-287776138), I will be providing AppImages and installers since Webcamoid 8.0.0 (soon to be released) so no need to fix that.

**Comment by hipersayanX** [comment]
Now providing AppImages.
