### ISSUE TITLE
is there a webcamoid download for windows 7? 32bit

### ISSUE THREAD

**Issue by neuronetv** [webcamoid/webcamoid#591]
and a virtual camera driver to go with it?

**Comment by hipersayanX** [comment]
You have win32 packages:

```
webcamoid-installer-windows-daily-master-win32.exe 
webcamoid-portable-windows-daily-master-win32.zip 
```

in the [daily build](https://github.com/webcamoid/webcamoid/releases/tag/daily-build), maybe works, maybe does not, Idk, did not tested because Windows 7 is EOL and all CPU now a days are 64 bits. And the virtual camera supports 32 bits too.

**Comment by neuronetv** [comment]
thankyou I installed webcamoid on windows 7 from the links you gave however the program crashes as soon as the virtualcameradriver is installed.

**Comment by hipersayanX** [comment]
It works without the virtual camera?

**Comment by neuronetv** [comment]
yeah
