### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by joseangel-mm** [webcamoid/webcamoid#593]
I've tried to use the `webcamoid` package available [here](https://github.com/webcamoid/webcamoid/releases/download/9.0.0/webcamoid-installer-mac-9.0.0-x86_64.pkg) in a M1 Mac, but I didn't have success. 

Could it be possible to know how to use the app on these kinds of devices, please?

**Comment by hipersayanX** [comment]
Please read:  #584, #469, [comment](https://github.com/webcamoid/webcamoid/issues/469#issuecomment-1566317269).
