### ISSUE TITLE
webcamoid 7.2.1 can't add virtual device: wrong password

### ISSUE THREAD

**Issue by adamlazok** [webcamoid/webcamoid#60]
Debian stretch, 
Webcamoid 7.2.1,
Qt 5.7.1,
FFmpeg 3.2.4-1

running from terminal as root:
bash: -c: row: 0: syntax error „(” unexpected token
bash: -c: row: 0: `modprobe v4l2loopback video_nr=1,2 card_label=Dummy\ video\ device\ (0x0000),Virtual\ Camera\ 2'

su:"must run from terminal", 
or such, i had to translate.
I've tried from terminal as root, as user, user was in the sudoers, everything. So am i missing something?

**Comment by hipersayanX** [comment]
First at all, never run Webcamoid ar root, it does not need that.
About your problem, it seems to be this:

modprobe v4l2loopback video_nr=1,2 card_label=Dummy\ video\ device\ **(0x0000)**,Virtual\ Camera\ 2

Because the parentheses are not escaped, it's a bug, for the moment just set the device **Description** by hand to some thing like *My camera*, "virtual camera", or similar, without quotes or parentheses.

**Comment by adamlazok** [comment]
![screenshot_20170331_224540](https://cloud.githubusercontent.com/assets/17588285/24568907/2e7de0a6-1664-11e7-9c3d-45b9276752a5.png)

I've just entered root password, i tried my own password, same result.

**Comment by adamlazok** [comment]
I also tried w/o Description.

**Comment by hipersayanX** [comment]
And removing all devices first, and then add a new webcam again?

**Comment by adamlazok** [comment]
Nothing happens, just the password input field with the buttons disappears.

**Comment by hipersayanX** [comment]
And the previous device is still there?

**Comment by adamlazok** [comment]
Yes, the video1 device remains there.

**Comment by hipersayanX** [comment]
Wait, try 

    sudo rmmod v4l2loopback

from console, close and reopen Webcamoid, and create a new virtual camera.

**Comment by adamlazok** [comment]
"wrong password"

Devices field is empty. I removed the module before i started webcamoid (I'm sure: "rmmod: ERROR: Module v4l2loopback is not currently loaded").

**Comment by hipersayanX** [comment]
And trying adding the camera from console like this?

    sudo modprobe v4l2loopback video_nr=1 card_label=Virtual \Camera

**Comment by adamlazok** [comment]
Virtual (/dev/video1) appears in Preferences/Output, but still "wrong password".

**Comment by hipersayanX** [comment]
Ok, I will test it later, thank for reporting this bug!

**Comment by adamlazok** [comment]
Thank You very much, and let me know if I can help You in anything!

**Comment by adamlazok** [comment]
![screenshot_20170503_105204](https://cloud.githubusercontent.com/assets/17588285/25653922/42f6dd7c-2fef-11e7-9791-40729c066129.png)

Installing libjack-dev would like to remove libavdevice-dev, jackd2, pulseaudio-module-jack too.
libavdevice-dev is also on the dependency list. I'm using jackd2 so i can't uninstall. Can i help more?

**Comment by hipersayanX** [comment]
Its possible to specify a build dependency to something like _libjack-dev | libjack-jackd2-dev_ in Debian, so it can build with one or the other? if that's the case just do that, if not just remove jack as dependency.

**Comment by hipersayanX** [comment]
Webcamoid now support kdesu, gksu, and other graphical variants, that may solve the problem with the virtual camera.

**Comment by Camaro77** [comment]
What password are they asking for?

**Comment by hipersayanX** [comment]
@Camaro77 Use [latest version](https://github.com/webcamoid/webcamoid/releases/latest), old versions has no support.
