### ISSUE TITLE
Storing/Restoring device configs [was: Don't apply effects on Desktop Capture]

### ISSUE THREAD

**Issue by xbox360pad** [webcamoid/webcamoid#62]
First of all, excuse my bad english. I use ur program (latest git code) on Linux and i like it but, It's possible to apply effects only on webcam output? I use my webcam using some effect, but when i swith to desktop capture the effect is still applied, which does not make much sense.

 Is it possible to configure the effects for each device individually? 

It's possible to store webcam parameters like resolution and fps? Every time I select my webcam i have to reconfigure. 

Thanks in advance.

**Comment by hipersayanX** [comment]
Is not possible to set a per device effect, but is planned in the very log term, maybe after Webcamoid 10.x or higher, but I do not promise anything, I want to add support for layouts first and then add that feature.

Storing/Restoring device configs will come **after** Webcamoid 8.0.0 release, maybe 8.1 o 8.2, but is planned in the short term.

**Comment by hipersayanX** [comment]
As said before, implementing more complex audio and video combinations will take a very long time. But I can implement per device configs storing/Restoring, so changing the title of this issue.

**Comment by hipersayanX** [comment]
Save/Restore webcam format, resolution and FPS may now be working well in 8.6.0.
