### ISSUE TITLE
Changing FOV/fixing fisheye/lens distortions

### ISSUE THREAD

**Issue by ghost** [webcamoid/webcamoid#649]
Would it by possible to add an effect fixing the fisheye effect present at high fovs? Also then it would be great to add a slider to change FOV, so that i can „zoom“ in but still fisheye/lens distortion is changed in proportion.

(Kind of related to webcamoid/webcamoid#72 but the scope is different.)

**Comment by hipersayanX** [comment]
Webcamoid should be able to detect if FoV options are available for the camera in V4L2 in Webcamoid 9.2.0.
