### ISSUE TITLE
Cannot start at Xubuntu 17.04

### ISSUE THREAD

**Issue by Nick222** [webcamoid/webcamoid#65]
Xubuntu 17.04
Webcamoid 7.2.1+dfsg1-4

When try to start webcamoid in terminal I see:

> QQmlApplicationEngine failed to load component
> qrc:/Webcamoid/share/qml/main.qml:252 Type MediaBar unavailable
> qrc:/Webcamoid/share/qml/MediaBar.qml:138 Type AddMedia unavailable
> qrc:/Webcamoid/share/qml/AddMedia.qml:148 Type FileDialog unavailable
> qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:48 module "Qt.labs.settings" is not installed
> qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:47 module "Qt.labs.folderlistmodel" is not installed
> qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:48 module "Qt.labs.settings" is not installed
> qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:47 module "Qt.labs.folderlistmodel" is not installed

and it cannot run.

**Comment by hipersayanX** [comment]
Install:

* qml-module-qtquick-controls
* qml-module-qt-labs-settings
* qml-module-qt-labs-folderlistmodel

And report the issue [here](https://launchpad.net/ubuntu/+source/webcamoid/+bugs), so they add the missing dependencies.
