### ISSUE TITLE
Feature Request: Be able to auto rotate video 

### ISSUE THREAD

**Issue by broes5** [webcamoid/webcamoid#661]
# Feature Request
To have video auto rotate when the orientation of the laptop is changed, or have a setting in "Video Source Options" that can be used to manually change the video orientation.

## Reason
I own a ThinkPad L13 Yoga Gen 2. It is a convertible laptop with a second webcam mounted next to the keyboard, which is intended to be used when the laptop is in a tablet configuration. When I flip the laptop all the way around, so that the keyboard is facing in the opposite direction as the screen and then change the video source to the keyboard webcam, the video is upside down. I know that the laptop has an accelerometer, and the desktop environment is able to auto rotate the display when I flip my laptop into the tablet configuration. 

I'm aware of the matrix transform effect would be able to invert the video, but it's unintuitive and is applied to all video sources, which in my is case is not necessary for the first webcam (the one next to the screen). I'm not sure that there are many others in the same situation as me.

**Comment by hipersayanX** [comment]
Feature added in 9.2.0.
