### ISSUE TITLE
Webcamoid 9.1.0 and above no longer detects Droidcam source on Linux

### ISSUE THREAD

**Issue by pizzadude** [webcamoid/webcamoid#671]
## Summary

Webcamoid 9.1.0 and above no longer detects Droidcam source on Linux. This is with the flatpak from github releases, on Fedora 38 KDE. I tried the "installer" version and the AppImage and they simply don't open at all. Version 9.0.0 from flathub.org is able to detect and use Droidcam's source.

## Current Behavior

Version 9.0.0 from flathub can see droidcam just fine. Version 9.1.0 and above can't see droidcam.

## Expected Behavior

For droidcam's source to show in the latest version.

## Steps to Reproduce

If Webcamoid crashed, try to reproduce the crash several times to be sure where is the problem. Write the steps to reproduce the issue below:

1.  Install droidcam app on Android
2.  Install droidcam kernel module https://github.com/dev47apps/droidcam
3.  Start droidcam
4.  Start Webcamoid, notice no droidcam source.
5. Use flatpak from flathub, droidcam works as a source in that version

## Suggestions and tips

How would you solve the problem?

## Your Environment

* Webcamoid information: 9.1.1
* Operating System information: Fedora 38 KDE
* Any other useful information: (logs, gdb backtrace, valgrind logs, screenshots, hardware, etc.)

# Want a new feature?

Describe your idea the best as you can, include sketches, mockups and diagrams if required.  
Be patient, take in mind that there may be other priorities. Your idea will be accepted if fit in project goals.

# Questions and other matters?

Go ahead!

**Comment by hipersayanX** [comment]
Fixed in 9.2.0.
