### ISSUE TITLE
Flatpak downloaded, and now?

### ISSUE THREAD

**Issue by italovignoli** [webcamoid/webcamoid#680]
I have downloaded webcamoid-linux-9.1.1-x64.flatpak, but instead of having the proper Flatpak icon has the folder icon and doesn't install. Any help is appreciated.

**Comment by hipersayanX** [comment]
# Install

## for the current user only

```flatpak install -u webcamoid-*.flatpak```

## for all users

```sudo flatpak install webcamoid-*.flatpak```

# Running

```flatpak run io.github.webcamoid```
