### ISSUE TITLE
Bought app from official website and it's missing filter from the free version.

### ISSUE THREAD

**Issue by MarkoKurtovic** [webcamoid/webcamoid#681]
So I bought app because free version keeps crashing (can't even start it now). 

And I really liked filter in free version.

I bought app from official website for linux and I'm missing this filter.

Image with filter:

![Picture 2024-02-01 11-21-15](https://github.com/webcamoid/webcamoid/assets/61917143/ad5c81e6-4799-4868-97c2-e2c28a0dda19)

Please can someone help me to find this filter in new app or advice me how to install free app without crashing.

**Comment by hipersayanX** [comment]
All video filters are there. The one  you are looking for is probably the Photocopy effect.

![Screenshot_20240207_172203](https://github.com/webcamoid/webcamoid/assets/1249885/47c3615f-3116-43b7-9524-a344289355d4)

**Comment by MarkoKurtovic** [comment]
It's not same filter
![Screenshot from 2024-02-07 22-32-15](https://github.com/webcamoid/webcamoid/assets/61917143/de34d374-9fef-4e4b-bd75-5b8317a1d764)

**Comment by MarkoKurtovic** [comment]
that one I didn't have to setup, just to click on it and it worked.

I tried manipulation photoCopy but it's not the same.

**Comment by hipersayanX** [comment]
Then it should be the Black & white effect, and its there too.

![Screenshot_20240207_212947](https://github.com/webcamoid/webcamoid/assets/1249885/ab032879-a181-484f-b29d-30f04cd14ce4)

**Comment by MarkoKurtovic** [comment]
Unfortunately it's not.

it's just gray.
![Screenshot from 2024-02-08 14-21-21](https://github.com/webcamoid/webcamoid/assets/61917143/be6a5685-39df-4d29-813b-31bf3c84bcfd)

**Comment by hipersayanX** [comment]
The only effect that gives a black and white result without options is that. Are you not sure its just a room illumination thing? because in the first image you have a strong light focus in your side, and that can change the contrast of the image.
Maybe, did you combined two effects? for example Black & white with Gamma?

**Comment by MarkoKurtovic** [comment]
Ahh shit, I did use two effect by mistake probably.

Can't figure it out which ones, I'm trying for 1hour combinations
