### ISSUE TITLE
"No playable streams" - Saved video file

### ISSUE THREAD

**Issue by wmbm** [webcamoid/webcamoid#683]
## Summary / Current Behavior / Expected Behavior

Whilst I can take screenshot, the video aspect of webcam capture is not working for me. If I try to record from my webcam, a non-empty output file is saved but if I try to open it, it seems to be empty "This file contains no playable streams". I've tried without any audio input, as well as different webcam inputs, however I get the same issues. I've also experimented with different FPS/formattings/output file types etc.

## Steps to Reproduce

1.  Click record video
2.  Open recorded file
3.  Error message

## Your Environment

* Webcamoid information: Version 9.11
* Operating System information: Ubuntu 22.04.4 LTS

If any further information is needed, happy to provide

**Comment by hipersayanX** [comment]
Let's try the very basic. Set the camera resolution at 640x480, video format MP4, video codec libx264, audio codec AAC, does it works?

**Comment by wmbm** [comment]
Tried to follow your guide, but same response

_In Video Source Options_
Resolution : 640x480
Video Format: MJPG 
FPS: 30

_In Preferences-Video Recording_
File format: MP4 (MPEG-4 Part 14)
Video codec: MPEG-4 part 2 (**libx264 wasn't on the list**)
Audio codec: AAC

**Comment by hipersayanX** [comment]
Sorry for the delay, I was not able to test the program until now.
I tested the official release with the same parameters as you and its working fine for me, also the official release has the libx264 codec.
Both ffplay and VLC con play the video file, while Firefox and Chomium can't (probably because the codec MPEG-4 part 2 is no supported there).
Also, what was the size of the file recorded in your case?

**Comment by wmbm** [comment]
File size is 258 bytes

I installed via Ubuntu Software center and using version 9.1.1, so should be the same (and have libx264) 

I tried on VLC, as apposed to the basic Ubuntu video player, but still no playback.

**Comment by hipersayanX** [comment]
>File size is 258 bytes
>I tried on VLC, as apposed to the basic Ubuntu video player, but still no playback.

It did not recorded nothing, the file is not playable.

>I installed via Ubuntu Software center and using version 9.1.1, so should be the same (and have libx264)

Should be, but the package is not managed by me, and don't know if they are using the same source code as me. The precompiled packages that I provide for GNU/Linux are actually build in Ubuntu.

**Comment by sameersharma2006** [comment]
@wmbm  Does this occur with Webcamoid Snap Package ?

**Comment by hipersayanX** [comment]
Fixed in 9.2.0.
