### ISSUE TITLE
akvcam dkms install error

### ISSUE THREAD

**Issue by chuimoi** [webcamoid/webcamoid#688]
I tried to install akvcam in webcamoid but it didn't work, so I downloaded it manually. "akvcam-installer-gui-linux-1.2.5.run"
and execute this the result is:

[59481] Warning: Error! Bad return status for module build on kernel: 6.8.1-zen1-1-zen (x86_64)
Consult /var/lib/dkms/akvcam/1.2.5/build/make.log for more information.

[make.log](https://github.com/webcamoid/webcamoid/files/14736584/make.log)

i'm under arch linux with zen kernel and a ave installed webcamoid 9.1.1-1 and akvcam-dkms 1.2.5-1 with the AUR

**Comment by hipersayanX** [comment]
Fixed with akvcam 1.2.6.
