### ISSUE TITLE
Root method

### ISSUE THREAD

**Issue by darkodarko1** [webcamoid/webcamoid#689]
When I want to install a virtual camera I get the error "root method not set". I went to the preferences, found root method and it is empty, there isn't an option i can click. Any ideas how to fix this?

**Comment by hipersayanX** [comment]
If you are using GNU/Linux, you need to install pkexec (polkit) in your system.

**Comment by darkodarko1** [comment]
> If you are using GNU/Linux, you need to install pkexec (polkit) in your system.

It's already installed.

**Comment by hipersayanX** [comment]
Result of ```which pkexec```?
Which distribution and version are you using?
Are you using the Flatpak version?
From where did you downloaded Webcamoid?

**Comment by BO24EH-02** [comment]
Hi, we are having the same problem. 
We have policykit-1 downloaded. 
We are using 9.1.1.
We downloaded with: sudo snap install webcamoid. 
We are on Ubuntu 20.04 arm64.

**Comment by sameersharma2006** [comment]
> Hi, we are having the same problem. We have policykit-1 downloaded. We are using 9.1.1. We downloaded with: sudo snap install webcamoid. We are on Ubuntu 20.04 arm64.

Snaps are confined package and hence some features might not work with the snap package.


Snap Description (https://snapcraft.io/webcamoid);

![Screenshot from 2024-04-08 12-52-19](https://github.com/webcamoid/webcamoid/assets/164338475/839c55ab-47b7-4187-aac1-c987db2c6bc8)
