### ISSUE TITLE
NOT FREE

### ISSUE THREAD

**Issue by GlydetheSurfer** [webcamoid/webcamoid#695]
If you guys say it's free.. why is it requiring me to pay $1.50 for it? What an absolute lie.

![image](https://github.com/webcamoid/webcamoid/assets/32045132/7e23ac42-5c1d-493c-a548-880973df6c63)

**Comment by hipersayanX** [comment]
Webcamoid is Free as  in Free Speech, not as in free beer.

https://www.gnu.org/philosophy/free-sw.html.en

**Comment by hipersayanX** [comment]
>they said you just started charging money for it... so it WAS once "actually" free.

It was, yes. But I had to charge for it because I need the income. And anyways, actually any other FOSS project can do the same I'm doing, for example [Ardour is doing the same I'm doing](https://community.ardour.org/download).

>and idk if you are thinking about deleting this post.. at LEAST I got my message out!

I don't, as long as keep respectful.
