### ISSUE TITLE
Qt ..errors:    Wwayland and Networkmanager errors during installation

### ISSUE THREAD

**Issue by BENOIT92200** [webcamoid/webcamoid#699]
![Screenshot from 2024-06-08 10-56-34](https://github.com/webcamoid/webcamoid/assets/107204047/6aaaf729-de79-4ac9-bc30-83e0d4a783cb)

Hi

Did try to install today.  Got some error messages about :    .qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
. ""  AND qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" et  etc

P.S. IF possible display the release number / version of your software during installation process....

Thanks for your Help.

**Comment by hipersayanX** [comment]
Those are error messages of QtIFW (it should be fixed by Qt developers, not me), just keep installing and advice me if Webcamoid itself gives any error.
