### ISSUE TITLE
Crashes out of the box on Windows 10

### ISSUE THREAD

**Issue by clrg** [webcamoid/webcamoid#70]
Downloaded and installed 64-bit installer.

Opened Webcamoid.

Tried to record a video using default settings with the exception of enabling audio recording. After the save file dialog (which pops up before starting to record; presumably a file to stream the recording to) the program crashed straight away.

**Comment by hipersayanX** [comment]
Thanks a lot for the report!

**Comment by hipersayanX** [comment]
May be fixed in 8.1.0.
