### ISSUE TITLE
low fps above 640x480 resolution using windows 7 64bit

### ISSUE THREAD

**Issue by jwaves** [webcamoid/webcamoid#707]
I am using windows 7 64-bit with a good computer. I am getting low fps on any resolution above 640x480. I tested different webcam software with windows 7 and my webcam can get 30fps @ 2048x1536. So I know windows 7 and my camera are okay. I also tested my webcam with linux and webcamoid 9.0 and it works great, 30 fps at 2048x1536. I noticed that my linux version of webcamoid is using the  .MJPG video format. If I change to the yuyv  format in linux my fps drop to 5 fps as well. When I use Windows 7 64bit with webcamoid 9.1.1 there is only the option for the yuyv file format . It gets 10 fps at 1280x720 and 5fps  for any bigger resolutions . 

1.) Any advice how to get Webcamoid to increase its framerate in windows 7 ?

2.) Can I use  the mjpg video format for the Windows 7 version of webcamoid 9.1.1 ? 
      or some other video codec in windows 7  ? 

This seems to be a video format issue.

**Comment by hipersayanX** [comment]
In Windows 7, Webcamoid depends of DirectShow for capturing the camera, if DirectShow does not offers MJPG or H264 formats I can't do nothing. Media Foundation may work probably (not sure) but you need Window 8 if I remember well.

**Comment by jwaves** [comment]
So I am still not sure what a good next step to try and get mjpeg or other video format to work instead of the yuyv video format ?

**Comment by hipersayanX** [comment]
If you want I can send you the daily build to test it, there are some bugs I have fixed recently related to frame rate detection in Windows, not sure if these fixes addresses your case specifically, may be works maybe not, but let's try. Send me the buy ticket to my mail (**NOT HERE**), and I will send you the daily build.

**Comment by jwaves** [comment]
I bought a week ago, what email do I use ?

**Comment by hipersayanX** [comment]
hipersayan _dot_ x _at_ gmail _dot_ com (if I remember well, the mail also appears in the ticket).
