### ISSUE TITLE
Photos are bad in quality

### ISSUE THREAD

**Issue by lukamrkonjic** [webcamoid/webcamoid#712]
# README

Some considerations before doing anything:

* Search the [issues list](https://github.com/webcamoid/webcamoid/issues) for similar topics before opening a new one.
* If you know how to fix the problem, consider doing a [pull request](https://github.com/webcamoid/webcamoid/pulls) instead of opening a new issue.
* Only report problems in [latest](https://github.com/webcamoid/webcamoid/releases) and [development](https://github.com/webcamoid/webcamoid/) version. Reporting issues related to older versions will be rejected.
* Use [gist](https://gist.github.com/) to post logs longer than 1024 characters.
* Webcamoid as project, is not affiliated or endorsed to any distribution, report packaging problems in their respective issue tracker.
* Respect the templates, we need as much information as possible.
* Don't open an issue and disappear, we need you at least the first week to clear up missing information.
* Missing information makes useless and unsolvable an issue report.
* You are our debugger, eyes and hands, if an issue is not reproducible then you will be the only person able to solve it.
* Take a seat and wait for your turn, as many others that has their issues open, or much better try fixing it your self and collaborate with the solution :smile:

Choose one of the templates below that fit better your issue.

# Reporting a problem?

Using the Windows photo app, photos come out in 4k using my Logitech Brio. Using Webcamoid, the photos are in really bad quality, namely in 640x480.

How it should have work?

I want to be able to change the quality of my photos in the app. I have it set to 100% on the slider but it doesn't do anything.

## Suggestions and tips

Add a resolution dropdown of photo quality.

## Your Environment

9.1.1 portable

# Want a new feature?

Describe your idea the best as you can, include sketches, mockups and diagrams if required.  
Be patient, take in mind that there may be other priorities. Your idea will be accepted if fit in project goals.

# Questions and other matters?

Go ahead!

**Comment by hipersayanX** [comment]
You can select the resolution in the Main menu -> Video -> Configure source -> Video format and resolution.

![screenshot](https://github.com/user-attachments/assets/1545161a-8ffe-40da-8503-9c90ebcc8f5a)
