### ISSUE TITLE
Virtual camera not installing

### ISSUE THREAD

**Issue by conquistador8** [webcamoid/webcamoid#713]
Windows 11, Webcamoid 9.1.1
Webcamoid downloads and installs the virtual camera AkVirtualCamera9.1.3

It appears to install without error, but when Webcamoid is reloaded there are no outputs and it asks to install the Virtual Camera again. If I install again, there is an error message during the install.

**Comment by hipersayanX** [comment]
Will check!

**Comment by hipersayanX** [comment]
Send me the buy ticket with the Payhip form submission, so I send you the daily build for testing.

**Comment by hipersayanX** [comment]
Fixed in 9.2.0.
