### ISSUE TITLE
colorconv.cpp::i420_to_rgb3 maybe wrong?

### ISSUE THREAD

**Issue by tristsesame** [webcamoid/webcamoid#74]
hi, when I saw the code:
libAvKys\Plugins\VirtualCamera\src\dshow\VirtualCameraFilter\VirtualCameraSource\src\colorconv.cpp
line:863             uint8_t y = line_y[j]; 
I think it should be  line_y[x];

**Comment by hipersayanX** [comment]
Yep indeed, luminance channel area must be the same size of the image.

**Comment by hipersayanX** [comment]
Thanks
