### ISSUE TITLE
Building on Mac - what do I do after opening with Qt Creator?

### ISSUE THREAD

**Issue by theonlygusti** [webcamoid/webcamoid#76]
I can't figure out how to complete step 6 of the mac build instructions:

> In Build, in Build environment add /usr/local/bin to PATH variable.

This is what I see when I open `Webcamoid.pro` in Qt Creator:

![](http://i.cubeupload.com/MYOpsv.png)

**Comment by hipersayanX** [comment]
Click in **Configure project**, wait until the project is loaded, then go to the left bar in **Projects** > **Build & Run** > **Build** > **Build Environment** > **PATH** and click **Edit**.

**Comment by theonlygusti** [comment]
Do you mean click the button on the right that says "Configure Project"? It's disabled and I can't click it.

The screen shot I've sent is exactly what I see after opening Webcamoid.pro, and it's been like this for hours.

**Comment by hipersayanX** [comment]
Click in **Details**, check all checkboxes and then click in **Configure Project**.

**Comment by theonlygusti** [comment]
Details has no checkboxes:

![](http://i.cubeupload.com/XrpJUD.png)

**Comment by hipersayanX** [comment]
You must install [Xcode](https://developer.apple.com/xcode/) and [command line tools](http://railsapps.github.io/xcode-command-line-tools.html).

**Comment by theonlygusti** [comment]
I've already done that

**Comment by theonlygusti** [comment]
Oh, I just found out about the GH pages site.

All I want to do is have webcamoid on my computer for streaming certain apps through things like Skype, 

can I just download the installer from webcamoid.github.io?

**Comment by hipersayanX** [comment]
Answered [here](https://github.com/webcamoid/webcamoid/issues/68#issuecomment-325493470), so closing this issue.
