### ISSUE TITLE
[Installer] Windows AMD64(x64) version installs into `C:\Program Files (x86)` instead of `C:\Program Files`

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [webcamoid/webcamoid#78]
It seems that the wrong installation directory is chosen, although it shouldn't cause any noticeable problem though.

### Operating System
Windows 7 Enterprise Service Pack 1(AMD64)

### Default Locale
Codepage 950(BIG5)

### Webcamoid Installer Filename
webcamoid-8.0.0-win64.exe

**Comment by Lin-Buo-Ren** [comment]
![Screenshot](https://user-images.githubusercontent.com/13408130/30010893-d529a1de-9165-11e7-9976-11275b8d720a.png)

Also the installation progress stuck here somehow, however this should be in a separate issue.

**Comment by hipersayanX** [comment]
Will check this, thanks!

**Comment by hipersayanX** [comment]
Fixed in 8.1.0, closing.
