### ISSUE TITLE
Webcamoid GUI glitches on Win10 x64 VM

### ISSUE THREAD

**Issue by Jassens** [webcamoid/webcamoid#79]
Hello,
Webcamoid´s GUI causes graphical glitches like this:

![virtualbox_mk_08_09_2017_07_01_27](https://user-images.githubusercontent.com/31560574/30197972-8dbbec36-946b-11e7-8b65-3c1647751f6c.jpeg)

Thank you.

**Comment by hipersayanX** [comment]
Is a known bug, and affects all platforms, it appeared after switching to [QSGSimpleTextureNode](https://github.com/webcamoid/webcamoid/blob/master/StandAlone/src/videodisplay.cpp#L53) for remove hard OpenGL dependency, it seems QSGSimpleTextureNode doesn't scale the frame using a smooth filter, I'm pretty sure there is an easy fix for this.

**Comment by hipersayanX** [comment]
May be fixed in 8.1.0, closing.
