### ISSUE TITLE
Desktop file does not pass desktop-file-validate, lacking Type=Application

### ISSUE THREAD

**Issue by probonopd** [webcamoid/webcamoid#80]
webcamoid.desktop: error: required key "Type" in group "Desktop Entry" is not present

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/277000676#L693

**Comment by hipersayanX** [comment]
Hi, it was fixed a few days ago, it will be ready for Webcamoid 8.1.0.

**Comment by hipersayanX** [comment]
Webcamoid 8.1.0 ready!
