### ISSUE TITLE
Crash after switching video

### ISSUE THREAD

**Issue by JustSpartak** [webcamoid/webcamoid#84]
Hello. I got instant crash when I am trying to switch between two preloaded video clips. Would be very nice if this issue could be fixed.

**Comment by hipersayanX** [comment]
8.1.0 right? Will check this, did you experienced other crashed besides this?

**Comment by JustSpartak** [comment]
Yes 8.1.0 x64... Other crashes I didn't expericed)

**Comment by hipersayanX** [comment]
Can't reproduce the issue, valgrind does not point nothing related to it.
