### ISSUE TITLE
build error on freebsd 12

### ISSUE THREAD

**Issue by zhou0** [webcamoid/webcamoid#88]
/usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/libAvKys/Plugins/MultiSrc/src/ffmpeg/src/audiostream.cpp:146:27: error: 
      reinterpret_cast from 'nullptr_t' to 'AVFrame *' is not allowed
        this->dataEnqueue(reinterpret_cast<AVFrame *>(NULL));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[4]: stopped in /usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/build/libAvKys/Plugins/MultiSrc/src/ffmpeg
*** Error code 1

Stop.
make[3]: stopped in /usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/build/libAvKys/Plugins/MultiSrc
*** Error code 1

Stop.
make[2]: stopped in /usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/build/libAvKys/Plugins
*** Error code 1

Stop.
make[1]: stopped in /usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/build/libAvKys
*** Error code 1

Stop.
make: stopped in /usr/home/lzhou/github.com/webcamoid/webcamoid/archive/webcamoid-8.0.0/build

**Comment by hipersayanX** [comment]
that error was fixed in 8.1.0.
