### ISSUE TITLE
Can't change media file on virtual camera

### ISSUE THREAD

**Issue by TheCNixon** [webcamoid/webcamoid#91]

**Comment by hipersayanX** [comment]
Need more info.

**Comment by TheCNixon** [comment]
Unable to edit the "Media file", it's stuck as "\\?\root#image#0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global".

**Comment by hipersayanX** [comment]
I will close this issue and continue in this one #90 since it's part of the same problem, ok?
