### ISSUE TITLE
How to set a video file as virtual camera

### ISSUE THREAD

**Issue by AhmedFaraz09** [webcamoid/webcamoid#92]
I want a video file to detected as a virtual camera on **Skype** 
I am using **windows 10 64-bit**. I have tried both 32-bit and 64-bit versions of **webcamoid** but I can't figure out how to do it. When I try to add a virtual camera in **preferences->output**, The only option which is available is of Description and there is no option to specify a video path.
![webc](https://user-images.githubusercontent.com/31037598/31940450-a6e75e44-b8d7-11e7-91e5-0ace70f04f11.png)
I even tried adding my video in sources, but then it wouldn't appear in video camera options in skype,
![webd](https://user-images.githubusercontent.com/31037598/31940586-19f69bac-b8d8-11e7-8858-83e9915b1f19.png)

**Comment by hipersayanX** [comment]
Just add the camera, it will output whatever media you have selected for play.

**Comment by AhmedFaraz09** [comment]
I added the camera but the edit button is disabled.
![webdc](https://user-images.githubusercontent.com/31037598/31942724-b9570388-b8df-11e7-9cc5-353032d57c51.png)

**Comment by hipersayanX** [comment]
That's the virtual webcam, now you must select the file, desktop, or webcam you want to play, in the left bar, that is what other programs will see.

**Comment by AhmedFaraz09** [comment]
Ok i tried that I added a file in the left bar and played it 
![webdc](https://user-images.githubusercontent.com/31037598/31944743-87166f60-b8e6-11e7-92f4-603a2c029aed.png)

but Skype and vlc still play's that same image. 
![webdc](https://user-images.githubusercontent.com/31037598/31944939-26035aca-b8e7-11e7-9ee8-dfd80f8ffa17.png)
 
I even tried VLC it also plays the same image when I select **TestCam** the (virtual camera i created in webcamoid)

**Comment by hipersayanX** [comment]
You problem is the same as @TheCNixon in #90 and it was opened before, let close this and continue there to centralize information, ok?
