### ISSUE TITLE
webcamoid appimages icon missing 

### ISSUE THREAD

**Issue by Lvaskz** [webcamoid/webcamoid#94]
hi, i am using webcamoid, but the icon is not appearing  in the system, can you provide one?
here i get one
![webcamoid](https://user-images.githubusercontent.com/29207169/32330762-bb10bfb6-bfa6-11e7-9d59-8f87f90a4ef6.png)
![webcamoid](https://user-images.githubusercontent.com/29207169/32330772-c459f0c4-bfa6-11e7-938a-c7a3c16a949a.png)

**Comment by hipersayanX** [comment]
Appimages are ELF executable binaries, and ELFs does not have an icon by design. Showing an icon depends absolutely on desktop implementation, I also remember there where some trick to show appimages icons with appimaged or something like that, but is much better if you as in their [official repository](https://github.com/AppImage/AppImageKit).

**Comment by Lvaskz** [comment]
hi, i am using appimaged ( daemond ) and the icon in the app menu is missing. The app is in the app menu but not the icon. Can you ask some help to @probono ? the app is cool

**Comment by hipersayanX** [comment]
Ok, I will ask but not sure it will work.

**Comment by Lvaskz** [comment]
Thanks

**Comment by Lvaskz** [comment]
Hi, I am using appimagelauncher https://github.com/TheAssassin/AppImageLauncher and I have the same issue. Thanks for your efforts in this.
I can assigne an Icon from( linuxmint 19.1)  cinnamon menu manually is not a real solution but it is fine to me. But It would be great if some day can be resolved 
thanks

**Comment by hipersayanX** [comment]
Oh, get it, that's the program that assign the icons to the AppImages, will check.

**Comment by hipersayanX** [comment]
Fixed in 8.6.1.

**Comment by Lvaskz** [comment]
thanks, works fine
